.github/pull_request_template.md

Create a basic PR template with following 3 sections:
1. What changes were proposed in this pull request?
2. Link to the Apache JIRA
3. How was this patch tested?
This template is adapted from Apache Hadoop Ozone: https://github.com/apache/hadoop-ozone/blob/master/.github/pull_request_template.md
The only way to test this is to create a new PR after committing this to master.

RATIS-741. Create a Github PR template

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java

I test with the patch, the failed unit test will not happen again.

RATIS-849. Fix Failed UT: GroupManagementBaseTest.runMultiGroupTest

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

Reverts apache/incubator-ratis#71

Revert "RATIS-991. Fix Failed UT: testRestartLogAppender"

---

ratis-common/src/main/java/org/apache/ratis/retry/ExponentialBackoffRetry.java
ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-test/src/test/java/org/apache/ratis/retry/TestExponentialBackoffRetry.java

Apache jira
https://issues.apache.org/jira/browse/RATIS-882

RATIS-882. Implement ExponentialBackoffRetry.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

RATIS-914. Fix Failed UT: can not mock final class

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

When remove group, `RaftServerImpl` try to remove storage dir on disk. But sometimes leader election thread has not become dead, and still rename the file in storage dir. Then `FileUtils.deleteFully` will throw `NoSuchFileException`, because the file has been renamed by leader election thread. 
You can find from the following stack, `RaftServerImpl` try to delete raft-meta, but leader election thread try to rename raft-meta at the same time, then both fail.
When `FileUtils.deleteFully` throw `NoSuchFileException`, we can retry.

RATIS-930. Fix failed to remove RaftStorageDirectory

---

ratis-logservice/src/main/java/org/apache/ratis/logservice/server/LogServiceRaftLogReader.java

RATIS-892. Fix failed UT: TestMetaServer.testReadWritetoLog

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

Please see https://issues.apache.org/jira/browse/RATIS-959

RATIS-959. Refactor xxxStateMachineData methods.

---

ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java

See https://issues.apache.org/jira/browse/RATIS-960

RATIS-960. Add APIs to support streaming state machine data.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

At 2020-06-18 00:46:43,636, s0 was elected as leader, but after 76ms i.e. 2020-06-18 00:46:43,712, a new leader election happens because `lastRpcTime:175ms, electionTimeout:169ms`. The root cause is [fs.updateLastRpcTime(FollowerState.UpdateType.REQUEST_VOTE)](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java#L839) happens before [state.persistMetadata()](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java#L844), and  `state.persistMetadata()` sometimes cost very long, because it needs to force sync data to disk.
How to fix ?
[fs.updateLastRpcTime(FollowerState.UpdateType.REQUEST_VOTE)](https://github.com/apache/i …

RATIS-980. Fix leader election happens too fast

---

pom.xml

Update gRPC to 1.29.0
https://issues.apache.org/jira/browse/RATIS-963
Build works

RATIS-963. Update gRPC to 1.29.0.

---

ratis-docs/pom.xml

To include bash executable in configuration to run generate-site.sh file.
https://issues.apache.org/jira/browse/RATIS-974
Existing tests. Only changes to pom file.

RATIS-974. Build fails on Windows machine

---

content/post/1.0.0.md
layouts/index.html

Include download links, announcement and relevant information related to release 1.0.0 in the project website. It also adds information regarding 1.0.0 being GA release.
https://issues.apache.org/jira/browse/RATIS-1010
Manual test

RATIS-1010. List release 1.0.0 in website

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeer.java
ratis-common/src/main/java/org/apache/ratis/util/ProtoUtils.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/test/java/org/apache/ratis/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java

Change proto and RaftConfiguration to support priority
https://issues.apache.org/jira/browse/RATIS-1032
add ut to test it.

RATIS-1032. Change proto and RaftConfiguration to support priority

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java

Change leader election to add priority consideration
https://issues.apache.org/jira/browse/RATIS-1033
add ut to test it.

RATIS-1033. Change leader election to add priority consideration

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java

Change leader heartbeat to yield to a higher priority leader
https://issues.apache.org/jira/browse/RATIS-1034
add test

RATIS-1034. Change leader heartbeat to yield to a higher priority leader

---

ratis-examples/src/main/java/org/apache/ratis/examples/counter/client/CounterClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/common/Constants.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

Math operands should be cast before assignment
RATIS-1052
It is already a test.

RATIS-1053. Math operands should be cast before assignment

---

ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java

The test failed because the actual elected leader is not the expected leader.
Analysis:
The original test keeps only one follower and kill other follower, then write a new message to Ratis ring. So the only left follower will have one entry that other closed follower do not have.
Then the test kills the leader. The intention here is to expect that follower with higher entry index be selected as leader. However, because only one follower has higher entry index, so Ratis does not guarantee that follower is elected.
The resolution is to keep at least half of followers alive to preserve that higher entry index. 
https://issues.apache.org/jira/browse/RATIS-1063
UT

RATIS-1063. Failed UT: testOldLeaderCommit: expected leader is different than actual leader

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/api/MessageOutputStream.java
ratis-client/src/main/java/org/apache/ratis/client/api/MessageStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/MessageStreamImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/io/CloseAsync.java
ratis-server/src/test/java/org/apache/ratis/MessageStreamApiTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestMessageStreamApiWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1080

RATIS-1080. Rename StreamApi to MessageStreamApi.

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamFactory.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DataStreamServerImpl.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStream.java

See https://issues.apache.org/jira/browse/RATIS-1081

RATIS-1081. Change NettyServerStreamRpc to write data to StateMachine.

---

ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1087

RATIS-1087. Add setConfiguration tests with single node clusters.

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-common/src/main/java/org/apache/ratis/util/PeerProxyMap.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamFactory.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServer.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServerRpc.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DataStreamServerImpl.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStream.java

See https://issues.apache.org/jira/browse/RATIS-1099

RATIS-1099. DataStreamServerRpc should connect other peers automatically

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-client/src/main/java/org/apache/ratis/client/RaftClientRpc.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/GroupManagementImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientRpcWithProxy.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeer.java
ratis-common/src/main/java/org/apache/ratis/util/PeerProxyMap.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientStreamer.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServerRpc.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServerRpc.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerRpcWithProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedClientRpc.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedServerRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStream.java

See https://issues.apache.org/jira/browse/RATIS-1103

RATIS-1103. Add an interface for adding RaftPeers.

---

ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamReplyByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacket.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacketHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReplyHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/DataStreamReplyDecoder.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamReplyEncoder.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStream.java

See https://issues.apache.org/jira/browse/RATIS-1098

RATIS-1098. DataStreamReply should include byteWritten and isSuccess.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketImpl.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamReplyByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacket.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacketHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReplyHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamRequestByteBuf.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-proto/src/main/proto/Raft.proto
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStream.java

Add DataStreamRequestType: HEAD, DATA, CLOSE, START_TRANSACTION
https://issues.apache.org/jira/browse/RATIS-1106
New assert

RATIS-1106. Add type for DataStream

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStream.java

See https://issues.apache.org/jira/browse/RATIS-1110

RATIS-1110. Fix DataStreamReply out of order.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1114

RATIS-1114. Change NettyServerStreamRpc to use only one ConcurrentMap.

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamBase.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1121

RATIS-1121. Support multiple streams.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamBase.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1123

RATIS-1123. Support multiple DataStream clients.

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamFactory.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/DisabledDataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DataStreamServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1124

RATIS-1124. NettyServerStreamRpc should get stateMachine from RaftServer

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamFactory.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/DisabledDataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DataStreamServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1127

RATIS-1127. Add a stream(RaftGroupId) method to DataStreamApi.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

Support multiple groups in Streaming
https://issues.apache.org/jira/browse/RATIS-1084
UT

RATIS-1084. Support multiple groups in Streaming

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

Use thenApplyAsync instead of thenApply
https://issues.apache.org/jira/browse/RATIS-1122
No need to add new ut.

RATIS-1122. Use thenApplyAsync instead of thenApply

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientImplUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java

Implement RaftClient.getDataStreamApi
https://issues.apache.org/jira/browse/RATIS-1090
Existed ut.

RATIS-1090. Implement RaftClient.getDataStreamApi

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/MessageStreamImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/MessageStreamRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

See https://issues.apache.org/jira/browse/RATIS-1137

RATIS-1137. Rename StreamRequestTypeProto to MessageStreamRequestTypeProto

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientImplUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftGroup.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeer.java
ratis-common/src/main/java/org/apache/ratis/util/NetUtils.java
ratis-common/src/main/java/org/apache/ratis/util/ProtoUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-proto/src/main/proto/Raft.proto
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1138

RATIS-1138. Add dataStreamAddress to RaftPeer.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1148

RATIS-1148. In NettyServerStreamRpc, each remote stream should not wait for its own previous write.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

Return exception of submitClientRequestAsync to client
https://issues.apache.org/jira/browse/RATIS-1143
new ut.

RATIS-1143. Return exception of submitClientRequestAsync to client

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketImpl.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamReplyByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacket.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacketHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamRequestByteBuf.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1155

RATIS-1155. Add a builder for DataStreamReplyByteBuffer.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/DataStreamException.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-proto/src/main/proto/Raft.proto
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

Return DataStreamException to client
https://issues.apache.org/jira/browse/RATIS-1150
new u

RATIS-1150. Return DataStreamException to client

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/util/ProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/util/ReflectionUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/util/MetaServiceProtoUtil.java
ratis-proto/src/main/proto/Raft.proto

See https://issues.apache.org/jira/browse/RATIS-1158

RATIS-1158. Use the same proto for StateMachineExceptionProto, AlreadyClosedExceptionProto and DataStreamExceptionProto.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/ClientId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftGroupId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftId.java
ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1153

RATIS-1153. Implement ChannelInboundHandler.exceptionCaught in NettyServerStreamRpc

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamOutput.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTests.java

Add sync flag when write stream data
https://issues.apache.org/jira/browse/RATIS-1154
new assert

RATIS-1154. Add sync flag when write stream data

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/JvmPauseMonitor.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java

See https://issues.apache.org/jira/browse/RATIS-1136

RATIS-1136. Add DataStreamRequestTypeProto.

---

ratis-metrics/src/main/java/org/apache/ratis/metrics/MetricRegistriesLoader.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/RefCountingMap.java

See https://issues.apache.org/jira/browse/RATIS-1163

RATIS-1163. RefCountingMap is not thread-safe.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientTestUtil.java
ratis-common/src/main/java/org/apache/ratis/protocol/ClientInvocationId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientReply.java
ratis-server/src/main/java/org/apache/ratis/server/impl/MessageStreamRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RetryCache.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RetryCacheTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1165

RATIS-1165. Add ClientInvocationId.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/DataStreamMap.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DataStreamMapImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1166

RATIS-1166. Link DataStream with LogEntryProto.

---

ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1168

RATIS-1168. Move the utils from DataStreamBaseTest to a new file.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

See https://issues.apache.org/jira/browse/RATIS-1171

RATIS-1171. Allow null for the stream parameter in StateMachine.DataApi.link

---

ratis-common/src/main/java/org/apache/ratis/protocol/ClientInvocationId.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

See https://issues.apache.org/jira/browse/RATIS-1173

RATIS-1173. Rename StateMachineDataChannel to DataChannel.

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamOutput.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/util/JavaUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

See https://issues.apache.org/jira/browse/RATIS-1175

RATIS-1175. DataStreamOutput should support FileChannel#transferTo.

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamOutput.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestFilePositionCount.java
ratis-common/src/main/java/org/apache/ratis/io/FilePositionCount.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacketHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReplyHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

See https://issues.apache.org/jira/browse/RATIS-1179

RATIS-1179. Add a new API to DataStreamOutput for sending a File.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcFactory.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/HadoopFactory.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyFactory.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/leader/FollowerInfo.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/LogAppenderMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestLogAppenderMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedRpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1191

RATIS-1191. Define an interface for FollowerInfo.

---

ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

Test leader change when close stream
https://issues.apache.org/jira/browse/RATIS-1174
new ut

RATIS-1174. Test leader change when close stream

---

ratis-server/src/main/java/org/apache/ratis/server/DivisionInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/StateMachineShutdownTests.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestCacheEviction.java

See https://issues.apache.org/jira/browse/RATIS-1197

RATIS-1197. Add getRoleInfoProto() and other methods to DivisionInfo.

---

ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RetryCacheTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/StateMachineShutdownTests.java
ratis-server/src/test/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogTestUtils.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestCacheEviction.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

See https://issues.apache.org/jira/browse/RATIS-1199

RATIS-1199. Change RaftServerProxy/RaftServerImpl to package private.

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-examples/pom.xml
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreStreamingBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/TestFileStoreStreamingWithGrpcCluster.java
ratis-proto/src/main/proto/Examples.proto

https://issues.apache.org/jira/browse/RATIS-1111
UT

RATIS-1111. Change the FileStore example to use Streaming

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/InstallSnapshotRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/FileChunkReader.java
ratis-server/src/main/java/org/apache/ratis/statemachine/SnapshotInfo.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/FileListSnapshotInfo.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/SingleFileSnapshotInfo.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1200

RATIS-1200. Refactor LogAppender.SnapshotRequestIter.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/DivisionProperties.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DivisionPropertiesImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LeaderState.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1205

RATIS-1205. Change LogAppender to use RaftServer.Division and LeaderState

---

ratis-common/src/main/java/org/apache/ratis/util/LifeCycle.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppenderDaemon.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java

See https://issues.apache.org/jira/browse/RATIS-1206

RATIS-1206. Use atomic update instead of synchronized in AppenderDaemon.

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java

See https://issues.apache.org/jira/browse/RATIS-1209

RATIS-1209. Compare the performance between DataStreamApi and AsyncApi.

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

Remove steams from StreamMap when close stream
https://issues.apache.org/jira/browse/RATIS-1212
No need to add ut.

RATIS-1212. Remove steams from StreamMap when close stream

---

ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreAsyncBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreStreamingBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreWriter.java

https://issues.apache.org/jira/browse/RATIS-1201

RATIS-1201. Enhance FileStore steaming tests

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

Fix TestLogAppenderWithSimulatedRpc.testUnlimitedElementBuffer throw NPE
https://issues.apache.org/jira/browse/RATIS-1211
test TestLogAppenderWithSimulatedRpc.testUnlimitedElementBuffer 100 times in a while

RATIS-1211. Fix TestLogAppenderWithSimulatedRpc.testUnlimitedElementBuffer throw NPE

---

ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/RetryCache.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RetryCacheImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetrics.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RetryCacheTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRetryCacheWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

See https://issues.apache.org/jira/browse/RATIS-1210

RATIS-1210. Expose RetryCache.

---

ratis-server/src/main/java/org/apache/ratis/server/RaftConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ConfigurationManager.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogSequentialOps.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorage.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1219

RATIS-1219. Define an interface for RaftConfiguration.

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileInfo.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java

See https://issues.apache.org/jira/browse/RATIS-1220

RATIS-1220. FileStore stream to send small packets for MappedByteBuffer and NettyFileRegion.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/GroupManagementImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientTestUtil.java
ratis-client/src/main/java/org/apache/ratis/client/impl/UnorderedAsync.java
ratis-common/src/main/java/org/apache/ratis/rpc/CallId.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerConstants.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java

See https://issues.apache.org/jira/browse/RATIS-1224

RATIS-1224. Define a CallId class.

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/LoadGen.java

FileStore write file in parallel
https://issues.apache.org/jira/browse/RATIS-1223
test it with manually command.

RATIS-1223. FileStore write file in parallel

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

Move log level from warn to debug, if directory name is of not in the format of UUID.
https://issues.apache.org/jira/browse/RATIS-1232

RATIS-1232. Change error log message in initGroups.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/statemachine/TransactionContext.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/TransactionContextImpl.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java

See https://issues.apache.org/jira/browse/RATIS-1233

RATIS-1233. Move the StateMachineData methods from ServerProtoUtils to LogProtoUtils

---

ratis-server/src/main/java/org/apache/ratis/server/RaftConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/leader/InstallSnapshotRequests.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LeaderProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/protocol/TermIndex.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorage.java

See https://issues.apache.org/jira/browse/RATIS-1236

RATIS-1236. Move out the leader only methods from ServerProtoUtils.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/main/java/org/apache/ratis/server/protocol/TermIndex.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/util/ServerStringUtils.java

See https://issues.apache.org/jira/browse/RATIS-1237

RATIS-1237. Move out the string method from ServerProtoUtils.

---

ratis-common/src/main/java/org/apache/ratis/util/AtomicFileOutputStream.java
ratis-server-api/src/main/java/org/apache/ratis/server/storage/FileInfo.java
ratis-server-api/src/main/java/org/apache/ratis/server/storage/RaftStorage.java
ratis-server-api/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectory.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/storage/FileChunkReader.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

See https://issues.apache.org/jira/browse/RATIS-1250

RATIS-1250. Move RaftStorage classes to ratis-server-api.

---

ratis-common/src/main/java/org/apache/ratis/protocol/ClientId.java
ratis-common/src/main/java/org/apache/ratis/util/ReflectionUtils.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/SnapshotInfo.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/SnapshotRetentionPolicy.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachineStorage.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/TransactionContext.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ConfigurationManager.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/SimpleStateMachineStorage.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/TransactionContextImpl.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

See https://issues.apache.org/jira/browse/RATIS-1251

RATIS-1251. Move StateMachine and TransactionContext to ratis-server-api

---

ratis-server-api/src/main/java/org/apache/ratis/server/metrics/RaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/LogAppenderMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetricsBase.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogInputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogReader.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestLogAppenderMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

See https://issues.apache.org/jira/browse/RATIS-1252

RATIS-1252. Refactor RaftLogMetrics.

---

ratis-server-api/src/main/java/org/apache/ratis/server/metrics/RaftLogMetrics.java
ratis-server-api/src/main/java/org/apache/ratis/server/protocol/TermIndex.java
ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/LogEntryHeader.java
ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetricsBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLogTest.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

See https://issues.apache.org/jira/browse/RATIS-1256

RATIS-1256. Leader updateCommit should use the updated index.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

**Steps to reproduce issue**
- Setup a 3 node ratis group.
- Write some transactions into the quorum.
- Bring 1 peer down.
- Write more transactions into the quorum (other 2 nodes), take a snapshot at the last txn and purge logs from the remaining 2 nodes.
- Start the node that was brought down.
- Leader falls into a possible irrecoverable state with respect to appending log entries to the follower.
**Stack trace**
> 2020-12-15 15:42:01,572 [omNode-3@group-523986131536->omNode-2-GrpcLogAppender-LogAppenderDaemon] > ERROR leader.LogAppenderDaemon (LogAppenderDaemon.java:run(86)) - omNode-3@group-523986131536->omNode-2-> GrpcLogAppender-LogAppenderDaemon failed
>org.apache.ratis.server.raftlog.RaftLogIOException: Log entry not found: index = 205
>        at …

RATIS-1241. Leader unable to append logs to a recovering follower when its logs have been purged.

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientAsynchronousProtocol.java
ratis-common/src/main/java/org/apache/ratis/protocol/TransferLeadershipRequest.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientRpc.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/client/CombinedClientProtocolClientSideTranslatorPB.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/client/CombinedClientProtocolServerSideTranslatorPB.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/client/HadoopClientRpc.java
ratis-hadoop/src/main/proto/HadoopCompatability.proto
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java
ratis-proto/src/main/proto/Grpc.proto
ratis-proto/src/main/proto/Hadoop.proto
ratis-proto/src/main/proto/Netty.proto
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedServerRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

subtask of Support rolling upgrade and rollback: Add transfer leadership request and proto
https://issues.apache.org/jira/browse/RATIS-1254
No need ut.

RATIS-1254. Add transfer leadership request and proto

---

ratis-examples/src/main/java/org/apache/ratis/examples/common/SubCommandBase.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreStreamingBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreWriter.java

FileStore support routing table
https://issues.apache.org/jira/browse/RATIS-1253
no need new ut

RATIS-1253. FileStore support routing table

---

ratis-server-api/src/main/java/org/apache/ratis/server/metrics/RaftServerMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerSlownessDetection.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1257

RATIS-1257. Refactor RaftServerMetrics.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/LeaderSteppingDownException.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/TransferLeadershipException.java
ratis-common/src/test/java/org/apache/ratis/BaseTest.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

Implement transferLeaderShip in server
https://issues.apache.org/jira/browse/RATIS-1260
TODO

RATIS-1260. Implement transferLeaderShip in server

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-test/src/test/java/org/apache/ratis/client/TestClientProtoUtils.java
ratis-test/src/test/java/org/apache/ratis/retry/TestRetryPolicy.java

Refactor RaftClientRequest to use Builder
https://issues.apache.org/jira/browse/RATIS-1263
no need new ut.

RATIS-1263. Refactor RaftClientRequest to use Builder

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-proto/src/main/proto/Raft.proto

Move routingTable to RaftRpcRequestProto
https://issues.apache.org/jira/browse/RATIS-1264
no need new test

RATIS-1264. Move routingTable to RaftRpcRequestProto

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/TransferLeadershipRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/LeaderSteppingDownException.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/TransferLeadershipException.java
ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyRpcProxy.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

Add timeout in TransferLeadershipRequest
https://issues.apache.org/jira/browse/RATIS-1261
new ut

RATIS-1261. Add timeout in TransferLeadershipRequest

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/api/AdminApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AdminImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-server/src/test/java/org/apache/ratis/RaftExceptionBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1269

RATIS-1269. Add a new AdminApi for RaftClient.

---

pom.xml
ratis-common/pom.xml
ratis-common/src/main/java/org/apache/ratis/util/ReflectionUtils.java
ratis-examples/pom.xml
ratis-grpc/pom.xml
ratis-hadoop/pom.xml
ratis-logservice/pom.xml
ratis-metrics/pom.xml
ratis-replicated-map/pom.xml
ratis-server/pom.xml
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-test/pom.xml
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java
ratis-test/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

See https://issues.apache.org/jira/browse/RATIS-1271

RATIS-1271. Bump mockito version.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketImpl.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamReplyByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestFilePositionCount.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacket.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacketHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReplyHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamRequestByteBuf.java
ratis-proto/src/main/proto/Raft.proto
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

Fix duplicated StreamMap#Key
https://issues.apache.org/jira/browse/RATIS-1207
new assert

RATIS-1207. Fix duplicated StreamMap#Key

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

Fix FileStore write failed because out of order
https://issues.apache.org/jira/browse/RATIS-1277
test it manually

RATIS-1277. Fix FileStore write failed because reply out of order

---

ratis-common/src/main/java/org/apache/ratis/protocol/RoutingTable.java
ratis-common/src/test/java/org/apache/ratis/BaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreStreamingBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/protocol/TestRoutingTable.java

See https://issues.apache.org/jira/browse/RATIS-1280

RATIS-1280. Validate RoutingTable before building it.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

See https://issues.apache.org/jira/browse/RATIS-1282

RATIS-1282. Refactor the code for preVote and vote in LeaderElection.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/VoteContext.java

See https://issues.apache.org/jira/browse/RATIS-1283

RATIS-1283. Refactor the code for preVote and vote in RaftServerImpl.

---

.github/workflows/pr.yml

add summary of failures to CI checks 
TBD
N/A

RATIS-1288. Add summary of failures to CI checks 

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-proto/src/main/proto/Raft.proto

See https://issues.apache.org/jira/browse/RATIS-1287

RATIS-1287. Incompatible proto changes due to RATIS-1158.

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

Use a config to enable/disable pre vote
https://issues.apache.org/jira/browse/RATIS-1295
no need to add new ut

RATIS-1295. Use a config to enable/disable pre vote

---

content/downloads.md
content/post/0.3.0.md
content/post/0.4.0.md
content/post/1.0.0.md
layouts/_default/list.html
layouts/_default/single.html
layouts/custompage/downloads.html
layouts/index.html
layouts/partials/header.html
layouts/partials/middle.html

RATIS-1285. Fix download link point to mirror links instead of download area directly

---

downloads.html

RATIS-1299. Fix version 0.4.0 can not download

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java

Fix NPE from SegmentedRaftLogCache#getOpenSegmentSizeInBytes
https://issues.apache.org/jira/browse/RATIS-1300
no need new ut

RATIS-1300. Fix NPE from SegmentedRaftLogCache#getOpenSegmentSizeInBytes

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java

https://issues.apache.org/jira/browse/RATIS-1309

RATIS-1309. Clarify ApplyTransaction Javadoc

---

BUILDING.md
DISCLAIMER
README.md

See https://issues.apache.org/jira/browse/RATIS-1317

RATIS-1317. Remove DISCLAIMER and update BUILDING.md & README.md.

---

dev-support/vagrant/README.md
dev-support/vagrant/Vagrantfile
dev-support/vagrant/bin/start_ratis_load_gen.sh
dev-support/vagrant/bin/start_ratis_server.sh
dev-support/vagrant/screenrcs/namazu_hdd_screenrc
dev-support/vagrant/screenrcs/ratis_ratis-hdd-slowdown_screenrc
dev-support/vagrant/screenrcs/ratis_ratis-server_screenrc

Fix vagrant for TLP
https://issues.apache.org/jira/browse/RATIS-1319
Review

RATIS-1319. Fix vagrant for TLP

---

ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamPacketHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java

Avoid parse proto for each packet
https://issues.apache.org/jira/browse/RATIS-1328
no need new ut

RATIS-1328. Avoid parse proto for each packet

---

pom.xml

add config build-helper-maven-plugin to auto mark source
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-793

RATIS-793. idea automatically mark generated source

---

layouts/partials/header.html

See https://issues.apache.org/jira/browse/RATIS-1347

RATIS-1347. Add ApacheCon Event Banner to website.

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

Revert "Ratis 1363 Intermittent failure in TestInstallSnapshotNotificationWithGrpc"

---

pom.xml

See https://issues.apache.org/jira/browse/RATIS-1357

RATIS-1357. Bump apache parent version to 23 in pom.xml.

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/LoadGen.java

Support multi-client in FileStore
https://issues.apache.org/jira/browse/RATIS-1372
test it manually

RATIS-1372. Support multi-client in FileStore

---

pom.xml

JIRA: https://issues.apache.org/jira/browse/RATIS-1387
Use fix version from ratis-thirdparty
Full build

RATIS-1387. bump to fix 0.7.0 thirdparty

---

ratis-common/src/main/java/org/apache/ratis/util/TaskQueue.java

See https://issues.apache.org/jira/browse/RATIS-1388

RATIS-1388 Add an isEmpty method to TaskQueue.

---

ratis-metrics/src/main/java/org/apache/ratis/metrics/MetricRegistriesLoader.java

Fix typo in MetricRegistriesLoader
https://issues.apache.org/jira/browse/RATIS-1389

RATIS-1389 Fix a typo in MetricRegistriesLoader

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

since we have [RATIS-1399](https://github.com/apache/ratis/pull/496), each `notify` of all the log senders will be executed in parallel ， default using ForkJoinPool ，which has a fixed num of threads in thread pool (default the same as the num of cpu core)
in GrpcLogAppender.java,  `synchronized` is used for two purposes:
1 protect `wait()`
2 protect variables like  `pendingRequests`, `pending` , etc.
this patch add a separate RWLock for the second case ， and keep `synchronized` only for wait and notify, thus any slow IO option will not block notify.
https://issues.apache.org/jira/browse/RATIS-1400
unit test

RATIS-1400. add a separate RWlock for GrpcLogAppender

---

downloads.html

Changes in the generated Ratis website for RATIS-1394 and RATIS-1395.
https://issues.apache.org/jira/browse/RATIS-1394
https://issues.apache.org/jira/browse/RATIS-1395
* `open downloads.html`
* verify changes from those two issues are applied

Update downloads.html for RATIS-1394 and RATIS-1395

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

See https://issues.apache.org/jira/browse/RATIS-1396

RATIS-1396. Reduce lock contention in RaftServerImpl::replyPendingRequest.

---

.asf.yaml

See https://issues.apache.org/jira/browse/RATIS-1404

RATIS-1404. Add "publish" section to .asf.yaml

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java

See https://issues.apache.org/jira/browse/RATIS-1406

RATIS-1406. Add an optional API to StateMachine.DataStream for providing an Executor.

---

ratis-common/src/main/java/org/apache/ratis/util/DataBlockingQueue.java
ratis-common/src/main/java/org/apache/ratis/util/DataQueue.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-test/src/test/java/org/apache/ratis/util/TestDataBlockingQueue.java
ratis-test/src/test/java/org/apache/ratis/util/TestDataQueue.java

https://issues.apache.org/jira/browse/RATIS-1407

RATIS-1407. Integer overflow when set raft.server.log.queue.limit" to 4GB by Ozone

---

content/community.md

See https://issues.apache.org/jira/browse/RATIS-1397

RATIS-1397. No link to issue tracker.

---

downloads.html

Merge asf-site for #509.
See also https://issues.apache.org/jira/browse/RATIS-1398

RATIS-1398. Wrong link for KEYS file.

---

index.html

This is a followup of #513.  Just found that index.html also need to be merged.

Amendment to RATIS-1397: merge index.html

---

build.sh
layouts/custompage/downloads.html

See https://issues.apache.org/jira/browse/RATIS-1413

RATIS-1413. Download page must not use dist.apache.org

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

https://issues.apache.org/jira/browse/RATIS-1420

RATIS-1420. Improve the appendEntity with inconsistency entities case

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java

See: https://issues.apache.org/jira/browse/RATIS-1421

RATIS-1421. [Streaming]make client NioEventLoopGroup size configurable.

---

pom.xml
ratis-examples/pom.xml
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-test/pom.xml
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1423

RATIS-1423. Remove commons.lang3 dependency from ratis-examples and ratis-test.

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/SetPriorityCommand.java

Add a setPriority sub command to set priority of the specific peer.
https://issues.apache.org/jira/browse/RATIS-1429
I did the following test within three alluxio ratis based masters.
```
[~/local/myproject/ratis] [setPriority *] -> %  mvn clean install  assembly:single -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true  -Dfindbugs.skip=true -Denforcer.skip=true -Dgpg.skip=true   -Djsse.enableSNIExtension=false  -Prelease -Papache-release
[~/local/myproject/ratis] [setPriority *]-> % cd ratis-assembly/target
[~/local/myproject/ratis/ratis-assembly/target] [setPriority *] -> % tar -xzf apache-ratis-2.3.0-SNAPSHOT-ratis-shell.tar.gz
[~/local/myproject/ratis/ratis-assembly/target] [setPriority *] -> % cd apache-ratis-2.3.0-SNAPSHOT …
```

RATIS-1429. Add ratis-shell setPriority command

---

ratis-common/src/main/java/org/apache/ratis/util/DataBlockingQueue.java
ratis-common/src/main/java/org/apache/ratis/util/DataQueue.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java
ratis-test/src/test/java/org/apache/ratis/util/TestDataQueue.java

See https://issues.apache.org/jira/browse/RATIS-1434

RATIS-1434. Add iterator() and remove(..) methods to DataQueue and DataBlockingQueue

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/LeaderElectionMetrics.java

Update metric of leaderElectionTimeout when transferLeader.
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1435

Ratis-1435. Update metric of leaderElectionTimeout

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/util/ProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java

See https://issues.apache.org/jira/browse/RATIS-1450

RATIS-1450. Remove ProtoUtils.addCommitInfos(..).

---

ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReplyHeader.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java

See https://issues.apache.org/jira/browse/RATIS-1449

RATIS-1449. Move netty related code out from ratis-common.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/GroupManagementImpl.java

See https://issues.apache.org/jira/browse/RATIS-1451

RATIS-1451. GroupManagementImpl should use sendRequestWithRetry.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java

see: https://issues.apache.org/jira/browse/RATIS-1452

RATIS-1452. Fix log output in sendRequest.

---

ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamReplyByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReplyHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

See https://issues.apache.org/jira/browse/RATIS-1448

RATIS-1448. Include commit infos in DataStreamReply.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java

See https://issues.apache.org/jira/browse/RATIS-1100

RATIS-1100. Make raft log gap error easier to troubleshoot.

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Server.java

https://issues.apache.org/jira/browse/RATIS-1410

RATIS-1410. Wrong comment in ratis filestore example

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java

OrderedStreamAsync error handler
https://issues.apache.org/jira/browse/RATIS-1464

RATIS-1464. OrderedStreamAsync error handler

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

DataStreamManagement  startTransaction error handler, doing so will fetch exceptions that may occur in async
https://issues.apache.org/jira/browse/RATIS-1457

RATIS-1457. DataStreamManagement startTransaction error handler

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server-api/src/main/java/org/apache/ratis/server/metrics/RaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetricsBase.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

https://issues.apache.org/jira/browse/RATIS-1408

RATIS-1408. Add metrics of statemachine read/write timeout count.

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java

Add request timeout to ratis Streaming
https://issues.apache.org/jira/browse/RATIS-1438

RATIS-1438. Add request timeout to ratis Streaming

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientRpc.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcAdminProtocolService.java
ratis-proto/src/main/proto/Grpc.proto

subtask of Support snapshot command: Add take snapshot grpc related request and proto
https://issues.apache.org/jira/browse/RATIS-1484
No need

RATIS-1484. Add take snapshot grpc related request and proto

---

ratis-examples/README.md

Improve guideline in ratis-example/README.md when users run FileStore example.
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1488
Don't need.

RATIS-1488. Improve README for FileStore example

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SnapshotManagementTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestSnapshotManagementWithGrpc.java

subtask of Support snapshot command: Add take snapshot raftClient and grpc-test related code
https://issues.apache.org/jira/browse/RATIS-1489
UT

RATIS-1489. Add take snapshot raftClient and grpc-test related code

---

ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/client/CombinedClientProtocolClientSideTranslatorPB.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/client/CombinedClientProtocolServerSideTranslatorPB.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/client/HadoopClientRpc.java
ratis-hadoop/src/main/proto/HadoopCompatability.proto
ratis-hadoop/src/test/java/org/apache/ratis/hadooprpc/TestSnapshotManagementWithHadoopRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java
ratis-proto/src/main/proto/Hadoop.proto
ratis-proto/src/main/proto/Netty.proto
ratis-test/src/test/java/org/apache/ratis/netty/TestSnapshotManagementWithNetty.java

subtask of Support snapshot command:  Add take snapshot hadoop and netty related request and proto
https://issues.apache.org/jira/browse/RATIS-1486
No need

RATIS-1486. Add take snapshot hadoop and netty related request and proto

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RoleInfo.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

subtask to support no leader mode in ratis: Implement pause election in sever
https://issues.apache.org/jira/browse/RATIS-1487
UT

RATIS-1487. Implement pause election in server

---

pom.xml
ratis-proto/pom.xml
ratis-resource-bundle/src/main/resources/supplemental-models.xml

See https://issues.apache.org/jira/browse/RATIS-1492

RATIS-1492. Use tomcat annotations-api.

---

pom.xml
ratis-common/pom.xml
ratis-examples/pom.xml
ratis-grpc/pom.xml
ratis-hadoop/pom.xml
ratis-logservice/pom.xml
ratis-netty/pom.xml
ratis-server-api/pom.xml
ratis-server/pom.xml

See https://issues.apache.org/jira/browse/RATIS-1494

RATIS-1494. Change spotbugs-annotations to provided scope.

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/SnapshotCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/snapshot/TakeSnapshotCommand.java

Add a sub command to take snapshot of the ratis server
https://issues.apache.org/jira/browse/RATIS-1437
UT

RATIS-1412. Add ratis-shell snapshot command

---

ratis-common/src/main/java/org/apache/ratis/util/AwaitForSignal.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java

See https://issues.apache.org/jira/browse/RATIS-1500

RATIS-1500. Fix LogAppender NN_NAKED_NOTIFY.

---

pom.xml
ratis-hadoop/pom.xml
ratis-replicated-map/pom.xml

See https://issues.apache.org/jira/browse/RATIS-1508

RATIS-1508. Clean up vulnerabilities from dependencies.

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

NettyServerStreamRpc use EpollEventLoopGroup
https://issues.apache.org/jira/browse/RATIS-1521

RATIS-1521. NettyServerStreamRpc use EpollEventLoopGroup

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-common/src/main/java/org/apache/ratis/io/WriteOption.java

Streaming tests may fail with TimeoutIOException: Timeout 3000ms
https://issues.apache.org/jira/browse/RATIS-1513

RATIS-1513. Streaming tests may fail with TimeoutIOException: Timeout 3000ms

---

ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/DivisionInfo.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Support listener in ratis
https://issues.apache.org/jira/browse/RATIS-1301
UT

RATIS-1301. Support listener in ratis

---

ratis-common/src/main/java/org/apache/ratis/conf/RaftProperties.java

See https://issues.apache.org/jira/browse/RATIS-1532

RATIS-1532. Fix RaftProperties security warning.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Fix typo
[RATIS-1533](https://issues.apache.org/jira/browse/RATIS-1533)

RATIS-1533 Fix typo in RaftClientImpl and RaftServerImpl

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractParentCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/ElectionCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/StepDownCommand.java

Add a sub command to step down the leader.
https://issues.apache.org/jira/browse/RATIS-1535
UT

RATIS-1535. Add a command to step down the leader

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

Handle when there is an exception in NettyServerStreamRpc# getDataStreamOutput
https://issues.apache.org/jira/browse/RATIS-1529

RATIS-1529. Handle when there is an exception in NettyServerStreamRpc# getDataStreamOutput

---

ratis-netty/src/main/java/org/apache/ratis/netty/metrics/NettyServerStreamRpcMetrics.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

Add metric to streaming
https://issues.apache.org/jira/browse/RATIS-1444

RATIS-1444. Add metric to streaming

---

ratis-common/src/main/java/org/apache/ratis/security/TlsConf.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcTlsConfig.java

See https://issues.apache.org/jira/browse/RATIS-1539

RATIS-1539. Refactor GrpcTlsConfig.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java

See https://issues.apache.org/jira/browse/RATIS-1552

RATIS-1552. Fix StateMachineUpdater NN_NAKED_NOTIFY.

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-test/src/test/java/org/apache/ratis/server/impl/TestRaftConfiguration.java

Sub task to support listener:  Suppport listener in setConfiguration
https://issues.apache.org/jira/browse/RATIS-1551
UT

RATIS-1551. Suppport listener in setConfiguration

---

ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedObject.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-test/src/test/java/org/apache/ratis/util/TestReferenceCountedObject.java

See https://issues.apache.org/jira/browse/RATIS-1556

RATIS-1556. Support reference-counted buffer in StateMachine.DataChannel

---

ratis-common/src/main/java/org/apache/ratis/util/FileUtils.java
ratis-common/src/main/java/org/apache/ratis/util/StringUtils.java
ratis-common/src/test/java/org/apache/ratis/util/FileUtilsTest.java
ratis-common/src/test/java/org/apache/ratis/util/TestFileUtils.java
ratis-common/src/test/resources/log4j.properties
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java

See https://issues.apache.org/jira/browse/RATIS-1554

RATIS-1554. Fix SnapshotManager RV_RETURN_VALUE_IGNORED_BAD_PRACTICE.

---

dev-support/checkstyle.xml
pom.xml
ratis-metrics/src/test/resources/hadoop-metrics2.properties

See https://issues.apache.org/jira/browse/RATIS-1559

RATIS-1559. Update checkstyle to avoid the vulnerability in 8.18.

---

ratis-common/src/main/java/org/apache/ratis/util/ConcurrentUtils.java
ratis-common/src/main/java/org/apache/ratis/util/PeerProxyMap.java
ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1567

RATIS-1567. NettyServerStreamRpc may throw NPE.

---

ratis-docs/content/cli.md

see https://issues.apache.org/jira/browse/RATIS-1461

RATIS-1461. Add ratis-shell documents

---

ratis-server-api/src/main/java/org/apache/ratis/server/DivisionInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

see [jira1570](https://issues.apache.org/jira/browse/RATIS-1570)

RATIS-1570. Add getLeaderId method to DivisionInfo

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/AddCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/RemoveCommand.java
ratis-test/src/test/java/org/apache/ratis/grpc/cli/TestElectionCommandIntegrationWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/cli/TestPeerCommandIntegrationWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/AbstractCommandIntegrationTestWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/ElectionCommandIntegrationTest.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/PeerCommandIntegrationTest.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/SnapshotCommandIntegrationTest.java

see https://issues.apache.org/jira/browse/RATIS-1580

RATIS-1580. Add ratis-shell peer and election command unit test

---

layouts/_default/list.html
layouts/index.html
layouts/partials/header.html

See https://issues.apache.org/jira/browse/RATIS-1568

RATIS-1568. Add a link to the new ASF privacy policy.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1584

RATIS-1584. Check if the group is empty in RaftClientImpl.

---

ratis-client/src/main/java/org/apache/ratis/client/api/AsyncApi.java
ratis-client/src/main/java/org/apache/ratis/client/api/BlockingApi.java
ratis-common/src/main/java/org/apache/ratis/util/IOUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientRpc.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/WatchRequests.java
ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java

See https://issues.apache.org/jira/browse/RATIS-1590

RATIS-1590. Include the new log index in Watch reply.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java

server reply should return success for SNAPSHOT_INSTALLED in InstallSnapshotReplyProto
make server reply success for SNAPSHOT_INSTALLED in InstallSnapshotReplyProto
https://issues.apache.org/jira/browse/RATIS-1604
/

RATIS-1604. server reply should return success for SNAPSHOT_INSTALLED in InstallSnapshotReplyProto

---

ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java

https://issues.apache.org/jira/browse/RATIS-1608

RATIS-1608. Improve RaftStorageDirectoryImpl#tryLock performance on ios system

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java

https://issues.apache.org/jira/browse/RATIS-1607

RATIS-1607. Fix NPE in OrderedAsync#sendRequestWithRetry

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

see https://issues.apache.org/jira/browse/RATIS-1611

RATIS-1611. Add notify server step sown event to inform

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java

Fix Concurrent issue on LogSegmentList which could lead to IndexOutOfBoundsException.
The consecutive operations should be protected by the lock.
https://issues.apache.org/jira/browse/RATIS-1617
Simple UT. not included in PR

RATIS-1617. Concurrent issue on LogSegmentList

---

ratis-common/src/main/java/org/apache/ratis/util/ConcurrentUtils.java
ratis-common/src/main/java/org/apache/ratis/util/MemoizedSupplier.java
ratis-server-api/src/main/java/org/apache/ratis/server/storage/RaftStorage.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/StorageImplUtils.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

See https://issues.apache.org/jira/browse/RATIS-1609

RATIS-1609. RaftStorageImpl should not lock the directory in the constructor.

---

ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/server/ServerBuilderTest.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/PeerCommandIntegrationTest.java

Validate server id in raft group if the group is not null
[RATIS-1619](https://issues.apache.org/jira/browse/RATIS-1619)
Add new tests.

RATIS-1619. Validate server id in raft group if the group is not empty

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftGroup.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeer.java
ratis-common/src/main/java/org/apache/ratis/util/ProtoUtils.java
ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java

Support starting a server as a Listener.
https://issues.apache.org/jira/browse/RATIS-1612

RATIS-1612. Support starting a server as a Listener.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java

https://issues.apache.org/jira/browse/RATIS-1605

RATIS-1605. Do not start RaftServer in MiniRaftCluster#addNewPeers when startNewPeer is false

---

ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/SetConfigurationRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/SetConfigurationCasModeException.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/SetConfigurationException.java
ratis-common/src/main/java/org/apache/ratis/util/CollectionUtils.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java

see https://issues.apache.org/jira/browse/RATIS-1593

RATIS-1593. Support CAS mode to setConfiguration

---

ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java

https://issues.apache.org/jira/browse/RATIS-1629
This testKillLeaderDuringReconf fail randomly at the check 
RaftReconfigurationBaseTest.runTestKillLeaderDuringReconf -> RaftServerTestUtil#waitAndCheckNewConf#Assert.assertFalse(conf.containsInConf(server.getId()));
The test tries to move a cluster from
[s0(L), s1, s2]  to 
[s0(killed), s1(removed), s2, s3(new)]. 
There is chance that s3 cannot join the group because of timing. s3 is rejected and shutdown itself when it receives an shutdown command from the new Leader which isn't in the configuration transitional state. 
If s3 cannot join the group, the "Assert.assertFalse(conf.containsInConf(server.getId()))" will fail because the set configuration request will mot get majority responses.

RATIS-1629. Fix flaky TestRaftReconfigurationWithSimulatedRpc#testKillLeaderDuringReconf

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java

See https://issues.apache.org/jira/browse/RATIS-1637

RATIS-1637. Improve the log message with fallback value in conf.

---

ratis-docs/src/site/markdown/index.md
ratis-docs/src/site/markdown/start/index.md

Added the get started document.
https://issues.apache.org/jira/browse/RATIS-1639
Document only commit, no tests available.

RATIS-1639. Added getting started document

---

ratis-docs/src/site/markdown/start/index.md
ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/ArithmeticStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/common/Constants.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/CounterCommand.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/client/CounterClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterServer.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterStateMachine.java
ratis-examples/src/test/java/org/apache/ratis/examples/counter/TestCounter.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java

See https://issues.apache.org/jira/browse/RATIS-1641

RATIS-1641. Cleanup the Counter example and revise the "Getting Started" doc.

---

ratis-common/src/main/java/org/apache/ratis/rpc/CallId.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ReadRequests.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java

See https://issues.apache.org/jira/browse/RATIS-1663

RATIS-1663. Record call id for board casting a heartbeat.

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/BufferedWriteChannel.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogOutputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestBufferedWriteChannel.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestRaftLogReadWrite.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

https://issues.apache.org/jira/browse/RATIS-1644

RATIS-1644. Provide a safe async flush.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java

See https://issues.apache.org/jira/browse/RATIS-1676

RATIS-1676. SnapshotManager should use ServerStringUtils.toInstallSnapshotRequestString(..).

---

ratis-common/src/main/java/org/apache/ratis/util/JavaUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcFactory.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestGrpcFactory.java

See https://issues.apache.org/jira/browse/RATIS-1586

RATIS-1586. Set useCacheForAllThreads default to false.

---

.github/workflows/post-commit.yml

see https://issues.apache.org/jira/browse/RATIS-1683

RATIS-1683. Upgrade ubuntu version from 18.04 to 20.04

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/GrpcServerMetrics.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/server/TestGrpcServerMetrics.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/MetricRegistryInfo.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/MetricsReporting.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/RatisMetricRegistry.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/RatisMetricRegistryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetricsBase.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestLogAppenderMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/metrics/ServerMetricsTestUtils.java
ratis-server/src/test/java/org/apache/ratis/server/metrics/TestLeaderElectionMetrics.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerSlownessDetection.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

See https://issues.apache.org/jira/browse/RATIS-1689

RATIS-1689. Remove the use of the thirdparty Gauge.

---

ratis-common/src/main/java/org/apache/ratis/protocol/GroupManagementRequest.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1694

RATIS-1694. Fix the compatibility issue of RATIS-1677.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/VoteContext.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

see https://issues.apache.org/jira/browse/RATIS-1702

RATIS-1702. Make listener reject leader election

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/snapshot/TakeSnapshotCommand.java

Trivial change.
https://issues.apache.org/jira/browse/RATIS-1713

RATIS-1713. Fix TakeSnapshotCommand's usage info

---

NOTICE

See https://issues.apache.org/jira/browse/RATIS-1720

RATIS-1720. Add back Dropwizard Metrics notice to branch-2.

---

ratis-client/src/main/java/org/apache/ratis/client/api/AsyncApi.java
ratis-client/src/main/java/org/apache/ratis/client/api/BlockingApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AsyncImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestWithLongTimeoutTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestReadOnlyRequestWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestReadOnlyRequestWithLongTimeoutWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1715

RATIS-1715. Support linearizable read in AsyncApi.

---

ratis-client/src/main/java/org/apache/ratis/client/api/AsyncApi.java
ratis-client/src/main/java/org/apache/ratis/client/api/BlockingApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AsyncImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/UnorderedAsync.java
ratis-common/src/main/java/org/apache/ratis/protocol/Message.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileInfo.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/TestFileStoreWithGrpc.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/TestFileStoreWithNetty.java
ratis-proto/src/main/proto/Examples.proto

See https://issues.apache.org/jira/browse/RATIS-1714

RATIS-1714. Support unordered async read.

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestFilePositionCount.java
ratis-common/src/main/java/org/apache/ratis/io/StandardWriteOption.java
ratis-common/src/main/java/org/apache/ratis/io/WriteOption.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamRequestByteBuf.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamStarTopologyWithGrpcCluster.java

See https://issues.apache.org/jira/browse/RATIS-1157

RATIS-1157. Buffer packets when the size of packets are too small.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java

See https://issues.apache.org/jira/browse/RATIS-1730

RATIS-1730. Optimize RaftLog cache eviction time.

---

pom.xml

see https://issues.apache.org/jira/browse/RATIS-1739

RATIS-1739. Upgrade Ratis Thirdparty to 1.0.3

---

ratis-metrics-api/src/main/java/org/apache/ratis/metrics/MetricRegistries.java
ratis-metrics-default/src/main/java/org/apache/ratis/metrics/impl/MetricRegistriesImpl.java
ratis-metrics-default/src/test/java/org/apache/ratis/metrics/TestMetricRegistriesLoader.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3MetricRegistriesImpl.java
ratis-metrics-dropwizard3/src/test/java/org/apache/ratis/metrics/dropwizard3/TestLoadDm3MetricRegistries.java

removeReporterRegistration method is provided
https://issues.apache.org/jira/browse/RATIS-1741
Patch is tested adding Unit test with register and remove registration of reporter

RATIS-1741 Add a removeReporterRegistration method

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

See https://issues.apache.org/jira/browse/RATIS-1743
This is the third attempt.

RATIS-1743. Memory leak in SegmentedRaftLogWorker due to metrics.

---

ratis-common/pom.xml
ratis-common/src/test/java/org/apache/ratis/util/Slf4jUtils.java
ratis-server/pom.xml
ratis-test/pom.xml
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

See https://issues.apache.org/jira/browse/RATIS-1742

RATIS-1742. Remove slf4j-log4j12 test dependency from ratis-common and ratis-server.

---

ratis-common/src/main/java/org/apache/ratis/util/AwaitForSignal.java

See https://issues.apache.org/jira/browse/RATIS-1745

RATIS-1745. Improve performance of AwaitForSignal by reducing amount of exceptions created.

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamFactory.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1753

RATIS-1753. NettyServerStreamRpc should create client with TlsConf.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java

See https://issues.apache.org/jira/browse/RATIS-1751

RATIS-1751. Race condition between LeaderStateImpl & ServerState.

---

ratis-client/src/main/java/org/apache/ratis/client/api/AdminApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AdminImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/StepDownCommand.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/ElectionCommandIntegrationTest.java

see https://issues.apache.org/jira/browse/RATIS-1768

RATIS-1768. Fix stepDown command don't work issue

---

ratis-docs/src/site/markdown/metrics.md
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java

Add descriptions to metrics entries
https://issues.apache.org/jira/browse/RATIS-1766

RATIS-1766. Add descriptions to metrics entries

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ReadIndexHeartbeats.java

see https://issues.apache.org/jira/browse/RATIS-1773

RATIS-1773. Fix readIndexHeartbeat using incorrct index handle onAppendEntriesReply method

---

pom.xml
ratis-common/pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-resource-bundle/src/main/resources/supplemental-models.xml
ratis-server/pom.xml
ratis-test/pom.xml

Cherry-pick #814 to `branch-2`.
https://issues.apache.org/jira/browse/RATIS-1776
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/3979247118

RATIS-1776. Switch to slf4j-reload4j

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ReadIndexHeartbeats.java

see https://issues.apache.org/jira/browse/RATIS-1778

RATIS-1778. Fix NPE in readIndexHeartbeats

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ReadIndexHeartbeats.java

revert https://github.com/apache/ratis/pull/817

Revert "RATIS-1778. Fix NPE in readIndexHeartbeats (#817)"

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

implement the basic transfer leadership operation, which is described in section 3.10 "leadership transfer extension" of [Diego Ongaro's PhD dissertation](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf).
Please see Jira for details.
https://issues.apache.org/jira/browse/RATIS-1762
LeaderElectionTests

RATIS-1762. Support transfer leadership between nodes with same priority

---

ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java

https://issues.apache.org/jira/browse/RATIS-1779

RATIS-1779. Refactor: Reduce nesting in TransferLeadership

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

See https://issues.apache.org/jira/browse/RATIS-1543

RATIS-1543. Log from GrpcLogAppender is confusing.

---

ratis-common/src/main/java/org/apache/ratis/util/JvmPauseMonitor.java
ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-test/src/test/java/org/apache/ratis/util/TestTimeDuration.java

See https://issues.apache.org/jira/browse/RATIS-1788

RATIS-1788. Improve the JvmPauseMonitor log messages.

---

ratis-server/src/test/java/org/apache/ratis/server/impl/PreAppendLeaderStepDownTest.java

Fix flaky test PreAppendLeaderStepDownTest#testLeaderStepDown
https://issues.apache.org/jira/browse/RATIS-1794
Repeat 100x in CI
Before: https://github.com/kaijchen/ratis/actions/runs/4275670166
After: https://github.com/kaijchen/ratis/actions/runs/4275781246

RATIS-1794. Intermittent failure in PreAppendLeaderStepDownTest#testLeaderStepDown

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/util/ResponseNotifyClientInterceptor.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/util/StreamObserverWithTimeout.java
ratis-proto/src/main/proto/Test.proto
ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcTestClient.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcTestServer.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/TestStreamObserverWithTimeout.java

See https://issues.apache.org/jira/browse/RATIS-1807

RATIS-1807. Support timeout in gRPC.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

Currently, if vote is timed out, the candidate will rerun another vote with increased term.
If PreVote is enabled, we should rerun another PreVote before increasing the term again.
https://issues.apache.org/jira/browse/RATIS-1808
Existing test passed: https://github.com/kaijchen/ratis/actions/runs/4351879050
TODO: cover the changed scenario.

RATIS-1808. Rerun PreVote when Vote is timed out

---

.gitignore
.mvn/wrapper/maven-wrapper.properties
BUILDING.md
mvnw
mvnw.cmd
ratis-assembly/src/main/assembly/src.xml

Split from #854.
RATIS-1795
Manually tested.

RATIS-1795. Add and distribute a Maven Wrapper

---

pom.xml
ratis-assembly/pom.xml
ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-common/src/main/java/org/apache/ratis/protocol/RoutingTable.java
ratis-common/src/main/java/org/apache/ratis/retry/RetryPolicies.java
ratis-common/src/main/java/org/apache/ratis/util/ExitUtils.java
ratis-examples/pom.xml
ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/expression/Expression.java
ratis-test/pom.xml

See https://issues.apache.org/jira/browse/RATIS-1820

RATIS-1820. Update apache parent pom version and other versions.

---

ratis-common/src/main/java/org/apache/ratis/util/StringUtils.java
ratis-common/src/main/java/org/apache/ratis/util/function/StringSupplier.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/util/StreamObserverWithTimeout.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcTestClient.java

See https://issues.apache.org/jira/browse/RATIS-1823

RATIS-1823. Improve error log in StreamObserverWithTimeout.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/GroupInfoReply.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractRatisCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/TransferCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/AddCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/RemoveCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/SetPriorityCommand.java

Fix the listener will change to follower when using ratis shell.
[RATIS-1826](https://issues.apache.org/jira/browse/RATIS-1826)

RATIS-1826: Listener will change to follower when using ratis shell

---

ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java

See https://issues.apache.org/jira/browse/RATIS-1838
Existing unit tests and manual tests

RATIS-1838. Compare commit index with last included index when installSnapshot

---

ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java

Fix flaky test TestRaftStateMachineExceptionWithSimulatedRpc
https://issues.apache.org/jira/browse/RATIS-1833
400x TestRaftStateMachineExceptionWithSimulatedRpc in CI:
Before: https://github.com/kaijchen/ratis/actions/runs/4697623656
After: https://github.com/kaijchen/ratis/actions/runs/4697624662

RATIS-1833. Intermittent failure in TestRaftStateMachineExceptionWithSimulatedRpc

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/server/MetricServerCall.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/server/MetricServerCallListener.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogReader.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java

Fixed some trivial SonarLint complains about unused params, try-with-clauses, function signature not complying with parent's.
https://issues.apache.org/jira/browse/RATIS-1852

RATIS-1852. Fix trivial SonarLint complains

---

ratis-common/src/main/java/org/apache/ratis/util/JvmPauseMonitor.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

see [jira](https://issues.apache.org/jira/browse/RATIS-1867)

RATIS-1867 To uniformly manage the timeout parameters for detecting gc

---

ratis-server/src/main/java/org/apache/ratis/server/storage/StorageImplUtils.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestStorageImplUtils.java

See https://issues.apache.org/jira/browse/RATIS-1871

RATIS-1871. Auto format RaftStorage when there is only one directory configured.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

Exception handling during truncate segment log, For a detailed description see jira
https://issues.apache.org/jira/browse/RATIS-1887

RATIS-1887. Gap between segement log

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

Optimize Stream client&server side channel pipeline Create
Currently every time you create a channel pipeline you create some temporary objects, this pr creates them in advance and reuses them.
https://issues.apache.org/jira/browse/RATIS-1880
Existing test

RATIS-1880. Optimize Stream client&server side channel pipeline Create

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java

RATIS-761. Handle writeStateMachineData failure in leader.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/GroupInfoRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/GroupListRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/GroupManagementRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/LeaderElectionManagementRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeer.java
ratis-common/src/main/java/org/apache/ratis/protocol/SetConfigurationRequest.java

RATIS-1903. Fix parameter number warning in RaftClientRequest.

---

NOTICE
ratis-assembly/src/main/resources/NOTICE

see https://issues.apache.org/jira/browse/RATIS-1906

RATIS-1906. Bump copyright year to 2023

---

ratis-client/src/main/java/org/apache/ratis/client/api/AdminApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/conf/ReconfigurationBase.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketImpl.java
ratis-common/src/main/java/org/apache/ratis/util/JvmPauseMonitor.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/server/MetricServerCallListener.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/server/MetricServerInterceptor.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotManagementRequestHandler.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/CacheInvalidationPolicy.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/AbstractShell.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractParentCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/StepDownCommand.java

see https://issues.apache.org/jira/browse/RATIS-1905

RATIS-1905. Fix some sonar lint complains

---

ratis-common/src/main/java/org/apache/ratis/protocol/ClientId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftGroupId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeerId.java
ratis-common/src/main/java/org/apache/ratis/thirdparty/com/google/protobuf/ByteStringUtils.java
ratis-test/src/test/java/org/apache/ratis/protocol/TestRaftId.java

RATIS-1910. Deduplicate RaftGroupId and ClientId.

---

ratis-test/pom.xml

RATIS-1914. Bouncy Castle For Java LDAP injection vulnerability.

---

ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

See https://issues.apache.org/jira/browse/RATIS-1908

RATIS-1908. Keep configurations doc updated

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

RATIS-1920. NPE in AppendLogResponseHandler.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-client/src/main/java/org/apache/ratis/client/impl/UnorderedAsync.java
ratis-common/src/main/java/org/apache/ratis/util/ProtoUtils.java

RATIS-1916. OrderAsync does not call handReply.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

See https://issues.apache.org/jira/browse/RATIS-1804

RATIS-1804. Change the default number of outstanding append entries.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RoleInfo.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDaemon.java

RATIS-1928. Join the LogAppenders when closing the server.

---

pom.xml
ratis-assembly/pom.xml
ratis-client/pom.xml
ratis-common/pom.xml
ratis-docs/pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-grpc/pom.xml
ratis-metrics-api/pom.xml
ratis-metrics-default/pom.xml
ratis-metrics-dropwizard3/pom.xml
ratis-netty/pom.xml
ratis-proto/pom.xml
ratis-replicated-map/pom.xml
ratis-resource-bundle/pom.xml
ratis-server-api/pom.xml
ratis-server/pom.xml
ratis-shell/pom.xml
ratis-test/pom.xml
ratis-tools/pom.xml

https://issues.apache.org/jira/browse/RATIS-1937

RATIS-1937. Bump version to 3.1.0-SNAPSHOT after release

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/RaftConfigKeys.java

Make the raft request configurable in Streaming
https://issues.apache.org/jira/browse/RATIS-1936

RATIS-1936. Make the raft request configurable in Streaming

---

README.md

see https://issues.apache.org/jira/browse/RATIS-1940

RATIS-1940. Introduce Pluggable Metrics to readme 

---

index.html

https://issues.apache.org/jira/browse/RATIS-1940.
See the result:

RATIS-1940. Add pluggable metrics description into project website

---

ratis-shell/pom.xml
ratis-shell/src/main/java/org/apache/ratis/shell/cli/Command.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/RatisShell.java
ratis-test/pom.xml
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/TestRatisShell.java

RATIS-1941. Do not print reflections log message in shell.

---

ratis-common/src/main/java/org/apache/ratis/conf/RaftProperties.java
ratis-common/src/main/java/org/apache/ratis/util/StringUtils.java
ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-common/src/main/java/org/apache/ratis/util/TraditionalBinaryPrefix.java
ratis-test/src/test/java/org/apache/ratis/conf/TestRaftProperties.java
ratis-test/src/test/java/org/apache/ratis/util/TestTraditionalBinaryPrefix.java

RATIS-599. Support underscores in numeric literals in RaftProperties.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

See https://issues.apache.org/jira/browse/RATIS-1943.
When leader is elected but not ready, we should pending the incoming read-index requests and reply later, instead of failing requests immediately.

RATIS-1943. Pending read requests instead of failing when leader not ready

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamOutput.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/io/StandardWriteOption.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-common/src/main/java/org/apache/ratis/util/CollectionUtils.java
ratis-common/src/main/java/org/apache/ratis/util/JavaUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

RATIS-1948. NettyClientStreamRpc.Connection.scheduleReconnect should check isClosed.

---

ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-test/src/test/java/org/apache/ratis/util/TestPreconditions.java

RATIS-1957. Preconditions incorrectly sets an exception message

---

ratis-server/src/main/java/org/apache/ratis/server/impl/CommitInfoCache.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ConfigurationManager.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java

RATIS-1967. Do not store CommitInfoProto in CommitInfoCache.

---

ratis-test/src/test/java/org/apache/ratis/grpc/TestRetryCacheWithGrpc.java

Wait for async request to remove previous replied client request from the RetryCache.
https://issues.apache.org/jira/browse/RATIS-1980
Passed 10x10:
https://github.com/adoroszlai/ratis/actions/runs/7239557058
CI:
https://github.com/adoroszlai/ratis/actions/runs/7239555524

RATIS-1980. Intermittent failure in TestRetryCacheWithGrpc#testInvalidateRepliedCalls

---

ratis-docs/src/site/markdown/membership-change.md
ratis-docs/src/site/site.xml

See https://issues.apache.org/jira/browse/RATIS-1965.

RATIS-1965. Add docs for configuration change

---

ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

Attempt to fix intermittent failure in `TestRaftStorage#testSnapshotCleanup`:
```
org.apache.ratis.server.storage.TestRaftStorage.testSnapshotCleanup  Time elapsed: 0.022 s  <<< FAILURE!
java.lang.AssertionError
...
at org.apache.ratis.server.storage.TestRaftStorage.testSnapshotCleanup(TestRaftStorage.java:256)
```
I'm guessing the problem is caused by duplicate random-generated term/index value, which can result in fewer than 7 expected files.
Also some additional assertions and cleanup.
https://issues.apache.org/jira/browse/RATIS-1986
Passed in 10x50 runs:
https://github.com/adoroszlai/ratis/actions/runs/7371067861

RATIS-1986. Intermittent failure in TestRaftStorage#testSnapshotCleanup

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientAsynchronousProtocol.java
ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedObject.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/TransactionContext.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/TransactionContextImpl.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java
ratis-tools/src/main/java/org/apache/ratis/tools/ParseRatisLog.java

RATIS-1983. Refactor client request processing to support reference count.

---

content/post/3.0.1.md

Update Ratis website with announcement for 3.0.1 bugfix release.
https://issues.apache.org/jira/browse/RATIS-1992
```
hugo serve
open http://localhost:1313
```

RATIS-1992. Update website with Ratis 3.0.1 release

---

ratis-common/src/main/java/org/apache/ratis/util/JmxRegister.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerJmxAdapter.java
ratis-test/src/test/java/org/apache/ratis/server/impl/TestRaftServerJmx.java

RATIS-1999. Move RaftServerJmxAdapter out from RaftServerImpl.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/UnorderedAsync.java
ratis-client/src/main/java/org/apache/ratis/client/retry/ClientRetryEvent.java
ratis-common/src/main/java/org/apache/ratis/util/PeerProxyMap.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-test/src/test/java/org/apache/ratis/RaftLogTruncateTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftLogTruncateWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/retry/TestExceptionDependentRetry.java
ratis-test/src/test/java/org/apache/ratis/retry/TestRetryPolicy.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java

RATIS-2012. Client should not retry after close.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java

See [RATIS-2017](https://issues.apache.org/jira/browse/RATIS-2017)
https://issues.apache.org/jira/browse/RATIS-2017)
CI.

RATIS-2017: checkAndEvictCache must be done in writeLock.

---

ratis-common/src/main/java/org/apache/ratis/util/JavaUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ReadIndexHeartbeats.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RetryCacheImpl.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2019)

RATIS-2019 Fixed abnormal exit of StateMachineUpdater

---

ratis-metrics-dropwizard3/pom.xml
ratis-metrics-dropwizard3/src/test/java/org/apache/ratis/metrics/dropwizard3/TestLoadDm3MetricRegistries.java
ratis-metrics-dropwizard3/src/test/java/org/apache/ratis/metrics/dropwizard3/TestRefCountingMap.java

Migrate ratis-metrics-dropwizard3 tests to Junit 5
RATIS-1975
Unit test

RATIS-1975. Migrate ratis-metrics-dropwizard3 tests to Junit 5.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java
ratis-server/src/main/java/org/apache/ratis/server/util/ServerStringUtils.java

RATIS-2024. Refactor appendEntries code.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RoleInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java

RATIS-2025. Move out assert and proto methods from RaftServerImpl.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestByteBuf.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

RATIS-2027. Ratis Streaming: Remote Stream copy data to heap.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java

RATIS-2038. IllegalStateException when ServerState is closed before start.

---

ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

Refactor RaftLog to supply log as ReferenceCountedObject
https://issues.apache.org/jira/browse/RATIS-2028
CI.

RATIS-2028. Refactor RaftLog to supply log as ReferenceCountedObject

---

ratis-server/src/main/java/org/apache/ratis/statemachine/impl/SimpleStateMachineStorage.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2048)

RATIS-2048 Fix SimpleStateMachineStorage potential NPE exception

---

ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/util/MemoizedCheckedSupplier.java
ratis-common/src/main/java/org/apache/ratis/util/MemoizedSupplier.java
ratis-examples/src/main/java/org/apache/ratis/examples/debug/server/Server.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-examples/src/main/java/org/apache/ratis/examples/membership/server/CServer.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2049)

RATIS-2049 Ensure atomic safety for volatile object

---

ratis-docs/src/site/markdown/configurations.md

see [jira](https://issues.apache.org/jira/browse/RATIS-2052)

RATIS-2052. Add docs for triggering snapshot when removing raftGroup parameter.

---

ratis-docs/src/site/markdown/concept/index.md
ratis-docs/src/site/markdown/snapshot.md

see [jira](https://issues.apache.org/jira/browse/RATIS-2067)

RATIS-2067 Enhance content for concept in ratis-docs

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

RATIS-2080. Reuse LeaderElection executor.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

See RATIS-2076
Passing all 100 runs: https://github.com/szetszwo/ratis/actions/runs/9038037405

RATIS-2076. Intermittent timeout in TestRaftWithNetty#testWithLoad.

---

pom.xml

Checkstyle is not checking test source directory. This ticket is to resolve this issue.
https://issues.apache.org/jira/browse/RATIS-2081
No need new tests.

RATIS-2081. Comment that we skip checkstyle on test directory on purpose

---

ratis-test/src/test/java/org/apache/ratis/RaftLogTruncateTests.java

RATIS-2098. RaftLogTruncateTests may fail.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/ZeroCopyMetrics.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcClientProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/util/ZeroCopyMessageMarshaller.java

See RATIS-2092
https://issues.apache.org/jira/browse/RATIS-2092
CI

RATIS-2092. Add metrics to expose number of zero-copy unclosed messages

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LogMetadataTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogMetadataTestsWithGrpc.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2097)

RATIS-2097 Add a conf to enable/disable Metadata entries

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java

RATIS-2136 Fixed the issue that RatisServer could not start after frequent restarts

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java

RATIS-2135. The leader keeps sending inconsistent entries repeatedly to followers.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java

RATIS-2139. Fix checkstyle:ParameterNumber in GrpcService.

---

ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java

Let leader set correct index when handling INCONSISTENCY in `LogAppenderDefault`
[RATIS-2137](https://issues.apache.org/jira/browse/RATIS-2137)

RATIS-2137. Fix LogAppenderDefault in handling of INCONSISTENCY

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/CliUtils.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractRatisCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/PauseCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/ResumeCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/StepDownCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/TransferCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/group/GroupListCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/local/RaftMetaConfCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/AddCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/RemoveCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/SetPriorityCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/snapshot/TakeSnapshotCommand.java

RATIS-2113. Use consistent method names and parameter types in RaftUtils

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

RATIS-2129. Low replication performance because of lock contention on RaftLog

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

see https://issues.apache.org/jira/browse/RATIS-2149

RATIS-2149.Do not perform leader election if the current RaftServer has not started yet

---

dev-support/make_rc.sh

see [jira](https://issues.apache.org/jira/browse/RATIS-2157)

RATIS-2157 Enhance make_rc.sh for non-first rc at release time

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/CliUtils.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/RatisShell.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractRatisCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/Context.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/PauseCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/ResumeCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/StepDownCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/TransferCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/group/GroupListCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/AddCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/RemoveCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/SetPriorityCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/snapshot/TakeSnapshotCommand.java
ratis-test/src/test/java/org/apache/ratis/security/SecurityTestUtils.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/TestSecureRatisShell.java

RATIS-2155. Add a builder for RatisShell.

---

content/post/3.1.1.md

Update Ratis website with announcement for 3.1.0 bugfix release.

RATIS-2163 Update website with Ratis 3.1.1 release

---

ratis-metrics-api/src/main/java/org/apache/ratis/metrics/MetricRegistriesLoader.java
ratis-metrics-default/src/test/java/org/apache/ratis/metrics/TestMetricRegistriesLoader.java

RATIS-2160. MetricRegistriesLoader should not print INFO message in CLI.

---

ratis-common/src/main/java/org/apache/ratis/util/FileUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegmentStartEnd.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogInputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogTestUtils.java
ratis-test/src/test/java/org/apache/ratis/conf/TestConfUtils.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestRaftLogReadWrite.java

RATIS-2178. Add a log message whenever deleting a RaftLog segment.

---

content/post/3.1.0.md
content/post/3.1.1.md
content/post/3.1.2.md

RATIS-2188. Update website with Ratis 3.1.2 release

---

ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java

Fix typo in RaftAsyncTests 
https://issues.apache.org/jira/browse/RATIS-212
CI: https://github.com/ongdisheng/ratis/actions/runs/12454185869

RATIS-212. Fix typo in RaftAsyncTests

---

pom.xml

see https://issues.apache.org/jira/browse/RATIS-2231

RATIS-2231 Bump Ratis-Thirdparty from 1.0.7 to 1.0.8

---

ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLogSequentialOps.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransactionManager.java

See https://issues.apache.org/jira/browse/RATIS-2232.
Thanks to the patch provided by @szetszwo

RATIS-2232. Improve log for debugging on RaftLog / TransactionManager

---

content/post/3.1.3.md

see https://issues.apache.org/jira/browse/RATIS-2238

RATIS-2238. Update website after 3.1.3 release

---

ratis-common/src/test/java/org/apache/ratis/BaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/expression/TestExpression.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-test/src/test/java/org/apache/ratis/RaftLogTruncateTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/retry/TestMultipleLinearRandomRetry.java
ratis-test/src/test/java/org/apache/ratis/retry/TestRetryPolicy.java

RATIS-2254. Replace junit 4 Timeout with junit 5.

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

RATIS-2256
My local maven version is the latest 3.9.9.  The change here is generated by running the following command.
```
mvn wrapper:wrapper
```

RATIS-2256. Update maven version.

---

ratis-grpc/pom.xml
ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-metrics-default/pom.xml
ratis-metrics-dropwizard3/pom.xml

RATIS-2255. Migrate ratis-grpc to junit 5.

---

ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/protocol/TermIndex.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/util/ServerStringUtils.java
ratis-test/src/test/java/org/apache/ratis/server/impl/TestLeaderElectionServerInterface.java

See RATIS-1995.
We also refactor the server call to `ServerInterface` in order to add new tests

RATIS-1995. Prevent data loss when a storage is accidentally re-formatted.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java

Fix some wrong symbols in ClientProtoUtils.
https://issues.apache.org/jira/browse/RATIS-2293
ci:
https://github.com/jianghuazhu/ratis/actions/runs/15035317966

RATIS-2293. Fix typo in ClientProtoUtils

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Please refer to https://issues.apache.org/jira/browse/RATIS-2314 for details.

[RATIS-2314] Fix that SegmentedRaftLogWorker may append entry by itself

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcStubPool.java

In https://issues.apache.org/jira/browse/RATIS-2325, a GrpcStubPool was added, and it was specified to use NIOEventLoopGroup, but on server side it's using epoll by default, this ticket is to remove the NIO specification.
https://issues.apache.org/jira/browse/RATIS-2342
Local test, no more warning logs like "WARN org.apache.ratis.thirdparty.io.netty.bootstrap.Bootstrap: Unknown channel option 'org.apache.ratis.thirdparty.io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT' for channel '[id: 0xe291c830]'"

RATIS-2342. Remove NIO specification from GrpcStubPool.
