apache/ratis

ratis-logservice/src/main/java/org/apache/ratis/logservice/shell/commands/ReadLogCommand.java

@chrajeshbabu @vladrodionov
An easy one.

RATIS-472. Clean up output for `read` logservice shell command

---

ratis-logservice/src/main/java/org/apache/ratis/logservice/tool/VerificationTool.java
ratis-logservice/src/test/java/org/apache/ratis/logservice/tool/TestVerificationTool.java

Pads the log entries that are written to the given size.
The read path of verification still works as the extra padding is trimmed off (the padding itself is not verified)

RATIS-546. Configurable value sizes on VerificationTool

---

pom.xml
ratis-assembly/pom.xml
ratis-assembly/src/main/assembly/bin.xml
ratis-assembly/src/main/assembly/src.xml

https://issues.apache.org/jira/browse/RATIS-807
How is this tested:
Test with the release script dev-support/make-rc.sh prepare_src and prepare_bin
prepare_bin will fail without the change.

RATIS-807. ratis-tools subproject is not included in the release jar.

---

ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java

Apache jira:
https://issues.apache.org/jira/browse/RATIS-879

RATIS-879. Fix TestRaftAsyncWithGrpc#testNoRetryWaitOnNotLeaderException

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java

I think the author of following code want to try 10 seconds until `followerState.getLastAppliedIndex() >= leaderLastIndex`, but actually `JavaUtils.attemptRepeatedly` will not retry unless the statement throw exception as the image shows.
```
// make sure the restarted follower can catchup
final ServerState followerState = cluster.getRaftServerImpl(followerId).getState();
JavaUtils.attemptRepeatedly(() -> followerState.getLastAppliedIndex() >= leaderLastIndex,
10, ONE_SECOND, "follower catchup", LOG);
```
I fix all the error use of JavaUtils.attemptRepeatedly to check boolean condition.
Maybe we have another method to avoid the error use of JavaUtils.attemptRepeatedly.

RATIS-885. Fix Failed UT because error use of attemptRepeatedly to check boolean condition

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

Can not elect a leader after a long time.
[RATIS-773](https://github.com/apache/incubator-ratis/commit/14927c7527afe13efb949065bbac0042ad82932f) has a change, as the image shows, cause this bug. 
The following switch statement is in  [while](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java#L197) loop.
If Timeout, the origin logic is continue, . But the new logic is return.

RATIS-991. Fix Failed UT: testRestartLogAppender

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java

Apache jira
https://issues.apache.org/jira/browse/RATIS-912

RATIS-912. Netty tests fail with RejectedExecutionException on channel close.

---

dev-support/checkstyle.xml
ratis-common/src/main/java/org/apache/ratis/retry/ExponentialBackoffRetry.java
ratis-common/src/main/java/org/apache/ratis/util/PlatformUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/metrics/LogServiceMetricsRegistry.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

1. Ignore violations in `NativeIO`-related classes, as these will be removed in [RATIS-757](https://issues.apache.org/jira/browse/RATIS-757).
2. Apply @dineshchitlangia's fix for `PlatformUtils` from aca98ffd3c94ca9e2f9c0798897631b726b381dd, which was lost between patches [001](https://issues.apache.org/jira/secure/attachment/12985021/RATIS-740.001.patch) and [002](https://issues.apache.org/jira/secure/attachment/12986074/RATIS-740.002.patch) in [RATIS-740](https://issues.apache.org/jira/browse/RATIS-740).
3. Fix few remaining violations.
https://issues.apache.org/jira/browse/RATIS-913
```
$ ./dev-support/checks/checkstyle.sh
...
INFO] BUILD SUCCESS
```
https://github.com/adoroszlai/incubator-ratis/runs/629340756

RATIS-913. Fix remaining (new) checkstyle violations

---

ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java

Fix TestRaftSnapshotWithGrpc and TestRaftSnapshotWithSimulatedRpc: `StateMachineUpdater` [unregisters metrics from the registry](https://github.com/apache/incubator-ratis/blob/56e2073515804cc70f64b215f971d547070ed38f/ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java#L129) during stop, so the timer after restart is not the same instance as before.  Thus, to verify that snapshot is taken during stop, we need to obtain the pre-stop timer.
Also verify the metric right after snapshot file is created.
https://issues.apache.org/jira/browse/RATIS-889
Executed `TestRaftSnapshot*` multiple times.  Also passed in CI:
https://github.com/adoroszlai/incubator-ratis/runs/633049769

RATIS-889. Fix TestRaftSnapshotWithGrpc and TestRaftSnapshotWithSimulatedRpc

---

ratis-server/src/test/java/org/apache/ratis/MiniRaftCluster.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java

In unit test testServerRestartOnException,  when call `ServerImplUtils.newRaftServer`, it did not set storage dir in RaftProperties. Then it use the default storage dir [/tmp/raft-server](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java#L45), but when test finish, it did not delete the generated sub dir. So every time testServerRestartOnException, it will generate a sub dir in /tmp/raft-server as the image shows. But when  testServerRestartOnException run, it will call `RaftServerProxy::initGroups`, and [create](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java#L194) a RaftServerImpl for each sub dir in …

RATIS-917. Set storage dir properties for testServerRestartOnException

---

pom.xml
ratis-test/src/test/resources/log4j.properties

1. include stack trace for test failures in results
2. include thread name in log message format
https://issues.apache.org/jira/browse/RATIS-915
Ran unit tests, verified output files.
```
$ cat ratis-test/target/surefire-reports/org.apache.ratis.server.simulation.TestRaftSnapshotWithSimulatedRpc.txt
-------------------------------------------------------------------------------
Test set: org.apache.ratis.server.simulation.TestRaftSnapshotWithSimulatedRpc
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.911 s <<< FAILURE! - in org.apache.ratis.server.simulation.TestRaftSnapshotWithSimulatedRpc
testBasicInstallSnapshot(org.apache.ratis.server.simulation.TestRaftSnapshotWithSimulatedRpc)  Time …
```

RATIS-915. Improve output of tests

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

The group-4F2C3D50C136 was deleted many times, but the log is not sufficient to find when it was deleted.

RATIS-927. Improve the log of remove group

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerMetrics.java

As the image shows, there are 2066 instances of RaftServerImpl, most of them are Closed, and should be GC, but actually not.
You can find from the image 2040 RaftServerImpl were held by RaftServerMetrics::metricsMap which is a staic map

RATIS-925. Fix memory leak of RaftServerImpl for no remove from static RaftServerMetrics::metricsMap

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java

`shutdownGracefully` does not pass any parameter from ratis, then it will take the default parameter at [shutdownGracefully(DEFAULT_SHUTDOWN_QUIET_PERIOD, DEFAULT_SHUTDOWN_TIMEOUT, TimeUnit.SECONDS)](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java#L70), the `DEFAULT_SHUTDOWN_QUIET_PERIOD` is 2 seconds, mean it can still accept new request in 2 seconds, you can also find it in the following code copied from netty, the `gracefulShutdownQuietPeriod `is the parameter `DEFAULT_SHUTDOWN_QUIET_PERIOD`. 
```
final long nanoTime = ScheduledFutureTask.nanoTime();
if (isShutdown() || nanoTime - gracefulShutdownStartTime > gracefulShutdownTimeout) {
return true;
}
if (nanoTime - lastExecutionTime <= …
```

RATIS-929. Shutdown EventLoopGroup faster

---

ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java

**Why WatchRequestTests.testWatchRequestClientTimeout failed ?**
The test try to watch a log index i.e. 1000 which will never be committed, so client can not receive reply, and connection closed throw AlreadyClosedException, [trigger TimeoutIOException](https://github.com/apache/incubator-ratis/blob/master/ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java#L325).
But when throw AlreadyClosedException, suggested new leader is null, because connection has been closed, so RaftClientImpl::handleIOException will [random select](https://github.com/apache/incubator-ratis/blob/master/ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java#L418) a new leader, so it maybe sometimes [throw …

RATIS-901. Fix Failed UT: WatchRequestTests.testWatchRequestClientTimeout

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

This Jira aims to fix the following:
- When Follower is in the process of installing snapshot and it gets an append entry, it replies with result INCONSISTENCY and the follower next index is updated to the snapshot index being installed. This should not happen as the snapshot installation is still in progress. Follower's next index on the leader should remain the same.
- After InstallSnapshot is done, Leader should update the commitIndex of the Follower to the installed snapshot index.
- After InstallSnapshot, when reloading StateMachine, any previously open LogSegment should be closed, if the last entry in the open log is already included in the snapshot.
- When Follower is notified to install snapshot through StateMachine, the reply should indicate the same. It would help with debugging …

RATIS-873. Fix Install Snapshot Notification

---

ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

This Jira aims to fix the following:
- Before sending an appendEntry request to follower, leader checks the validity of the request be verifying if the follower has the previous log entry. But if the follower had installed a snapshot, the previous could be missing and the appendEntry would still be valid. Hence, the SnapshotIndex should be factored in while checking the validity of appendEntry request. Leader should store Follower's SnapshotIndex for this.
- When follower receives appendEntry request, it checks the validity of log entry - the first index of the log entry is exactly 1 more than the last log index. During this check, the snapshotIndex should also be considered i.e. the first index of the log entry can be 1 more than the last log index or the snapshotIndex.
- After Ratis …

RATIS-874. Fix AppendEntry validity checks to take the SnapshotIndex into account

---

ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/cli/Assign.java
ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/expression/UnaryExpression.java
ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/expression/Variable.java
ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/cli/TestAssignCli.java

1. Allow variable names like `v1` in expressions, too
2. Allow expressions like `0.1 + 0.2`
3. Fix `NumberFormatException` for expression like `-5`
https://issues.apache.org/jira/browse/RATIS-639
Added test cases in unit test.  Also tested manually via CLI.

RATIS-639. Inconsistent pattern for variable names

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

When an open log segment is loaded, it always logs a warning that the segment is corrupted.
```
Segment file is corrupted: expected to have -43 entries but only 8 entries read successfully
```
LogSegment#loadSegment() has the following check for corruption:
```
final int expectedEntryCount = Math.toIntExact(end - start + 1);
final boolean corrupted = entryCount != expectedEntryCount;
if (corrupted) {
LOG.warn("Segment file is corrupted: expected to have {} entries but only {} entries read successfully",
expectedEntryCount, entryCount);
}
```
But the end is always INVALID_LOG_INDEX (-1) for an open segment.
Before this check, entries are appended to the segment. So the end variable should be updated with the correct endIndex of the segment before checking for corruption.

RATIS-937. Loading of open segments always throws corrupted segment warning

---

.github/workflows/post-commit.yml
dev-support/checks/sonar.sh

Ratis instance has been created in ASF's Sonar Cloud. This can now be used to analyze and improve the code quality. To ensure the analysis is automatically executed whenever there is a commit in master branch, we need to add a github action for Sonar check.
This PR aims to do that.
https://issues.apache.org/jira/browse/RATIS-940
For testing, I was able to add a token in my fork on incubator-ratis and confirm the script triggers analysis. For the incubator-ratis repo, ASF INFRA team helped to add the sonar cloud token in the repo settings via https://issues.apache.org/jira/browse/INFRA-20295
Once this PR is merged, I can confirm that the sonar check got enabled correctly.

RATIS-940. Add sonar check for ratis

---

ratis-server/src/test/java/org/apache/ratis/RaftExceptionBaseTest.java

In the test, the cluster first select an oldLeader such as s1, then force change to newLeader such as s2, and kill s2. Then client connect to s1 and expect s1 reply the info of real leader i.e. s2 in the NotLeaderException. But the s2 has been killed, ratis will triger a leader election, leader will change from s2 to s0, then s0 was included in the NotLeaderException rather than s2. so the test failed.
I think this UT is outdated. We can not expect the leader will not change if we kill the leader.

RATIS-900. Fix Failed UT: RaftExceptionBaseTest.testHandleNotLeaderAndIOException

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

Fixed checkstyle violation - unused import in LogSegment
Spotted in https://github.com/apache/incubator-ratis/pull/108

RATIS-943. Remove unused import in LogSegment

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/test/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogTestUtils.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

when create `RaftLogMetrics`, it use `memberId.getPeerId()` to identify, the `peerId` comes from `RaftServerProxy::getId`. So if one Ratis node belongs to different group, the `peerId` is same for different `RaftLogMetrics`. When create the second `RaftLogMetrics` for the second group, it will not create, because it's been created by the first group.
`memberId.toString()` will return `peerId + "@" + groupId`.

RATIS-942. Fix can not create raftLogMetrics in multi-raft

---

ratis-logservice/src/main/java/org/apache/ratis/logservice/api/LogServiceClient.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/server/MetaStateMachine.java
ratis-logservice/src/test/java/org/apache/ratis/logservice/server/TestMetaServer.java

```
ava.lang.AssertionError: expected:<19> but was:<20>
at org.apache.ratis.logservice.server.TestMetaServer.testJMXCount(TestMetaServer.java:339)
at org.apache.ratis.logservice.server.TestMetaServer.testListLogs(TestMetaServer.java:331)
```
1. when create log, it will call [RaftClientImpl::sendRequestWithRetry](https://github.com/apache/incubator-ratis/blob/master/ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java#L285), if throw TimeoutIOException, it will retry at [final RaftClientReply reply = sendRequest(request)](https://github.com/apache/incubator-ratis/blob/master/ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java#L296), So JMXCount will increase many times at [timerContext = …

RATIS-867. Fix failed UT: TestMetaServer#testListLogs

---

.github/workflows/post-commit.yml

RATIS-940 enabled the Sonar check for all the commits but it doesn't work for forked repositories (unless somebody set an own SONAR_TOKEN).
The fix is the same as HDDS-2627, we can restrict the execution to the Apache repository.
Thanks to Lokesh Jain who reported this issue:
Example failure:
https://github.com/lokeshj1703/incubator-ratis/runs/716253801
Note: PRs are not affected as they work well (no sonar check there) only the builds of forked repos.
https://issues.apache.org/jira/browse/RATIS-948
We should wait until the first build is finished on my fork:
https://github.com/elek/incubator-ratis/actions/runs/117813626
Unit test can fail only after the (ignored) sonar check.

RATIS-948. Update Sonar statistics only from the Apache repo, not from the forks

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/CacheInvalidationPolicy.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

If a segment is evicted from Segment Cache before it is rolled over and applyTransaction thread tries to read this segment, it can lead to FileNotFoundException.

RATIS-923. Cache evicted before RollSegment completes

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java

Failed UT: testRestartLogAppender
[grpcServerMetrics.unregister()](https://github.com/apache/incubator-ratis/blob/master/ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java#L130) was called when GrpcLogAppender become dead. If the order is: interrupt old GrpcLogAppender ->start new GrpcLogAppender -> grpcServerMetrics.onRequestInconsistency -> old GrpcLogAppender turn dead -> grpcServerMetrics.unregister when old GrpcLogAppender become dead -> unit test check the metric of grpcServerMetrics. Then the unit test failed, because grpcServerMetrics has been unregistered.
grpcServerMetrics.unregister should be called before interrupt old GrpcLogAppender, then start new GrpcLogAppender will create a new …

RATIS-964. Fix failed UT: testRestartLogAppender

---

.asf.yaml

Once a PR is opened, the corresponding Jira should get a new label "pull request available", the worklog should be updated and the PR should be linked in the jira.
https://issues.apache.org/jira/browse/RATIS-957
Followed instructions from INFRA, can be validated with the PR opened after this change is merged.

RATIS-957. Update .asf.yaml to define jira notifications strategy

---

ratis-metrics/src/main/java/org/apache/ratis/metrics/RatisMetricRegistry.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/RatisMetricRegistryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerMetrics.java

**What's the problem  ?**
One server was elected as leader twice. Every time leader will try to [addNumPendingRequestsByteSize {registry.gauge(REQUEST_BYTE_SIZE, () -> byteSize) } ](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java#L91) with a new `RequestLimits`. 
But in the second time, it can not re-guage again, because the `gauge` in metrics was implemented by `getOrAdd` as the following code shows. So it will first check whether `REQUEST_BYTE_SIZE` exist, if exist, it will not `gauge` `REQUEST_BYTE_SIZE`  again. So the `byteSize` is the old RequestLimits's,  and can not update when `addPendingRequest`, so assert failed.
```
public Gauge gauge(String name, final …
```

RATIS-939. Fix Failed UT: testRaftServerMetrics

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java

Adding Raft Log metrics concerning the count of various types of entries in the raft log.
https://issues.apache.org/jira/browse/RATIS-966
Tested by running through Ozone. Metrics are populating.

RATIS-966. Track commit metrics for different type of entries in RaftLog.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/impl/LogStreamImpl.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/server/LogServer.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/server/LogStateMachine.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/server/MetaStateMachine.java
ratis-logservice/src/test/java/org/apache/ratis/logservice/LogServiceReadWriteBase.java
ratis-logservice/src/test/java/org/apache/ratis/logservice/server/TestMetaServer.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/StateMachineShutdownTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/retry/TestExceptionDependentRetry.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/statemachine/TestStateMachine.java

Thousands of gRPC clients were not closed after use, in test and src. It will cause resource leak, and the unit test become very flaky. 
I think the following error is also caused by this problem.
This patch do the following:
1. add `GrpcUtil.shutdownManagedChannel` method to ensure the ManagedChannel was closed.
2. change `RaftClient client = ...` to `try (RaftClient client = ...)`, so that client can be closed.
3. change `LogStream logStream1 = client.createLog...` to` try (LogStream logStream1 = client.createLog...)`, so that the client in `LogStreamImpl` can be closed.
4. close the filed client which forgot to be closed in close method. Such as `metaClient` in `LogServer`

RATIS-921. Fix resource leak by closing thousands  of gRPC clients after use

---

ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java

1. MetricsStateMachine is instance of DataApi, so `data()` return `this`, and `data().flush` (i.e. `this.flush`) call the method self, the dead recursion happens.
```
default DataApi data() {
return this instanceof DataApi? (DataApi)this : DataApi.DEFAULT;
}
```
2. assertCommitCount always fail. @anshkhannasbu Could you explain why `stmCount + configCount + metaCount == expectedMsgs i.e. 2` ?  Sorry, I can not get the point.
https://issues.apache.org/jira/browse/RATIS-975
Existed tests.

RATIS-975. Fix failed UT: testRaftLogMetrics

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileInfo.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreAsyncBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreBaseTest.java

1. It's hard to finish write one 10M file and hundred 1M file in 100 seconds, if the leader re-election happens when write, timeout will happens.
2. `if (offset < writeSize)`  we can not throw exception. For example,  if leader finish write data with (offset = 4096, length = 4096), then writeSize of leader become 8192, and 2 follower has not written the data with (offset = 4096, length = 4096), then start a leader re-election, and the old leader elected as a new leader . So client will retry send the data with (offset = 4096, length = 4096), then (offset = 4096) < (writeSize=8192) in leader.  If we throw exception, leader can not write successfully forever.
https://issues.apache.org/jira/browse/RATIS-904
Existed test.

RATIS-904. Fix Failed UT: testFileStoreAsync

---

ratis-client/src/main/java/org/apache/ratis/client/api/MessageOutputStream.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/StreamImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StreamRequests.java
ratis-server/src/test/java/org/apache/ratis/StreamApiTests.java

See https://issues.apache.org/jira/browse/RATIS-958

RATIS-958. Support multiple requests in a single MessageOutputStream.

---

ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java

s1 received the request with callid: 999 at 2020-06-18 03:20:56,564, and after only 27ms i.e. 2020-06-18 03:20:56,591 unit test check the retry cache of s1 contain the request with callid: 999.  27ms is too short and s1 has not put the request in the retry cache, so test failed.
How to fix ?
Check many times whether the retry cache of s1 contain the request with callid: 999
https://issues.apache.org/jira/browse/RATIS-895
Existed tests

RATIS-895. Fix Failed UT: runTestRetryOnStateMachineException

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

1. There are server s0, s1, s2, all start leader election. But s2 has not start askForVotes.
s0
```
2020-06-21 03:46:27,958 [Thread-7] INFO  impl.RoleInfo (RoleInfo.java:updateAndGet(143)) - s0: start LeaderElection
2020-06-21 03:46:27,963 [s0@group-D88B65C78887-LeaderElection1] INFO  impl.LeaderElection (LeaderElection.java:askForVotes(206)) - s0@group-D88B65C78887-LeaderElection1: begin an election at term 1 for -1: [s0:0.0.0.0:40443, s1:0.0.0.0:46669, s2:0.0.0.0:41589], old=null
```
s1
```
2020-06-21 03:46:27,990 [Thread-8] INFO  impl.RoleInfo (RoleInfo.java:updateAndGet(143)) - s1: start LeaderElection
2020-06-21 03:46:27,998 [s1@group-D88B65C78887-LeaderElection2] INFO  impl.LeaderElection (LeaderElection.java:askForVotes(206)) - …
```

RATIS-983. Check follower state before ask for votes

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

This happens in test, but it maybe also happen in production.
For example, leader is s3 and follower is s4.
1. kill s4, and restart s4.
```
2020-06-19 07:03:18,095 [Thread-6194] INFO  ratis.MiniRaftCluster (MiniRaftCluster.java:killServer(458)) - killServer s4
2020-06-19 07:03:18,095 [Thread-6194] INFO  ratis.MiniRaftCluster (MiniRaftCluster.java:newRaftServer(330)) - newRaftServer: s4, group-5BD7E8A01610:[s3:0.0.0.0:43375, s4:0.0.0.0:33719, s0:0.0.0.0:34867, s1:0.0.0.0:33783, s2:0.0.0.0:40473], format? false
```
2. s4 start and set configuration from storage at [setRaftConf(raftConf.getLogEntryIndex(), raftConf) ](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java#L170) and s4 will change to …

RATIS-982. Fix RaftServerImpl illegal transition from RUNNING to RUNNING

---

ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java

How to fix ? 
try some times to check the assert condition.
https://issues.apache.org/jira/browse/RATIS-903
Existed tests.

RATIS-903. Fix Failed UT: RaftSnapshotBaseTest.testBasicInstallSnapshot

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

1. This happens in ozone production with ratis-0.5.0
2. leader notify follower install snapshot-(t:3, i:999697) infinitely
3.  follower install snapshot but log `StateMachine installSnapshot is in progress` infinitely.
What's the reason ?
1.  The log code of [StateMachine installSnapshot is in progress](https://github.com/apache/incubator-ratis/blob/ratis-0.5.0-rc0/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java#L1198) in ratis-0.5.0 as follow.
This log will be printed if [inProgressInstallSnapshotRequest.compareAndSet(null, firstAvailableLogTermIndex)](https://github.com/apache/incubator-ratis/blob/ratis-0.5.0-rc0/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java#L1157) return false, i.e. …

RATIS-987. Fix Infinite install snapshot

---

ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

@bshashikant Could you help review it ? Thank you very much.

RATIS-833. Add metrics for raft log cache count and size in bytes

---

ratis-hadoop/pom.xml
ratis-logservice/pom.xml

Exclude Netty version 3.10 from Ratis dependency. This gets added as a transitive dependency from Hadoop
https://issues.apache.org/jira/browse/RATIS-1006
Build succeeds.

RATIS-1006. Exclude Netty 3.10 from Ratis dependencies.

---

ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java

when `reinitialize` we need change state from PAUSED->STARTING->RUNNING
https://issues.apache.org/jira/browse/RATIS-1015
check `simpleStateMachine.getLifeCycleState`  after `reinitialize`

RATIS-1015. Fix Failed UT: testBasicInstallSnapshot

---

ratis-server/src/test/java/org/apache/ratis/server/impl/GroupInfoBaseTest.java

remove following assert
```
if (RaftPeerId.valueOf(i.getServer().getId()).equals(killedFollower)) {
Assert.assertTrue(i.getCommitIndex() <= maxCommit);
}
```
As the image shows, `killedFollower` is s0, after client receive RaftClientReply, s0 can still increase commit index if it receive metadata entry, then the commit index of s0 maybe greater than the max index in RaftClientReply.
https://issues.apache.org/jira/browse/RATIS-1018
No need to add unit tests.

RATIS-1018. Fix Failed UT: testGroupInfo

---

ratis-test/src/test/java/org/apache/ratis/retry/TestMultipleLinearRandomRetry.java

`randomized.getDuration()` got from the following code, i.e. `rounded`. `multiplier` is a double value less than 1.5 in the test, such as 1.4999999, `duration` is 1000, then `product` will be 1499.9999, so `rounded` will be 1500, which is not less than `d*1.5`, i.e. 1500.
https://issues.apache.org/jira/browse/RATIS-1021
No need to add ut.

RATIS-1021. Fix failed UT: testMultipleLinearRandomRetry

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogSequentialOps.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLogTest.java

Add unit tests to test MemoryReftLog log truncation
https://issues.apache.org/jira/browse/RATIS-1024
unit tests

RATIS-1024.Unit Tests for MemoryRaftLog entry truncation

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/server/MetricServerInterceptor.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupInfoBaseTest.java

When identifier is not NULL, `metrics` variable will not be initialized: https://github.com/apache/incubator-ratis/blob/349c365e81d76b210df7a97704217178e3f7f826/ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/server/MetricServerInterceptor.java#L71
https://issues.apache.org/jira/browse/RATIS-1029
UT

RATIS-1029. NPE at MetricServerInterceptor.interceptCall

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java

Change client to try the servers according to the priority
https://issues.apache.org/jira/browse/RATIS-1041
Check leader is the peer with highest priority as soon as create client.

RATIS-1041. Change client to try the servers according to the priority

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java

For example, s1, s2, s3's priority is (1, 2, 3). If s1 askForVotes, s2 reply success, but s3 crash, so exception happens.
Then election rejected at [return logAndReturn(Result.REJECTED, responses, exceptions, -1)](https://github.com/runzhiwang/incubator-ratis/blob/052e109bf33bedaf6754c6a26f55c2eb1d9dbae9/ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java#L351)
https://issues.apache.org/jira/browse/RATIS-1047
add test.

RATIS-1047. Fix can not elect leader when higher priority server crash

---

ratis-common/src/main/java/org/apache/ratis/util/MD5FileUtil.java

Use try-resource-block when saveMd5File
RATIS-1051
No need.

RATIS-1051. Use try-resource-block when saveMd5File

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

Switch cases should end with an unconditional "break" statement
RATIS-1055
No need.

RATIS-1055. Switch cases should end with an unconditional "break" statement

---

ratis-logservice/src/main/java/org/apache/ratis/logservice/server/LogStateMachine.java

Avoid NPE when exportInfo is NULL in LogStateMachine.processArchiveLog. 
Detailed analysis see https://issues.apache.org/jira/browse/RATIS-1059
https://issues.apache.org/jira/browse/RATIS-1059
N/A

RATIS-1059. Avoid NPE when exportInfo is NULL in LogStateMachine.processArchiveLog

---

ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestGrpcOutputStream.java

`TestGrpcOutputStream` has failed both `testKillLeader` and `testSimpleWrite`. This PR fixes `testSimpleWrite`.
For the failure of `testSimpleWrite`:
It is because the CLUSTER hasn't elect a leader.
https://issues.apache.org/jira/browse/RATIS-1064
UT

RATIS-1064. Fix TestGrpcOutputStream.testSimpleWrite

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-test/src/test/java/org/apache/ratis/server/simulation/TestRatisServerMetricsWithSimulatedRpc.java

Add a metric for tracking failed client requests on a server
https://issues.apache.org/jira/browse/RATIS-830
UT

RATIS-830. Add a metric for tracking failed client requests on a server

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java

Co-authored-by: Elek Márton <elek@apache.org>
The PR initiates heartbeat if follower's commitIndex lags from leader's commitIndex. This helps in faster resolution of any pending watch requests in the leader. 
It also changes the waitTimes for the appender thread so that the thread does not sleep for a long time while there are pending watch requests in leader.
https://issues.apache.org/jira/browse/RATIS-1042
Existing UT and by running teragen for Ozone

RATIS-1042. Watch for commit calls are blocked for a long if no other message

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

GrpcLogAppender improperly decrease nextIndex to 1, which will trigger installSnapshot request to followers, and make pipeline be vulnerable.
https://issues.apache.org/jira/browse/RATIS-1074
CI

RATIS-1074:  GrpcLogAppender improperly decrease nextIndex to 1, which may trigger a installSnapshot request to follower.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java

Should not shutdown and re-create channel/stub in GrpcServerProtocolClient when StreamObserver::onError() is called.
It is un-necessary and dangerous.
For detail behind the change, please check https://github.com/grpc/grpc-java/issues/7442
https://issues.apache.org/jira/browse/RATIS-1072
Please check reply from grpc community:
https://github.com/grpc/grpc-java/issues/7442
https://github.com/grpc/grpc-java/issues/7449#issuecomment-697766246
CI

RATIS-1072: Should not shutdown and re-create channel/stub in GrpcServerProtocolClient when StreamObserver::onError() is called.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamReplyByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestByteBuffer.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/DataStreamReplyDecoder.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/DataStreamRequestEncoder.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamReplyEncoder.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamRequestByteBuf.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamRequestDecoder.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1078

RATIS-1078. Refactor DataStream classes.

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/api/GroupManagementApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/GroupManagementImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/UnorderedAsync.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/server/MetaStateMachine.java
ratis-server/src/test/java/org/apache/ratis/RaftExceptionBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupInfoBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-test/src/test/java/org/apache/ratis/statemachine/TestStateMachine.java

See https://issues.apache.org/jira/browse/RATIS-1092

RATIS-1092. Move the group management methods from RaftClient to a new interface

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/api/AsyncApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AsyncApiImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AsyncImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftOutputStream.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreClient.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/RequestLimitAsyncBaseTest.java
ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestGrpcMessageMetrics.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/retry/TestExceptionDependentRetry.java

…face
Move sync api from RaftClient interface to AsyncApi interface
https://issues.apache.org/jira/browse/RATIS-1094
UT

RATIS-1094. Move async methods from RaftClient to a new AsyncApi interface

---

ratis-client/src/main/java/org/apache/ratis/client/api/AsyncApi.java
ratis-client/src/main/java/org/apache/ratis/client/api/BlockingApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AsyncImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/GroupManagementImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/MessageStreamImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java

See https://issues.apache.org/jira/browse/RATIS-1095

RATIS-1095. Move the related methods from RaftClientImpl to the corresponding impls.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

While closing an open log segment using the SegmentedRaftLogWorker#closeLogSegment method, the corresponding cache segment also needs to be rolled (close and open a new empty one). Else, the cache will go out of sync with the on disk log segment state.
https://issues.apache.org/jira/browse/RATIS-1049
Manually tested.
Unit tests pending.

RATIS-1088. SegmentedRaftLogWorker#closeLogSegment should also roll the open segment maintained in the cache.

---

ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java

Seeing a flaky instance of `RaftBasicTests.runTestOldLeaderNotCommit` due to `IndexOutOfBounds` (https://github.com/apache/incubator-ratis/pull/225/checks?check_run_id=1281324912).
The exception is from 
```
for (int i = 1; i < NUM_SERVERS - 1; i++) {
RaftServerImpl follower = followers.get(i);
cluster.killServer(follower.getId());
}
```
where it turned out i exceeded the range of followers size. This might be due to slow machine/process so followers are not enough.
Per suggestion from @szetszwo  we can use `org.junit.AssumptionViolatedException` to not fail this test in this special case.
https://issues.apache.org/jira/browse/RATIS-1101
UT

RATIS-1101. Fix Failed UT: RaftBasicTests.runTestOldLeaderNotCommit:IndexOutOfBounds

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

Add a correctness check that compares the `byteswritten` to peers with current `byteswritten` locally.  If remote write is not successful or `byteswritten` is not equal, should return a reply with "not success".
https://issues.apache.org/jira/browse/RATIS-1104
UT

RATIS-1104.Should check "bytewritten" from remote writes to peers to determine whether current stream write is successful

---

ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/MetricRegistriesImpl.java

https://issues.apache.org/jira/browse/RATIS-1102
The warning message in `MetricRegistriesImpl#create` should read `addReport*er*Registration`. It was missing the "er". Confused me for a bit when I'm trying to follow the message.

RATIS-1102. Fix typo in MetricRegistriesImpl#create warning message

---

ratis-common/src/main/java/org/apache/ratis/datastream/SupportedDataStreamType.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DisabledDataStreamFactory.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamBase.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

Add SupportedDataStreamType.DISABLED to control whether datastream server is enabled. It is because running a DataStream server in RaftServer has a cost thus it might be better to allow enable/disable it that depends on needs. 
https://issues.apache.org/jira/browse/RATIS-1108
UT

RATIS-1108. Add SupportedDataStreamType.DISABLED

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClientFactory.java
ratis-client/src/main/java/org/apache/ratis/client/DisabledDataStreamClientFactory.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/datastream/DataStreamFactory.java
ratis-common/src/main/java/org/apache/ratis/datastream/DataStreamType.java
ratis-common/src/main/java/org/apache/ratis/datastream/SupportedDataStreamType.java
ratis-server/src/main/java/org/apache/ratis/server/DataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/DisabledDataStreamServerFactory.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DataStreamServerImpl.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java

See https://issues.apache.org/jira/browse/RATIS-1116

RATIS-1116. Add DataStreamType.

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-client/src/main/java/org/apache/ratis/client/DataStreamClientRpc.java
ratis-client/src/main/java/org/apache/ratis/client/DisabledDataStreamClientFactory.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamBase.java

See https://issues.apache.org/jira/browse/RATIS-1117

RATIS-1117. Remove DataStreamClient.start() and DataStreamClientRpc.startClient().

---

ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

TestDataStream no long tests right state machine after RATIS-1124. It is because RaftServer uses its own map to keep state machine so the original state machines used to test server's writes no long work.
https://issues.apache.org/jira/browse/RATIS-1125
UT

RATIS-1125. Fix TestDataStream

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

Use new thread pool to support more than 10 streams
https://issues.apache.org/jira/browse/RATIS-1126
increase 10 streams to 20 streams

RATIS-1126. Fix can not support more than 10 streams

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/statemachine/StateMachine.java

When Ratis receives a Configuration change request (SetConfiguration), the StateMachine is only notified of index update.
CompletableFuture<Message> applyLogToStateMachine(LogEntryProto next) {
if (!next.hasStateMachineLogEntry()) {
stateMachine.notifyIndexUpdate(next.getTerm(), next.getIndex());
} else if (next.hasStateMachineLogEntry()) {
......
This Jira aims to add a method in StateMachine interface to notify StateMachine about configuration change.
https://issues.apache.org/jira/browse/RATIS-1109
No unit test. Tested on Ozone cluster.

RATIS-1109. Notify StateMachine on Configuration change

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfiguration.java
ratis-server/src/test/java/org/apache/ratis/server/impl/PeerConfigurationTest.java

In the leader election approach, the candidate will change to leader in advance if the majority voters vote for it. we can also terminate the approach if majority voters reject it.
https://issues.apache.org/jira/browse/RATIS-1120
unit test.

RATIS-1120. Terminate election in advance if majority peers reject

---

ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerConstants.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java

If a Follower is lagging behind and needs to install snapshot to catch up, it can miss any configuration changes that were applied on the Leader. When installing snapshot, the configuration change must also be propagated and applied on the follower. 
https://issues.apache.org/jira/browse/RATIS-1128
(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

RATIS-1128. Update Configuration on InstallSnapshot

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamOutputRpc.java
ratis-client/src/main/java/org/apache/ratis/client/api/MessageStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

See https://issues.apache.org/jira/browse/RATIS-1129

RATIS-1129. Move out the RPC related APIs from DataStreamOutput.

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-client/src/main/java/org/apache/ratis/client/DataStreamRpcApi.java
ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

When peer create data stream, it call RaftClientImpl.nextCallId(), so the primary's streamId maybe different from peer's.
It maybe difficult to debug when error happen.
https://issues.apache.org/jira/browse/RATIS-1132
new ut

RATIS-1132. Primary and peer should use the same streamId

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamRpcApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

When primary create DataStreamOutputImpl for peer, it will create a new [RaftClientRequest](https://github.com/apache/incubator-ratis/blob/master/ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java#L77) and send it to peer. I think primary should send RaftClientRequest got from client to peer.
https://issues.apache.org/jira/browse/RATIS-1133
new assert

RATIS-1133. Primary and peer should use the same RaftClientReques

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamPacketByteBuffer.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1134

RATIS-1134. Remove DataStreamApi.stream(RaftGroupId).

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

The server id could be `null` at https://github.com/apache/incubator-ratis/blob/189ee94471afdef8bd6c8b1fb419309230bfaa24/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java#L185
So move the DataStreamServer creation after it.
Otherwise the `server.getId()` could be `null` at https://github.com/apache/incubator-ratis/blob/189ee94471afdef8bd6c8b1fb419309230bfaa24/ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java#L221
https://issues.apache.org/jira/browse/RATIS-1135
UT

RATIS-1135. Initialize DataStreamServer after RaftServerProxy id is set

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

I found this issue when setting up MiniRaftCluster for data stream. In a normal case, every Raft peer can act as a primary server and clients will decide which Raft to use.
However, when all Raft peers can act as a primary. in previous implementation, there will be a deadlock case that a server will receive a request, and then route to other peers, and other peers will do the same.
Thus we should distinguish primary server by adding primary server id into the Raft proto, and do not forward requests to peers when the server is not the primary.
https://issues.apache.org/jira/browse/RATIS-1140
UT

RATIS-1140. Do not create DataStreamOutput for non-primary server

---

ratis-client/src/main/java/org/apache/ratis/client/DataStreamOutputRpc.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-proto/src/main/proto/Raft.proto

Remove STREAM_CLOSE_FORWARD, because we use `boolean isPrimary(RaftPeerId primaryId) `to distinguish primary and peer.
https://issues.apache.org/jira/browse/RATIS-1142
No need new ut.

RATIS-1142. Remove STREAM_CLOSE_FORWARD

---

ratis-common/src/main/java/org/apache/ratis/RaftConfigKeys.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

Default disable datastream when start a MiniRaftCluster, so that the other test no need to start data stream server, to make the CI run faster.
https://issues.apache.org/jira/browse/RATIS-1144
no need to add new ut.

RATIS-1144. Default disable datastream when start a MiniRaftCluster

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1145

RATIS-1145. In NettyServerStreamRpc, the local/remote writes should only wait for the previous write.

---

.github/workflows/post-commit.yml
.github/workflows/pr.yml
dev-support/checks/build.sh
pom.xml
ratis-proto/pom.xml

1. Add `javax.annotation-api` dependency, required for compilation with Java 9+.
2. Improve _compile_ CI check to build Ratis with both Java 8 and Java 11.
https://issues.apache.org/jira/browse/RATIS-1146
Compile checks:
https://github.com/adoroszlai/incubator-ratis/runs/1385567749#step:4:10
https://github.com/adoroszlai/incubator-ratis/runs/1385567774#step:4:1729
Compiled Ratis locally with the same Java versions, and Java 14, too:
```
$ mvn -DskipTests -V clean package
...
Java version: 14.0.1
...
[INFO] BUILD SUCCESS
```

RATIS-1146. Does not build with newer JDK

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1151

RATIS-1151. Move the DateStream requests handling code from NettyServerStreamRpc to a new class.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

Need to wait the ChannelFuture be completed. Otherwise the local address (`channelFuture.channel().localAddress()`) could be `null`.
https://issues.apache.org/jira/browse/RATIS-1159
UT (run 100 times locally without seeing the timeout issue again)

RATIS-1159. Wait ChannelFuture be completed before getting the local address

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientMessage.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-1160

RATIS-1160. DataStreamClientImpl.closeAsync() should be idempotent.

---

ratis-server/src/main/java/org/apache/ratis/server/JvmPauseMonitor.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

Idea of JvmpauseMonitor taken from hadoop with two additional conditions added:
1) If the total jvm pause time exceeds maxRpcTimeout in Ratis, ratis leader will stepdown
2) If the total pause time exceeds rpcSlownesstimeout, kill all the ratis pipeline on the node
https://issues.apache.org/jira/browse/RATIS-1149
Tested Manually by adding below code manually :
`@@ -97,7 +98,12 @@ public class TestRaftServerWithGrpc extends BaseTest implements MiniRaftClusterW
final RaftServerImpl leader = RaftTestUtil.waitForLeader(cluster);
final RaftPeerId leaderId = leader.getId();
-    final RaftProperties p = getProperties();
+    List<String> list = Lists.newArrayList();
+    int i = 0;
+    while (true) {
+      list.add(String.valueOf(i++));
+    }
+   /* final RaftProperties p = getProperties();
` …

RATIS-1149. Leader should step down and initiate a stateMachine action in case of jvm pauses.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/GroupInfoReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/GroupListReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientMessage.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientReply.java
ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolService.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequest.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamNetty.java

See https://issues.apache.org/jira/browse/RATIS-610

RATIS-610. Add a builder for RaftClientReply.

---

ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-netty/src/test/java/org/apache/ratis/netty/MiniRaftClusterWithNetty.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/MiniRaftClusterWithGrpcAndNettyDataStream.java
ratis-test/src/test/java/org/apache/ratis/datastream/MiniRaftClusterWithRpcTypeGrpcAndDataStreamTypeNetty.java
ratis-test/src/test/java/org/apache/ratis/datastream/MiniRaftClusterWithRpcTypeNettyAndDataStreamTypeNetty.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamWithGrpcCluster.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamWithNettyCluster.java

See https://issues.apache.org/jira/browse/RATIS-1162

RATIS-1162. Enable testing clusters with Netty data stream and gRPC.

---

ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/ArithmeticStateMachine.java
ratis-logservice/src/main/java/org/apache/ratis/logservice/server/LogStateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerConstants.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogSequentialOps.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogInputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogReader.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectory.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestRaftLogReadWrite.java

See https://issues.apache.org/jira/browse/RATIS-1164

RATIS-1164. Remove deprecated RaftServerConstants.INVALID_LOG_INDEX.

---

content/getting_started.md

Remove the redundant " in link to Raft page.
https://issues.apache.org/jira/browse/RATIS-1167
IMHO it is a minor change, and we don't need test.

RATIS-1167. Fix the link to raft main page

---

ratis-common/src/main/java/org/apache/ratis/util/CollectionUtils.java
ratis-server/src/test/java/org/apache/ratis/MiniRaftCluster.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamWithGrpcCluster.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamWithMock.java

See https://issues.apache.org/jira/browse/RATIS-1169

RATIS-1169. Move the DataStream tests from TestDataStreamNetty to DataStreamClusterTests

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

When a follower is in candidate state but unable to get votes and also unable to get new leader info, the JMXBeanServer query to getLeaderId can throw a NPE. 
This happens because RaftServerJmxAdapter#getLeaderId() does not check whether leaderId is null before calling toString() on it.

RATIS-1177. NPE when RaftServerJmxAdapter queries getLeaderId.

---

ratis-examples/src/test/java/org/apache/ratis/TestMultiRaftGroup.java
ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/TestArithmeticLogDump.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/test/java/org/apache/ratis/MessageStreamApiTests.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/RaftExceptionBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RequestLimitAsyncBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupInfoBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerNoLeaderTimeout.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerSlownessDetection.java
ratis-test/src/test/java/org/apache/ratis/statemachine/TestStateMachine.java

See https://issues.apache.org/jira/browse/RATIS-1182

RATIS-1182. Move RaftServerProxy/RaftServerImpl LOG to RaftServer.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RoleInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/test/java/org/apache/ratis/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamWithMock.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestGrpcMessageMetrics.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRetryCacheWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/statemachine/TestStateMachine.java

See https://issues.apache.org/jira/browse/RATIS-1183

RATIS-1183. Add getId() and getPeer() to RaftServer/RaftServer.Division.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetrics.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerSlownessDetection.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftSnapshotWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1184

RATIS-1184. Move RaftServerMetrics to org.apache.ratis.server.metrics.

---

ratis-grpc/src/test/java/org/apache/ratis/grpc/server/TestGrpcServerMetrics.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/RatisMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/LeaderElectionMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/metrics/TestLeaderElectionMetrics.java

See https://issues.apache.org/jira/browse/RATIS-1187

RATIS-1187. Avoid directly using RaftServerImpl in LeaderElectionMetrics

---

ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/TestArithmeticLogDump.java
ratis-logservice/src/test/java/org/apache/ratis/logservice/server/TestMetaServer.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/StateMachineShutdownTests.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/retry/TestExceptionDependentRetry.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java
ratis-test/src/test/java/org/apache/ratis/statemachine/TestStateMachine.java

See https://issues.apache.org/jira/browse/RATIS-1188

Ratis 1188. Change MiniRaftCluster.getLeader() to return RaftServer.Division.

---

ratis-server/src/test/java/org/apache/ratis/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/RequestLimitAsyncBaseTest.java
ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/ServerPauseResumeTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/MiniRaftClusterWithSimulatedRpc.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerNoLeaderTimeout.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestGrpcOutputStream.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java

See https://issues.apache.org/jira/browse/RATIS-1189

RATIS-1189. Change other MiniRaftCluster methods to return RaftServerDivision

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

make RaftServerImpl#getRoleInfoProto() public, providing app layer an atomic way to get term and role when RaftServer is a leader.
https://issues.apache.org/jira/browse/RATIS-1001
CI

RATIS-1001. Make RaftServerImpl#getRoleInfoProto() public

---

ratis-examples/src/main/bin/client.sh

The docs[1] that describe client command will added duplicate peers parameters.
```
${BIN}/client.sh filestore loadgen --size 1024000 --numFiles 10 --peers ${PEERS}
Found xxx/incubator-ratis/ratis-examples/target/ratis-examples-1.1.0-SNAPSHOT.jar
Wrong parameters: Can only specify option --peers once.
```
I think the QUORUM_OPTS parameter should not be used in client.sh, just like server.sh.
[1] https://github.com/apache/incubator-ratis/blob/master/ratis-examples/README.md#filestore-client
https://issues.apache.org/jira/browse/RATIS-1066
manual tests

RATIS-1066. Fixed example filestore client run failed

---

ratis-common/src/main/java/org/apache/ratis/conf/RaftProperties.java

Prevent external XML entities attacks:
1. Turn on "secure processing" for XML
2. Disable external DTD/schema explicitly
[SonarCloud](https://sonarcloud.io/organizations/apache/rules?open=java%3AS2755&rule_key=java%3AS2755) and SonarLint display slightly different instructions for fixing XXE.  This change applies both.
https://issues.apache.org/jira/browse/RATIS-953
Existing unit tests.
https://github.com/adoroszlai/incubator-ratis/runs/771645855

RATIS-953. XML Parsers should not be vulnerable to XXE attacks

---

ratis-logservice/src/main/java/org/apache/ratis/logservice/server/LogStateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftStateMachineExceptionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/ServerPauseResumeTest.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java

See https://issues.apache.org/jira/browse/RATIS-1193

RATIS-1193. Add getRaftLog() to RaftServer.Division.

---

ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java

Proposed code changes to fix flaky test in class `TestRetryCacheMetrics.java`
https://issues.apache.org/jira/browse/RATIS-1203#
(This JIRA ticket contains more detailed info. for this PR)
- The flaky test is found by running [iDFlakies](https://github.com/idflakies/iDFlakies) (tools for detecting/classifying flaky tests). After fixing the issue, there are no flaky tests.
- This patch is also tested with maven command: `mvn test`

RATIS-1203. Fix flaky tests caused by TestRetryCacheMetrics#retryCache

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

Use FileStore write 1GB file, OOM happens.
**How to reproduce ?**
1.  change timeout 100 seconds to 600 seconds.
```
public int getGlobalTimeoutSeconds() {
return 100;
}
```
2. change 1M to 50M, and run `testFileStore`, OOM happens
`testMultipleFiles("file", 20, SizeInBytes.valueOf("1M"), newClient);`
1. In FileStore, `CACHING_ENABLED_DEFAULT`, i.e. `stateMachineCachingEnabled` is false,  so cache will append the complete LogEntryProto into cache, without remove StateMachineData.
```
if (stateMachineCachingEnabled) {
// The stateMachineData will be cached inside the StateMachine itself.
cache.appendEntry(ServerProtoUtils.removeStateMachineData(entry));
} else {
cache.appendEntry(entry);
}
```
2. But when getEntrySize, it does not calculate …

RATIS-1198. Fix OOM when use FileStore to write 1GB file

---

ratis-examples/src/main/java/org/apache/ratis/examples/common/SubCommandBase.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/LoadGen.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Server.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

Change the FileStore CLI to use Streaming
https://issues.apache.org/jira/browse/RATIS-1186
1.
Common env in client and servers.
```
BIN=ratis-examples/src/main/bin
PEERS=n0:127.0.0.1:6000:7000,n1:127.0.0.1:6001:7001,n2:127.0.0.1:6002:7002
```
Start 3 servers.
```
ID=n0; ${BIN}/server.sh filestore server --id ${ID} --storage /tmp/ratis/${ID} --peers ${PEERS}
ID=n1; ${BIN}/server.sh filestore server --id ${ID} --storage /tmp/ratis/${ID} --peers ${PEERS}
ID=n2; ${BIN}/server.sh filestore server --id ${ID} --storage /tmp/ratis/${ID} --peers ${PEERS}
```
2. 
DataStreamApi: DirectByteBuffer, MappedByteBuffer, transferTo
```
${BIN}/client.sh filestore datastream --size 100000000 --numFiles 10 --bufferSize 1000000 --type DirectByteBuffer --peers ${PEERS}
${BIN}/client.sh filestore datastream …
```

RATIS-1186. Change the FileStore CLI to use Streaming

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java

We can provide a default implementation for ``DataStreamOutput stream();` so it can reuse existing code.
https://issues.apache.org/jira/browse/RATIS-1213
UT

RATIS-1213. Provide a default implementation for DataStreamApi.stream()

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

Currently, duplicated key maybe put into entryCache by different threads loading segment file at the same time. So we should allow it.
For example.
First thread's stack:
```
org.apache.ratis.server.raftlog.segmented.LogSegment$LogEntryLoader|LogSegment.java|245|load
org.apache.ratis.server.raftlog.segmented.LogSegment|LogSegment.java|363|loadCache
org.apache.ratis.server.raftlog.segmented.SegmentedRaftLog|SegmentedRaftLog.java|275|get
org.apache.ratis.server.impl.StateMachineUpdater|StateMachineUpdater.java|223|applyLog
org.apache.ratis.server.impl.StateMachineUpdater|StateMachineUpdater.java|176|run
```
Second thread's stack:
```
org.apache.ratis.server.raftlog.segmented.LogSegment$LogEntryLoader|LogSegment.java|245|load
org.apache.ratis.server.raftlog.segmented.LogSegment|LogSegment.java …
```

RATIS-1215. Allow put duplicate key into LogSegment#entryCache

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileInfo.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Server.java

1. There are two usage for FileStore#read, the first is for FileStoreStateMachine#query which read  data has been committed, the second if for FileStoreStateMachine#read which read data has been written by leader, and leader read the data to appendEntry to follower. So in the second case, we should not check `offset + length > committedSize`, we should check `offset + length > writeSize`
2. data length should use ByteBuffer#remaining()
```
final WriteRequestHeaderProto.Builder header = WriteRequestHeaderProto.newBuilder()
.setPath(ProtoUtils.toByteString(path))
.setOffset(offset)
-        .setLength(data.position())
+        .setLength(data.remaining())
.setClose(close);
```
https://issues.apache.org/jira/browse/RATIS-1217
manually execute following command many times.
${BIN}/client.sh …

RATIS-1217. Fix filestore failed readStateMachineData when use AsyncApi

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileInfo.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/LoadGen.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreAsyncBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreWriter.java
ratis-proto/src/main/proto/Examples.proto

Add sync option when test filestore performance
https://issues.apache.org/jira/browse/RATIS-1218
Test it manually
The test command of sync:
```
${BIN}/client.sh filestore datastream --size 128000000 --numFiles 10 --bufferSize 4000000 --syncSize 16000000 --type DirectByteBuffer --peers ${PEERS}
${BIN}/client.sh filestore loadgen --size 128000000 --numFiles 10 --bufferSize 4000000 --sync 1 --peers ${PEERS}
```
The test command of no sync:
```
${BIN}/client.sh filestore datastream --size 128000000 --numFiles 10 --bufferSize 4000000 --syncSize -1 --type DirectByteBuffer --peers ${PEERS}
${BIN}/client.sh filestore loadgen --size 128000000 --numFiles 10 --bufferSize 4000000 --sync 0 --peers ${PEERS}
```

RATIS-1218. Add sync option when test filestore performance

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Server.java

FileStore support multi disk
https://issues.apache.org/jira/browse/RATIS-1228
`nohup ${BIN}/server.sh filestore server --id n0 --storage /data/ratis/n0 --storage /data1/ratis/n0 --storage /data2/ratis/n0 --storage /data3/ratis/n0 --storage /data4/ratis/n0 --storage /data5/ratis/n0 --storage /data6/ratis/n0 --storage /data7/ratis/n0 --storage /data8/ratis/n0 --storage /data9/ratis/n0 --storage /data10/ratis/n0 --storage /data11/ratis/n0 --peers ${PEERS} >> n0.log 2>&1 &`

RATIS-1228. FileStore support multi disk

---

ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/TestArithmeticLogDump.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServerRpcWithProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerSlownessDetection.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java

See https://issues.apache.org/jira/browse/RATIS-1227

RATIS-1227. RaftServerRpcWithProxy constructor and the abstract impl methods should be protected.

---

ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/StateMachineException.java
ratis-hadoop/src/test/java/org/apache/ratis/hadooprpc/TestPreAppendLeaderStepDownWithHadoopRpc.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/test/java/org/apache/ratis/server/impl/PreAppendLeaderStepDownTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestPreAppendLeaderStepDownWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/netty/TestPreAppendLeaderStepDownWithNetty.java
ratis-test/src/test/java/org/apache/ratis/server/simulation/TestPreAppendLeaderStepDownWithSimulatedRpc.java

Add a flag to `StateMachineException` to indicate whether the exception should cause the leader to step down. In `RaftServerImpl#appendTransaction`, only trigger a leader step down if the flag in the StateMachineException is enabled.
[RATIS-1216](https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1216?filter=allopenissues)
Integration tests added.

RATIS-1216. State machine preAppend callback can throw exception without having leader to step down.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/TransactionContextImpl.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestCacheEviction.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestRaftLogReadWrite.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java
ratis-tools/src/main/java/org/apache/ratis/tools/ParseRatisLog.java

See https://issues.apache.org/jira/browse/RATIS-1230

RATIS-1230. Move out the LogEntryProto methods from ServerProtoUtils.

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreCommon.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/LoadGen.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Server.java

1. FileStore client generate files by multi-thread, in multi-disk
2. config write, read, commit, delete thread number in FileStoreStateMachine
3. client drop system cache before read.
https://issues.apache.org/jira/browse/RATIS-1229
test it manually by command
client:
`${BIN}/client.sh filestore datastream --size 128000000 --numFiles 1000 --bufferSize 4000000 --syncSize 16000000 --type DirectByteBuffer --peers ${PEERS} --storage /data/ratis/n2 --storage /data1/ratis/n2 --storage /data2/ratis/n2 --storage /data3/ratis/n2 --storage /data4/ratis/n2 --storage /data5/ratis/n2 --storage /data6/ratis/n2 --storage /data7/ratis/n2 --storage /data8/ratis/n2 --storage /data9/ratis/n2 --storage /data10/ratis/n2 --storage /data11/ratis/n2`
server:
`nohup ${BIN}/server.sh filestore server --id n2 …

RATIS-1229. FileStore client generate files in parallel

---

ratis-examples/src/main/java/org/apache/ratis/examples/common/SubCommandBase.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Server.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

Seperate the thread pool of request and write disk 
https://issues.apache.org/jira/browse/RATIS-1238
No need to add new ut.

RATIS-1238. Seperate request and write executor

---

community.html
index.html

Ratis website lists the old slack workspace. This should be updated to the channel being used currently.
https://issues.apache.org/jira/browse/RATIS-1235
(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

RATIS-1235. Update slack invite in ratis website

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeer.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java

In HA case, such as there are three server: server1, server2, server3, server1 is the leader.
1. if we want to rolling upgrade leader, we can upgrade server2, and then assign server2 with the highest priority, and server1 stop accepting client request, then server2 will try to grab the leader once catch up the log
2. if we want to rollback, we can assign server1 with the highest priority again and server2 stop accepting client request.
https://issues.apache.org/jira/browse/RATIS-1245
new ut

RATIS-1245. Support change priority dynamically

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamOutput.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestByteBuffer.java
ratis-common/src/main/java/org/apache/ratis/datastream/impl/DataStreamRequestFilePositionCount.java
ratis-common/src/main/java/org/apache/ratis/io/StandardWriteOption.java
ratis-common/src/main/java/org/apache/ratis/io/WriteOption.java
ratis-common/src/main/java/org/apache/ratis/protocol/DataStreamRequestHeader.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/DataStream.java
ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreWriter.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamRequestByteBuf.java
ratis-proto/src/main/proto/Raft.proto
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

For the CLOSE, we can add a new API, writeAndClose(..) to save STREAM_CLOSE RPC call.
https://issues.apache.org/jira/browse/RATIS-1196

RATIS-1196. Save STREAM_CLOSE RPC call

---

ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/TestArithmeticLogDump.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegmentPath.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegmentStartEnd.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectory.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestRaftLogReadWrite.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java
ratis-tools/src/main/java/org/apache/ratis/tools/ParseRatisLog.java

See https://issues.apache.org/jira/browse/RATIS-1246

RATIS-1246. Move out LogPathAndIndex from RaftStorageDirectory.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/server/HadoopRpcService.java
ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/server/RaftServerProtocolServerSideTranslatorPB.java
ratis-hadoop/src/main/proto/HadoopCompatability.proto
ratis-netty/src/main/java/org/apache/ratis/netty/NettyRpcProxy.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java
ratis-proto/src/main/proto/Grpc.proto
ratis-proto/src/main/proto/Netty.proto
ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/protocol/RaftServerProtocol.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/test/java/org/apache/ratis/server/impl/BlockRequestHandlingInjection.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/RaftServerReply.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/RaftServerRequest.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedServerRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

Leader send TimeoutNow request to higher priority peer
For example, there are 3 servers, server1 with priority 1 and is leader, server2 with priority 2 and is follower. 
If server1 find server2's log catch up, server1 send TimeoutNowRequest to server2, and server2 become candidate and ask for vote, most case only server2 is candidate, so server2 can win the election directly. Compared to server1 stepDown to follower, and some server wait timeout and become candidate, TimeoutNowRequest can save the election time.
https://issues.apache.org/jira/browse/RATIS-1266
no need new ut.

RATIS-1266. Leader send StartLeaderElectionRequest to higher priority peer

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamDisabled.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamWithMock.java

See https://issues.apache.org/jira/browse/RATIS-1270

RATIS-1270. Set default primary DataStreamServer in RaftClient.Builder.

---

ratis-client/src/main/java/org/apache/ratis/client/api/DataStreamApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java

When create dataStreamApi in RaftClientImpl, we need to create DataStreamClient, so we need to  close DataStreamClient when close RaftClient. 
https://issues.apache.org/jira/browse/RATIS-1274
no need new ut

RATIS-1274. Close DataStreamClient when close RaftClient

---

ratis-examples/pom.xml
ratis-server/src/test/java/org/apache/ratis/server/impl/RetryCacheTestUtil.java

See https://issues.apache.org/jira/browse/RATIS-1275

RATIS-1275. Add slf4j-log4j12 runtime dependency to ratis-example.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-proto/src/main/proto/Raft.proto

Use ClientInvocationId as key instead of StreamMap.Key
https://issues.apache.org/jira/browse/RATIS-1276
no need new ut

RATIS-1276. Use ClientInvocationId as key instead of StreamMap.Key

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java

See https://issues.apache.org/jira/browse/RATIS-1278

RATIS-1278. Resource leak when decoding DataStreamReplyByteBuffer.

---

ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RoleInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedRequestReply.java

1. Implement **Preventing disruptions when a server rejoins the cluster** according to raft paper section 9.6.
2. In ozone, rejoin happen easily because the unstable network, for example sometimes one server's network is slow, it will try to trigger election, but which is unnecessary,  this can be prevented by this PR.
3. In this PR, before follower trigger leader election, it send pre-vote request to the other servers, if other server allow the follower to trigger leader election, it reply PASSED to the pre-vote request. If majority of the other servers allow the follower trigger leader election, the follower will trigger leader election.
4. The other server allow the follower to trigger leader election only when 1. the voters have not received heartbeats from a valid leader for at least …

RATIS-993. Support pre vote

---

ratis-common/src/main/java/org/apache/ratis/protocol/AdminAsynchronousProtocol.java
ratis-common/src/main/java/org/apache/ratis/protocol/AdminProtocol.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientAsynchronousProtocol.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientProtocol.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcAdminProtocolService.java
ratis-proto/src/main/proto/Grpc.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Discussed [here](https://lists.apache.org/thread.html/r51e13b73d6f3de8ffe2fe5db497535d816e3b1d5ff6f9256f954bf05%40%3Cdev.ratis.apache.org%3E) on dev@ mailing list.
Ratis GRPC has multiple GRPC services:
* RaftClientProtocolService
* RaftServerProtocolService
* AdminProtocolService
If all of them use the same port / netty server a malicious client/user 
may send admin/setConfiguration requests to the servers adding more 
groups or re-configuring existing ones.
For example if somebody implements any authentication/authorization on 
the StateMachine level, it can be ignored by adding more nodes and 
replicating the raw Ratis data.
I suggest improving the GrpcService.java and add only the configured 
services. With this approach mTLS can be turned on for admin and 
server2server communication …

RATIS-1286. Move setConfiguration and transferLeadership to admin GRPC calls

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java

Support skip the storagedir with multiple volumes which cause by bad disk
the problem statement:
when ratis created the storagedir on the bad disk,it would throw java.nio.file.AccessDeniedException
https://issues.apache.org/jira/browse/RATIS-1289
I started the Ozone server which the ratis was replaced by my local changed ratis, when the one of volumes thrown the IOException caused by bad disk ,this volume would be skipped

RATIS-1289. Support skip the storagedir with multiple volumes which cause by bad disk

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeer.java
ratis-common/src/main/java/org/apache/ratis/util/NetUtils.java
ratis-common/src/main/java/org/apache/ratis/util/ProtoUtils.java
ratis-common/src/test/java/org/apache/ratis/BaseTest.java
ratis-common/src/test/java/org/apache/ratis/util/TestNetUtils.java
ratis-examples/src/main/bin/common.sh
ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/cli/Server.java
ratis-examples/src/main/java/org/apache/ratis/examples/common/SubCommandBase.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Server.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcFactory.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolProxy.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientRpc.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerRpc.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java

Make it possible to expose client, server and admin services on different ports and with different TLS configuration.
https://issues.apache.org/jira/browse/RATIS-1290
* unit test coverage: updated `MiniRaftCluster` to use different ports
* examples: tested with arithmetic and filestore
* integrated with Ozone (locally for now)

RATIS-1290. Allow separate admin and client service

---

.asf.yaml

JIRA: https://issues.apache.org/jira/browse/RATIS-1297
As discussed in 
https://lists.apache.org/thread.html/r3f50ee6cf72e678eb53c3b47d48c34c4272000aba6abaaf879cc560d%40%3Cdev.ratis.apache.org%3E
the notifications can be forwarded to issues@ mailing list instead of dev@ to make it easier to follow the archive of dev@

RATIS-1297. Adjust Github nofications settings to use issues@ mailing list

---

layouts/custompage/downloads.html

RATIS-1299. Fix version 0.4.0 can not download

---

pom.xml

Upgrade `ratis-thirdparty` to recently released `0.6.0`, because `0.6.0-SNAPSHOT` [is no longer in the repo](https://repository.apache.org/content/repositories/snapshots/org/apache/ratis/ratis-thirdparty-misc/0.6.0-SNAPSHOT).
https://issues.apache.org/jira/browse/RATIS-1303
Compiled successfully:
https://github.com/adoroszlai/incubator-ratis/actions/runs/525010715

RATIS-1303. Upgrade Ratis Thirdparty to 0.6.0

---

pom.xml

Match `protobuf` and `grpc` versions from `ratis-thirdparty`.
https://issues.apache.org/jira/browse/RATIS-1303

RATIS-1303. Upgrade Ratis Thirdparty to 0.6.0 - addendum

---

ratis-common/src/main/java/org/apache/ratis/util/JvmPauseMonitor.java

1. Get rid of empty line in JvmPauseMonitor message.
2. Collapse message into a single line if `No GCs detected`.
ie. change this:
```
om_1 | 2021-01-29 14:59:37,955 [org.apache.ratis.util.JvmPauseMonitor$$Lambda$364/0x0000000840497c40@47272cd3] WARN util.JvmPauseMonitor: JvmPauseMonitor-om1: Detected pause in JVM or host machine (eg GC): pause of approximately 188209400ns
om_1 |
om_1 | No GCs detected
```
to this:
```
om_1 | 2021-01-29 16:47:26,546 [org.apache.ratis.util.JvmPauseMonitor$$Lambda$346/0x000000084047f040@6b9fdbc6] WARN util.JvmPauseMonitor: JvmPauseMonitor-om1: Detected pause in JVM or host machine (eg GC): pause of approximately 160745200ns. No GCs detected.
```
Also verified that pools are still printed to separate lines:
```
datanode_2  | 2021-01-29 17:03:17,098 …
```

RATIS-1302. JvmPauseMonitor logs multi-line message

---

ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java

JIRA: https://issues.apache.org/jira/browse/RATIS-1304
I found that Ozone prints out a lot of errors related to missing ratis-meta.conf, even if everything works well.
The related code path seems to be prepared to this case, but still prints out errors.

RATIS-1304. Do not print error if ratis log is not yet created

---

.github/workflows/post-commit.yml

Save time in CI by caching the local Maven repository (dependencies downloaded during the build).
https://issues.apache.org/jira/browse/RATIS-1307
2-7 minutes per job saved [with the patch](https://github.com/adoroszlai/incubator-ratis/actions/runs/539952212) compared to [previous successful run](https://github.com/apache/incubator-ratis/actions/runs/538951717).  (Unit check is not comparable, because I limited the run to a single test.)

RATIS-1307. Cache Maven dependencies in CI workflow

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

After RATIS-1241, a leader with no logs will send install snapshot notifications to followers on every heartbeat, regardless of whether or not they are behind. Fix this so that followers only get install snapshot notifications when they are actually behind.
[RATIS-1305](https://issues.apache.org/jira/browse/RATIS-1305)
Integration test added. The test still has an issue that is marked with a TODO. Leaving this PR as a draft while I fix this.

RATIS-1305. Leader stuck in infinite install snapshot cycle when logs have been purged

---

.github/workflows/post-commit.yml

Sonar no longer accepts reports created using Java 8.  This change upgrades to Java 11.  Check is split from unit to avoid affecting that one, and also to let them execute concurrently.
https://issues.apache.org/jira/browse/RATIS-1311
Tested in own fork with temporarily removed repo name comparison: https://github.com/adoroszlai/incubator-ratis/actions/runs/540063075
The check was skipped in subsequent run with repo name comparison restored: https://github.com/adoroszlai/incubator-ratis/runs/1838364223

RATIS-1311. Upgrade Java for Sonar check

---

ratis-assembly/pom.xml
ratis-assembly/src/main/assembly/bin.xml
ratis-assembly/src/main/assembly/src.xml

See https://issues.apache.org/jira/browse/RATIS-1315

RATIS-1315. Fix child module ratis-server-api does not exist.

---

.asf.yaml
dev-support/make_rc.sh
dev-support/vagrant/README.md
ratis-assembly/pom.xml
ratis-assembly/src/main/resources/README.md

Remove incubating
https://issues.apache.org/jira/browse/RATIS-1318
no need new ut.

RATIS-1318. Remove incubating

---

.github/workflows/post-commit.yml

In preparation for upcoming rename, let's execute _sonar_ check in both old and new repos.
https://issues.apache.org/jira/browse/RATIS-1320
Workflow syntax is validated, _sonar_ skipped in fork:
https://github.com/adoroszlai/incubator-ratis/runs/1941803835

RATIS-1320. Handle graduated repo in Github workflow

---

pom.xml

Fix the build error that occurs if Ratis directory is not a git repo (which would happen when building from release source artifact):
```
[INFO] Apache Ratis ....................................... FAILURE [  0.819 s]
...
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata (default) on project ratis: Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata failed.: NullPointerException -> [Help 1]
```
`revision` in `ratis-version.properties` is set to `Unknown` in this case.  This matches Ozone's properties for the same situation.
https://issues.apache.org/jira/browse/RATIS-1322
```
$ mvn -DskipTests clean verify; cat target/classes/ratis-version.properties
...
version=1.1.0-SNAPSHOT …
```

RATIS-1322. Cannot build from source without repo

---

LICENSE
NOTICE
ratis-assembly/src/main/resources/NOTICE

Change 2020 to 2021 in NOTICE
https://issues.apache.org/jira/browse/RATIS-1325
No need new ut

RATIS-1325. Change 2020 to 2021 in NOTICE

---

ratis-examples/src/main/java/org/apache/ratis/examples/common/SubCommandBase.java
ratis-examples/src/test/java/org/apache/ratis/examples/common/TestSubCommand.java

Hi, I am a ratis novice and found an array out of bounds issue during testing
I added a check on the data where I manipulated array subscripts and threw an expected exception and hint

RATIS-1330. fix ratis-examples SubCommand parsePeers method ArrayIndexOutOfBounds exception

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcTlsConfig.java

This Jira is to make truststore param a list of trusted CA certificate.
This will be needed for SCM HA.
https://issues.apache.org/jira/browse/RATIS-1331

RATIS-1331. Make GrpcTLS config truststore param list.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

A simple improvement to make make thread names more distinct, making troubleshooting easier. 
https://issues.apache.org/jira/browse/RATIS-1333
Confirmed with a VisualVM output that shows thread names.

RATIS-1333. Add explicit thread names for FollowerState and LeaderState threads.

---

content/community.md

The site still documents the project mailing lists in the .incubator sub-domain. Now that the project has graduated to TLP, we can update documentation of the mailing lists.
I also noticed that we did not have documentation for the -commits and -issues lists, so I added those.
Also, many of the `mailto:` links were not working correctly because of an extraneous space after the scheme.  I corrected all of those.
https://issues.apache.org/jira/browse/RATIS-1335
Built site locally and verified changes.

RATIS-1335. Update project mailing lists to use TLP domain.

---

layouts/custompage/downloads.html

The site still contains download links pointing to the distribution server at incubator sub-paths. Update these links to point to the new TLP location.
https://issues.apache.org/jira/browse/RATIS-1336
Built site locally and verified changes.
Note in the screenshot at the bottom that it no longer shows the "/incubator" sub-path for the download link.

RATIS-1336. Update download page to link to artifacts at TLP path.

---

content/post/0.2.0.md
content/post/0.3.0.md
content/post/0.4.0.md
content/post/0.5.0.md
content/post/1.0.0.md

The site has posts for release announcements with download links pointing to an old incubator location. Update these links to point to the new TLP location.
While working on this, I also noticed there were links to Ozone documentation at the old location under the hadoop sub-domain.  I updated all of those to use Ozone's TLP site: ozone.apache.org.
https://issues.apache.org/jira/browse/RATIS-1337
Built site locally and verified all links point to the correct locations.  (Note link target displayed at bottom of screenshot.)

RATIS-1337. Update release posts to use download links from TLP path.

---

ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

Always remove raft-meta.tmp to clean uncommitted changes.
https://issues.apache.org/jira/browse/RATIS-1332
unit tests.

RATIS-1332. Always remove raft-meta.tmp to clean uncommitted changes

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

Fixed missing leader info during installSnapshot.
https://issues.apache.org/jira/browse/RATIS-1326
Modified existing unit tests.

RATIS-1326. NotifyInstallSnapshot during SetConfiguration has leader info missing.

---

.github/workflows/post-commit.yml

#422 added matrix build for unit tests with 3 splits, with fail-fast behavior (if one split fails, other splits are cancelled).  @szetszwo [pointed out](https://github.com/apache/ratis/pull/422#issuecomment-801012525) that 
> better to always run all the tests since the overall running time is short. This is the reason that we moved the tests to the ratis-test module; see RATIS-399
I propose to run all tests for `push` builds, but keep fail-fast behavior for PRs.  The rationale is that PRs should be merged only after fully green build, so any failing test requires a new run.
https://issues.apache.org/jira/browse/RATIS-1341
Push build with failed _unit (grpc)_ check, but completed other _unit_ checks:
https://github.com/adoroszlai/incubator-ratis/actions/runs/660949453

RATIS-1341. Fail-fast tests only for PRs

---

dev-support/checks/sonar.sh
dev-support/ci/README.md
dev-support/make_rc.sh
dev-support/yetus-personality.sh
pom.xml
ratis-docs/themes/ratisdoc/layouts/partials/navbar.html
ratis-docs/themes/ratisdoc/layouts/partials/sidebar.html

Remove remaining references to "incubator" in repo links and build scripts.  Also correct a mismatch between dev and user mailing lists in pom.xml mail archive links.
https://issues.apache.org/jira/browse/RATIS-1323
No Ratis code changes, so no new tests.  Verified build locally.

RATIS-1323. Update repo links for TLP

---

pom.xml
ratis-assembly/pom.xml
ratis-client/pom.xml
ratis-common/pom.xml
ratis-docs/pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-grpc/pom.xml
ratis-hadoop/pom.xml
ratis-logservice/pom.xml
ratis-metrics/pom.xml
ratis-netty/pom.xml
ratis-proto/pom.xml
ratis-replicated-map/pom.xml
ratis-resource-bundle/pom.xml
ratis-server-api/pom.xml
ratis-server/pom.xml
ratis-test/pom.xml
ratis-tools/pom.xml

Since ratis 2.0.0 release is out. We should update the version to 2.1.0-SNAPSHOT.
https://issues.apache.org/jira/browse/RATIS-1354
existing UT

RATIS-1354. Update Ratis version to 2.1.0-SNAPSHOT.

---

pom.xml

Upgrade Ratis Third-party to latest 0.7.0 snapshot to pick up Netty fixes.
https://issues.apache.org/jira/browse/RATIS-1360
Only some apparently broken tests are failing in CI (same as on `master`):
https://github.com/adoroszlai/incubator-ratis/actions/runs/759205721
https://github.com/adoroszlai/incubator-ratis/actions/runs/762953972
https://github.com/adoroszlai/incubator-ratis/actions/runs/763381680

RATIS-1360. Upgrade Ratis Thirdparty to 0.7.0-a398b19-SNAPSHOT

---

.github/workflows/post-commit.yml

Few tests started failing recently in CI with errors like:
```
org.apache.ratis.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: /0.0.0.0:33307
```
without any code change.  [First failed](https://github.com/apache/ratis/runs/2329275686#step:5:4) on `master` for a simple [version number update](https://github.com/apache/ratis/commit/bd3f36bd324257d5898d59f203f7d19c1405a26c).
Also:
https://github.com/apache/ratis/runs/2379889361#step:5:4
https://github.com/apache/ratis/runs/2368524547?check_suite_focus=true#step:5:4
https://github.com/apache/ratis/runs/2379594469?check_suite_focus=true#step:5:4
They pass locally.
It seems likely that this is a side-effect of https://github.com/actions/virtual-environments/issues/3185.  So apply the suggested workaround. …

RATIS-1361. Connection errors in tests

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

Fix `org.apache.ratis.grpc.TestInstallSnapshotNotificationWithGrpc` testcase using following methods:
- Make sure that all clients has been created fully before taking a snapshot
- Add poll based wait to make sure that follower's have enough time to catch up
https://issues.apache.org/jira/browse/RATIS-1363
This is a fix for a automated test case, so no particularly special testing have been made. Fix has been tested manually using mvn test and Ratis CI.

Ratis 1363 Intermittent failure in TestInstallSnapshotNotificationWithGrpc

---

ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java

Fix `org.apache.ratis.grpc.TestRaftReconfigurationWithGrpc` testcase using following methods:
- Changed hard coded sleep time to poll based sleep to make sure that there is enough time on every machine
- Added poll based sleep before test case assertions to make sure, that everything is run properly before evaluation of the results.
https://issues.apache.org/jira/browse/RATIS-1362
This is a fix for a automated test case, so no particularly special testing have been made. Fix has been tested manually using mvn test and Ratis CI.

RATIS-1362. Intermittent NPE in RaftReconfigurationBaseTest.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java

For now, if there is no snapshot existed, the returned snapshotIndex is 0. 
It is not correctly, since the raft log starts from index 0 (BTW, in raft paper, the first valid log index is 1, but in ratis, it is 0), a snapshot taken at snapshotIndex 0 should contain the log entry 0. The snapshotIndex indicating an empty/fake snapshot should be -1.
```
diff --git a/ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java b/ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
index 728f7e9c..6307ca79 100644
--- a/ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
+++ b/ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
@@ -431,7 +431,7 @@ class ServerState implements Closeable {
long …
```

RATIS-1369. When there is no snapshot, the return snapshotIndex should be -1, not 0.

---

ratis-hadoop/src/main/java/org/apache/ratis/hadooprpc/client/CombinedClientProtocolServerSideTranslatorPB.java

There is future potential NPE issue in CombinedClientProtocolServerSideTranslatorPB class. Add error notification for developers to make sure that this issue is not triggered accidentally in the future.
https://issues.apache.org/jira/browse/RATIS-1365
This change should be very safe. It has only been tested using existing unit tests.

Ratis 1365 Add message for potential NPE in CombinedClientProtocolServerSideTranslatorPB

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

If server1 use only one client to transfer data to server2, there is bottleneck, so we should use multi-client.
https://issues.apache.org/jira/browse/RATIS-1371
No need new ut.

RATIS-1371. Support multi-client when transfer data between servers

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

We use StreamInfo#applyToRemotes to transfer data to to other server, and eventually we call OrderedStreamAsync#sendRequest. So StreamInfo#applyToRemotes finished after sending out request, but sometimes OrderedStreamAsync#sendRequest costs hundred millseconds. So we need to make StreamInfo#applyToRemotes async model, and also keep the order of request belongs to the same stream.
https://issues.apache.org/jira/browse/RATIS-1373
no need new ut

RATIS-1373. Use async model for StreamInfo#applyToRemotes

---

ratis-common/src/main/java/org/apache/ratis/util/IOUtils.java

This PR fixes problems related by Sonar Qube including two NPE issues. Bellow more comprehensive list of changes:
- Fix asIOException function NPE
- Reaorganize readFully function for better readability
- Change while-loop like for-loops to actual while-loops
- Fix readObject function NPE
https://issues.apache.org/jira/browse/RATIS-1364
Change has been tested using existing unit tests.

RATIS-1364 Fix Sonar Qube issues in IOUtils

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java

Handle bad storage dir due to disk failures.
This includes a small fix for the remove behavior of the directories list.
https://issues.apache.org/jira/browse/RATIS-1375
manual tests

RATIS-1375. Handle bad storage dir due to disk failures.

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java

1. Decrease outstanding-requests
2. Do not use request in lambda, because the request contains data, before lambda finish, request can not free memory.
https://issues.apache.org/jira/browse/RATIS-1376
no need new ut.

RATIS-1376. Improve the used memory

---

ratis-logservice/src/main/java/org/apache/ratis/logservice/server/MetaStateMachine.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java

Fix two Sonar Qube reported NPE issues in MetaStateMachine
- Fix NPE in applyTransactionSerial
- Fix NPE in query
https://issues.apache.org/jira/browse/RATIS-1366
Tested using existing unit tests.

RATIS-1366 Fix NPE issues in MetaStateMachine

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

Introduce a '.storage.space.reserved' for storage dir, it is used to prevent RaftServer from failing to take a final snapshot
when raftgroups are removed.
This threshold is only saved for final snapshots and should not be very large (e.g. 100MB),
and it is not for ratis log disks to be shared with other services, so maybe a simple global config is enough.
https://issues.apache.org/jira/browse/RATIS-1377
a new ut.

RATIS-1377. Ratis min free space for storage dirs.

---

ratis-metrics/src/main/java/org/apache/ratis/metrics/RatisMetrics.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/MetricRegistriesImpl.java

MetricsRegistriesImpl throws a warning when creating RatisMetricsRegistry without registering any reporters beforehand.
```
@Override
public RatisMetricRegistry create(MetricRegistryInfo info) {
return registries.put(info, () -> {
if (reporterRegistrations.isEmpty()) {
LOG.warn(
"First MetricRegistry has been created without registering reporters. You may need to call" +
" MetricRegistries.global().addReporterRegistration(...) before.");
StackTraceElement[] stackTrace = Thread.currentThread().getStackTrace();
for(StackTraceElement element : stackTrace) {
LOG.warn("     " + element.getClassName() + " - " + element.getMethodName() + " - " +
element.getLineNumber());
}
}
RatisMetricRegistry registry = factory.create(info);
reporterRegistrations.forEach(reg -> reg.accept(registry));
return …
```

RATIS-1381. Add default Reporter if there are no reporters when creating Metrics Registry

---

ratis-assembly/pom.xml

mvn build command is failing of assembly is turned on:
```
mvn clean install assembly:single -DskipTests=true  -Prelease
```
```
[INFO] --- exec-maven-plugin:1.6.0:exec (concat-NOTICE-files) @ ratis-assembly ---
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
```
Looks like to be sensitive to the new lines in the command.
https://issues.apache.org/jira/browse/RATIS-1385
Executed the same command with the patch and it worked well.

RATIS-1385. Project assembly fails on linux

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/client/MetricClientInterceptor.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/intercept/server/MetricServerInterceptor.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java

Make sure `Metric*Interceptor` unregisters its metrics from the global registry to avoid memory leak.
https://issues.apache.org/jira/browse/RATIS-1386
Built Ratis and Ozone with it.  Created objects in Ozone via S3 Gateway.  Verified that no `MetricRegistryInfo` and `RatisMetricRegistryImpl` instances are retained in S3 Gateway memory for each object.
https://github.com/adoroszlai/incubator-ratis/actions/runs/979350754

RATIS-1386. Some MetricsRegistry instances never unregistered

---

pom.xml
ratis-assembly/pom.xml
ratis-client/pom.xml
ratis-common/pom.xml
ratis-docs/pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-grpc/pom.xml
ratis-hadoop/pom.xml
ratis-logservice/pom.xml
ratis-metrics/pom.xml
ratis-netty/pom.xml
ratis-proto/pom.xml
ratis-replicated-map/pom.xml
ratis-resource-bundle/pom.xml
ratis-server-api/pom.xml
ratis-server/pom.xml
ratis-test/pom.xml
ratis-tools/pom.xml

Bump Ratis version number to `2.2.0-SNAPSHOT`.
https://issues.apache.org/jira/browse/RATIS-1393
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/1138370236

RATIS-1393. Update version number after 2.1.0 release

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/leader/FollowerInfo.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LeaderState.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java

When a peer is bootstrapping and joins the Ratis ring via SetConf request, the Leader adds the peer to the sender list and sends it either the append log entries or the snapshot or a notification to install snapshot via State Machine. The leader sends the snapshot only when some or all of the ratis logs have been purged. 
The snapshot is maintained by the State Machine and as such could contain information not present in the Ratis logs (for example Ozone's OzoneManager StateMachine maintains the snapshot as a DB file and it could contain information which cannot be constructed just using the Ratis logs - HDDS-5338). 
To avoid this scenario, this Jira proposes that whenever a new peer is bootstrapping, the leader should send an install snapshot request at least once. …

RATIS-1390. Bootstrapping Peer should always try to install a snapshot the first time.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java

See https://issues.apache.org/jira/browse/RATIS-1401

RATIS-1401. Failed to add a new group due to RaftServerProxy$ImplMap LOCK unavailable.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

```
//LeaderStateImpl.java
void notifySenders() {
senders.forEach(LogAppender::notifyLogAppender);
}
```
if raft , one slow log sender should not block others sender
https://issues.apache.org/jira/browse/RATIS-1399
no need

RATIS-1399. should notify all the log senders Asynchronously

---

layouts/custompage/downloads.html

* Fix dash in `gpg` commands
* Fix argument of `gpg --verify` commands (pass signature file, not the tarball)
https://issues.apache.org/jira/browse/RATIS-1395
```
hugo serve
open http://localhost:1313/downloads.html
```
Copied and ran command:
```
$ gpg --import KEYS
...
gpg: Total number processed: 6
...
```
Also copied, adapted and ran:
```
$ gpg --verify apache-ratis-2.1.0-src.tar.gz.asc
gpg: assuming signed data in 'apache-ratis-2.1.0-src.tar.gz'
gpg: Signature made Sat Jun 26 08:17:39 2021 CEST
gpg:                using RSA key 1CEF33FA61800117BDB2E0E0D51EA8F00EE79B28
gpg: Good signature from "Marton Elek (CODE SIGNING KEY) <elek@apache.org>" [unknown]
...
```

RATIS-1395. Cannot use commands from download page as is

---

layouts/custompage/downloads.html

Use date from download content page header, instead of hard-coded string.
https://issues.apache.org/jira/browse/RATIS-1394
Verified release date for both 2.0.0 and 2.1.0 in the Download page.
```
hugo serve
open http://localhost:1313/downloads.html
```

RATIS-1394. Wrong date for 2.1.0 release

---

.asf.yaml

Copy `.asf.yaml` file to the `asf-site` branch.  Based on the [doc](https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-Publishingabranchtoyourprojectwebsite) this file needs to be present in the branch being published.
https://issues.apache.org/jira/browse/RATIS-1404
Not tested, but hopefully we'll finally see the site being updated.

RATIS-1404. Copy .asf.yaml to asf-site branch

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

https://issues.apache.org/jira/browse/RATIS-1411

RATIS-1411.  Alleviate slow follower issue

---

layouts/custompage/downloads.html

See https://issues.apache.org/jira/browse/RATIS-1398

RATIS-1398. Wrong link for KEYS file.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

when notifying install snapshot, we should wait until the snapshot is installed successfully or exceptionally and then start appending subsequent log entries. 
in current implement , `wait` is used to achieve this purpose. but `notifyInstallSnapshotFromLeader` in state machine is call in a separate thread (completeFuture.supplyAsync), so `wait` does not take effect at this situation.
as a result , the client will get a reply with`installSnapshotResult.IN_PROGRESS` before the installation process is completed.
and then, then client will retry this call, because `setAttemptedToInstallSnapshot()` is not called when  received a reply with`installSnapshotResult.IN_PROGRESS`.
this will leading to too many useless rpc calls (shown in the attachment of this jira). …

RATIS-1402. do not send extra rpc calls to follower when the follower is still installing a snapshot

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

catch user statemachine notifyInstallSnapshotFromLeader exception
https://issues.apache.org/jira/browse/RATIS-1417
UT

RATIS-1417. catch user statemachine notifyInstallSnapshotFromLeader exception

---

pom.xml
ratis-assembly/pom.xml
ratis-assembly/src/main/assembly/ratis-shell.xml
ratis-shell/pom.xml
ratis-shell/src/main/bin/ratis
ratis-shell/src/main/conf/log4j.properties
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/RatisShell.java
ratis-shell/src/main/libexec/ratis-shell-config.sh

- How to build
```console
mvn clean install  assembly:single -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Denforcer.skip=true   -Djsse.enableSNIExtension=false  -Prelease -Papache-releas
```
- How to run
```
cd ratis/ratis-assembly/target/
tar -xzf apache-ratis-2.3.0-SNAPSHOT-bin.tar.gz
cd apache-ratis-2.3.0-SNAPSHOT
bin/ratis sh info -peers PEER0_HOST:PEER0_PORT,PEER1_HOST:PEER1_PORT,PEER2_HOST:PEER2_PORT
```

Support ratis-shell base framework with info command

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractRatisCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/ElectCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/InfoCommand.java

Add a elect sub command to trigger elect specific peer to be next leader.
https://issues.apache.org/jira/browse/RATIS-1428
mI did the following test within three alluxio ratis based masters.
```Console
➜  incubator-ratis git:(rs-elect) ✗ mvn clean install  assembly:single -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true  -Dfindbugs.skip=true -Denforcer.skip=true   -Djsse.enableSNIExtension=false  -Prelease -Papache-release 
➜  incubator-ratis git:(rs-elect) ✗ cd ratis-assembly/target 
➜  target git:(rs-elect) ✗ tar -xzf apache-ratis-2.3.0-SNAPSHOT-ratis-shell.tar.gz
➜  target git:(rs-elect) ✗ cd apache-ratis-2.3.0-SNAPSHOT 
➜  apache-ratis-2.3.0-SNAPSHOT git:(rs-elect) ✗ bin/ratis sh
Usage: ratis sh [generic options]
[elect -address <HOSTNAME:PORT> -peers …
```

RATIS-1428. Add ratis-shell elect command

---

ratis-common/src/main/java/org/apache/ratis/util/ConcurrentUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageMetadataFileImpl.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java

See https://issues.apache.org/jira/browse/RATIS-1419

RATIS-1419. Use cached thread pools in DataStreamManagement.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientRpc.java

See https://issues.apache.org/jira/browse/RATIS-1442

RATIS-1442. Typo: orderedWithTimeout should be unorderedWithTimeout in GrpcClientProtocolClient.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java

NettyClientStreamRpc exception handling：
1. When an exception occurs, clear the clientInvocation's send queue.
2. Write error logs when exceptions occur
https://issues.apache.org/jira/browse/RATIS-1445

RATIS-1445. NettyClientStreamRpc exception handling

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java

org.apache.ratis.netty.client.NettyClientStreamRpc#replies
```
private final ConcurrentMap<ClientInvocationId, Queue<CompletableFuture<DataStreamReply>>> replies =
new ConcurrentHashMap<>();
When all data for a streamID has been sent, is it necessary to clear the queue from the map？
```
I would implement a ExpiringMap. If you don't use it for a long time or Queue.size is 0, I delete it from the Map.
https://issues.apache.org/jira/browse/RATIS-1447

RATIS-1447. Cleanup NettyClientStreamRpc#replies empty queue

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/Command.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractRatisCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/GroupCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/GroupInfoCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/PeerCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/group/GroupInfoCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/group/GroupListCommand.java

Add a sub command to show the group information of a ratis server
https://issues.apache.org/jira/browse/RATIS-1436
```
[~/local/myproject/ratis] [group *] -> %  mvn clean install  assembly:single -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true  -Dfindbugs.skip=true -Denforcer.skip=true -Dgpg.skip=true   -Djsse.enableSNIExtension=false  -Prelease -Papache-release
[~/local/myproject/ratis] [group *]-> % cd ratis-assembly/target
[~/local/myproject/ratis/ratis-assembly/target] [group *] -> % tar -xzf apache-ratis-2.3.0-SNAPSHOT-ratis-shell.tar.gz
[~/local/myproject/ratis/ratis-assembly/target] [group *] -> % cd apache-ratis-2.3.0-SNAPSHOT
[~/local/myproject/ratis/ratis-assembly/target/apache-ratis-2.3.0-SNAPSHOT] [group *] -> % bin/ratis sh groupInfo -peers …
```

RATIS-1436.Add ratis-shell GroupInfo command

---

ratis-common/src/main/java/org/apache/ratis/retry/ExceptionDependentRetry.java

Provide more useful string output for `ExceptionDependentRetry`.  Example:
```
ExceptionDependentRetry(maxAttempts=3; defaultPolicy=RetryLimited(maxAttempts=5, sleepTime=10s); map={java.io.IOException->RetryLimited(maxAttempts=1, sleepTime=1s), org.apache.ratis.protocol.exceptions.TimeoutIOException->RetryLimited(maxAttempts=2, sleepTime=4s)})
```
https://issues.apache.org/jira/browse/RATIS-1458
Verified `toString` result by temporarily adding assertions about it in `TestExceptionDependentRetry`.
CI
https://github.com/adoroszlai/incubator-ratis/actions/runs/1535418055

RATIS-1458. Implement ExceptionDependentRetry#toString

---

ratis-assembly/pom.xml
ratis-assembly/src/main/assembly/shell-bin.xml
ratis-shell/src/main/libexec/ratis-shell-config.sh

Rename the assembly id from ratis-shell to shell to keep simple and meaningful.
https://issues.apache.org/jira/browse/RATIS-1460
```Console
➜  incubator-ratis git:(rename-ratis-shell) ✗ mvn clean install  assembly:single -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true  -Dfindbugs.skip=true -Denforcer.skip=true   -Djsse.enableSNIExtension=false  -Prelease -Papache-release
➜  incubator-ratis git:(rename-ratis-shell) cd ratis-assembly/target 
➜  target git:(rename-ratis-shell) tar -xzvf apache-ratis-2.3.0-SNAPSHOT-shell.tar.gz
x apache-ratis-2.3.0-SNAPSHOT/lib/shell/ratis-shell-2.3.0-SNAPSHOT-jar-with-dependencies.jar
x apache-ratis-2.3.0-SNAPSHOT/LICENSE
x apache-ratis-2.3.0-SNAPSHOT/NOTICE
x apache-ratis-2.3.0-SNAPSHOT/bin/
x apache-ratis-2.3.0-SNAPSHOT/bin/ratis
x …
```

RATIS-1460. Rename assembly id from ratis-shell to shell

---

ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java

Wait a bit for follower log to catch up to avoid intermittent failure in the test.
https://issues.apache.org/jira/browse/RATIS-531
Passed 100x:
https://github.com/adoroszlai/incubator-ratis/runs/4409665940
https://github.com/adoroszlai/incubator-ratis/runs/4410084395
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/1535984617

RATIS-531. TestServerRestartWithGrpc.runTestRestartCommitIndex is flaky

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/cli/Client.java

Hung occured during the filestore test, which has been described in Issues. The reason for this problem is that we need to use the first node in -- peers as the primary.
For example, if we pick the last node, then in the routetable he doesn't have the next node, so it can't write down. 
https://issues.apache.org/jira/browse/RATIS-1453

RATIS-1453. The client will hung when streaming writes.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java

Logging the exception does not provide useful information. There is also a redundant trace logging right after.
https://issues.apache.org/jira/browse/RATIS-1463

RATIS-1463 Fix verbose logging at INFO level

---

ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-test/src/test/java/org/apache/ratis/util/TestTimeDuration.java

RaftServer started failed when rpc timeout use different unit. 
The code analysis shows that the compareTo method of the TimeDuration class has a bug. 
When the unit of this is greater than that, that.compareTo(this) is called, but the return value is not set to a negative value.
https://issues.apache.org/jira/browse/RATIS-1462
unit tests.

RATIS-1462. RaftServer started failed when rpc timeout use different unit

---

pom.xml
ratis-experiments/pom.xml

See https://issues.apache.org/jira/browse/RATIS-1467

RATIS-1467. Remove unused log4j dependency from pom.xml.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/VoteContext.java

Candidate shall not start leader election in these cases in case of possible NPE caused by conf.getPeer().getPriority().
With this patch, the candidate will become a follower again when receiving the future appendEntries request.
Phenomenon:
The bootstrapped follower becomes the leader after the election timeout somehow, with an empty raft conf. Then in the process of ```yieldLeaderToHigherPriorityPeer```, NPE happens as (null).getPriority(). 
Setconfiguration action takes place at the end of appendEntriesAsync. If we make it possible to raise electiontimeout before this action, we can replay the NPE case.
```
1private void yieldLeaderToHigherPriorityPeer() {
2  if (!server.getInfo().isLeader()) {
3    return;
4  }
5  final RaftConfigurationImpl conf = server.getRaftConf();
6  int …
```

RATIS-1446. Avoid leader election for invalid conf

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/group/GroupListCommand.java

Add one new option peerId to shell command of group list
https://issues.apache.org/jira/browse/RATIS-1470
Test by command line manually

RATIS-1470. Add peerId option to group list

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

see: https://issues.apache.org/jira/browse/RATIS-1472

RATIS-1472. make use CachedThreadPool configurable.

---

ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-shell/pom.xml

See https://issues.apache.org/jira/browse/RATIS-1477

RATIS-1477. Exclude log4j JMSAppender.class in jar.

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SnapshotManagementTest.java

subtask of Support snapshot command: Make the min gap to take snapshot configurable
https://issues.apache.org/jira/browse/RATIS-1479
UT

RATIS-1479.Make the min gap to take snapshot configurable

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

1. ```shouldNotifyToInstallSnapshot``` should return ```the first available log's start term index```, but right now returns ```LastEntryTermIndex```. The possible corner case is when the log is purged and no newer log entries are appended.
2. Added of simulation of snapshot transmission delay in ```InstallSnapshotNotificationTests```
https://issues.apache.org/jira/browse/RATIS-1482
CI

RATIS-1482. fix shouldNotifyToInstallSnapshot to return the first avail term index

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java

The stream client sends a packet to the server reply and returns not success. Subsequent requests do not need to be sent to the server because it is a stream.
https://issues.apache.org/jira/browse/RATIS-1478

RATIS-1478 NettyClientStreamRpc error reply handling

---

ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java

`RaftServerImpl` creates a new `FollowerState` for each vote request received.  The old `FollowerState` may trigger change to candidate role even after it was shutdown by the server.  Both `RaftServerImpl#requestVote` and the change to candidate by `FollowerState` requires lock on `server` (`RaftServerImpl` object).  The order of events which triggers the problem:
* `RaftServerImpl` executing `requestVote` [with lock on itself](https://github.com/apache/ratis/blob/b57be797fe97c00abc0e3d7353d30e1b2961714d/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java#L1099)
* `FollowerState` [checks conditions, then waits for lock on `server`](https://github.com/apache/ratis/blob/b57be797fe97c00abc0e3d7353d30e1b2961714d/ratis-server/src/main/java/org/apache/ratis/server/impl/Fo …

RATIS-1490. Follower should not change to candidate if already stopped

---

ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamAsyncClusterTests.java

`testMultipleStreamsMultipleServersStepDownLeader` has 300 seconds timeout, but is frequently stopped after 100 seconds:
```
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 205.692 s <<< FAILURE! - in org.apache.ratis.datastream.TestNettyDataStreamChainTopologyWithGrpcCluster
testMultipleStreamsMultipleServersStepDownLeader(org.apache.ratis.datastream.TestNettyDataStreamChainTopologyWithGrpcCluster)  Time elapsed: 100.021 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 100 seconds
```
Timeout specified in `@Test(timeout = ...)` is limited by the `BaseTest#globalTimeout` rule, which defaults to 100 seconds.  We need to override `getGlobalTimeout()` to increase the rule's timeout.
`OutputStreamBaseTest` also has a test case which intends to …

RATIS-1491. TestNettyDataStreamChainTopologyWithGrpcCluster timed out after 100 seconds

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

When DataStreamManagement#read an exception occurs, release ByteBuf
https://issues.apache.org/jira/browse/RATIS-1495

RATIS-1495. When DataStreamManagement#read an exception occurs, release ByteBuf

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/SnapshotManagementImpl.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SnapshotManagementTest.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/snapshot/TakeSnapshotCommand.java

subtask of Support snapshot command: Take snapshot on specific ratis server
https://issues.apache.org/jira/browse/RATIS-1498
UT

RATIS-1498. Take snapshot on specific ratis server

---

ratis-common/src/main/java/org/apache/ratis/util/ConcurrentUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcClientProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-server/src/test/java/org/apache/ratis/OutputStreamBaseTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestGrpcOutputStream.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftOutputStreamWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestWatchRequestWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1497

RATIS-1497. Avoid using ForkJoinPool.commonPool().

---

ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-shell/pom.xml

See https://issues.apache.org/jira/browse/RATIS-1501

RATIS-1501. Exclude log4j JMSSink, JDBCAppender, and Chainsaw from the generated jar.

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractParentCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/AbstractRatisCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/ElectionCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/GroupCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/LeaderElectionCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/PeerCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/command/SnapshotCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/PauseCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/ResumeCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/TransferCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/AddCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/RemoveCommand.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/SetPriorityCommand.java

Add a sub command to pause and resume leader election on the specific peer.
https://issues.apache.org/jira/browse/RATIS-1526
UT

RATIS-1526. Add ratis-shell pause&resume leader election command

---

ratis-client/src/main/java/org/apache/ratis/client/api/AdminApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AdminImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/SetConfigurationRequest.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java

Sub task to support listener: Remove old PeerConfiguration API and change SetConfiguration
https://issues.apache.org/jira/browse/RATIS-1540
UT

RATIS-1540. Support listeners in AdminApi, SetConfigurationRequest and proto.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java

for now, the following is used to check whether a snapshot should be taken
`return state == State.RUNNING && getLastAppliedIndex() - snapshotIndex.get() >= autoSnapshotThreshold; `
but `getLastAppliedIndex` is the index recorded by stateMachineUpdater, not state machine itself. in some other case (for example, om), the lastAppliedIndex of state machine will not be updated immediately after `applyTransaction` is called . in om , lastAppliedIndex will be updated until the ready queue of double buffer is flushed.
so here `stateMachineUpdater#getLastAppliedIndex()` does not always equal to `stateMachine#lastAppliedIndex`
https://issues.apache.org/jira/browse/RATIS-1548
current UT

RATIS-1548. use stateMachine#lastAppliedIndex instead of stateMachinUpdater#lastAppliedIndex when checking snapshot should be taken

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/BufferedWriteChannel.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogOutputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

We previously tried to reduce disk IO by introducing a minimum interval between flushes, the relevant pr is here: https://github.com/apache/ratis/pull/611
However, after subsequent tests, we found that **the pr #611 has a bug**, make the raft performance degraded,  because `flushIfNecessary()` function does more operations than just flushing the stream.
Since we enforced the minimum time for each flush, **the raft log to can't be committed in flush intervals, which reduces the performance of raft.**
So we want to separate `out.flush()`  from `flushIfNecessary()` and execute it asynchronously, so that the process of writing to disk will not block the operation of other threads
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1545
We use the ozone freon ockg tool to detect the …

RATIS-1545. RaftLogOutputStream support async flush.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

subtask to support listener: Support Listener in RaftServerImpl
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1558?filter=reportedbyme
UT

RATIS-1558. Support Listener in RaftServerImpl

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java

The  state upgrade  ```state.updateInstalledSnapshotIndex(reply);
state.reloadStateMachine(reply.getIndex());
installedSnapshotIndex.set(reply.getIndex()); ```
in ```notifyStateMachineToInstallSnapshot``` should be synchronized in main thread.
Currently it is executed in whenComplete stage after ```stateMachine.followerEvent().notifyInstallSnapshotFromLeader```, which could lead to two inappropriate logic. 
1. The following check in the main thread ``` if (latestInstalledSnapshotIndex > 0)``` will be executed before state upgrade, which cause the raft server could not respond SNAPSHOT_INSTALLED in one request.
2. Once the actual upgrade of snapshot index and commit index takes place through the above state upgrade, the leader receives the inconsistency reply with the new index and then …

RATIS-1481. make state upgradate in notifyStateMachineToInstallSnapshot serialized

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java

See https://issues.apache.org/jira/browse/RATIS-1563

RATIS-1563: Better error message when stateMachine.data().read(entry) fails.

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java

When notifying follower's slowness, if the leader knows who is slow using StateMachine, then it will help users to handle it.
https://issues.apache.org/jira/browse/RATIS-1574

RATIS-1574. Add follower information to LeaderEventApi.notifyFollowerSlowness(..)

---

pom.xml

Upgrade Ratis Thirdparty to 1.0.0, which has the following (non-test) changes:
* RATIS-1515. Upgrade gRPC to 1.44.0, Netty to 4.1.74
* RATIS-1514. Bundle specific netty artifacts instead of netty-all
* RATIS-1507. Clean up the vulnerabilities from dependencies.
* RATIS-1468. Remove unused log4j dependency from thirdparty pom.xml
* RATIS-1443. Shade all Netty Native libraries
https://issues.apache.org/jira/browse/RATIS-1572
https://github.com/adoroszlai/incubator-ratis/actions/runs/2276551769

RATIS-1572. Upgrade Ratis Thirdparty to 1.0.0

---

.gitignore
ratis-assembly/src/main/assembly/src.xml
ratis-docs/pom.xml

Exclude Hugo's lock file from source tarball, and let Rat and Git ignore it.
https://issues.apache.org/jira/browse/RATIS-1575
```
$ mvn -DskipTests -Prelease -Papache-release clean package assembly:single 
...
[INFO] BUILD SUCCESS
$ ls -s ratis-docs/.hugo_build.lock
0 ratis-docs/.hugo_build.lock
$ dev-support/checks/rat.sh
...
[INFO] BUILD SUCCESS
$ tar tzvf ratis-assembly/target/apache-ratis-*-src.tar.gz| grep hugo | wc -l
0
$ git status
On branch RATIS-1575
nothing to commit, working tree clean
```

RATIS-1575. Handle hugo lock file

---

ratis-assembly/src/main/assembly/src.xml

Include `ratis-shell` submodule in source tarball to prevent build failure when building Ratis after downloading source tarball.
https://issues.apache.org/jira/browse/RATIS-1576
```
$ mvn -DskipTests -Prelease -Papache-release clean package assembly:single
...
[INFO] BUILD SUCCESS
$ tar -C ~/tmp -xzf ratis-assembly/target/apache-ratis-2.3.0-SNAPSHOT-src.tar.gz
$ cd ~/tmp/apache-ratis-2.3.0-SNAPSHOT
$ mvn -DskipTests clean package
...
[INFO] BUILD SUCCESS
```

RATIS-1576. Add ratis-shell to source assembly

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java

After 7167fafe Ozone SCM HA fails to start due to the following error in follower:
```
[grpc-default-executor-0] INFO  impl.SnapshotInstallationHandler (SnapshotInstallationHandler.java:installSnapshot(79)) - 2d9f16d2-1d71-4978-9546-00aa402e881d@group-F84A6C219907: receive installSnapshot: edb17d6c-0f2e-4b73-aa2b-eb8fdf376958->2d9f16d2-1d71-4978-9546-00aa402e881d#0-t2,notify:(t:1, i:0)
[grpc-default-executor-0] INFO  server.RaftServer$Division (ServerState.java:setLeader(287)) - 2d9f16d2-1d71-4978-9546-00aa402e881d@group-F84A6C219907: change Leader from null to edb17d6c-0f2e-4b73-aa2b-eb8fdf376958 at term 2 for installSnapshot, leader elected after 488ms
[grpc-default-executor-0] INFO  impl.SnapshotInstallationHandler (SnapshotInstallationHandler.java:notifyStateMachineToInstallSnapshot(21 …
```

RATIS-1577. Install snapshot failure

---

.github/workflows/post-commit.yml
dev-support/checks/build.sh
ratis-assembly/src/main/assembly/src.xml

CI should ensure that source tarball contents can be compiled (see RATIS-1576 for example where it was broken).
This PR includes the following changes:
* _build_ check produces tarballs and stores the one with sources for other checks to consume
* _compile_ check builds from the source tarball instead of git repo
* source tarball sets `+x` permission on `dev-support` scripts
https://issues.apache.org/jira/browse/RATIS-1579
https://github.com/adoroszlai/incubator-ratis/actions/runs/2296722458

RATIS-1579. Verify build from source release tarball in CI

---

ratis-docs/content/cli.md

see https://issues.apache.org/jira/browse/RATIS-1581

RATIS-1581. Add ratis-shell compile and command document

---

layouts/custompage/downloads.html

https://www.apache.org/info/verification.html#specify_both
&ndash; is not the same as --

Second param is needed for gpg --verify

---

ratis-proto/src/main/proto/Grpc.proto
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLeaderInstallSnapshot.java

* Fix snapshot multiple-chunk bug. Currently, when leader install a snapshot(multiple chunks) to a newly joined follower, leader will send multiple InstallSnapshot RPCs. However, each RPC will create a tmp dir with Random UUID, place the chunk in this tmp dir, and only renames the last tmp dir to sm-dir. In this PR, I propose to create tmp dir using request.uuid(), which remains unchanged among multiple RPCs.
* Fix Grpc Stream errors. Currently In grpc.proto, InstallSnapshot is declaimed as client-end streaming rpc, but it is actual bi-directional streaming rpc. In this PR, I addded stream to InstallSnapshot proto so that it becomes bi-directional.
* Support snapshot file hierarchy. Currently all files of a snapshot will be placed in statemachine dir and file hierarchy is flattened. In …

RATIS-1587. Fix snapshot multi-chunk bug & support snapshot hierarchy

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

Currently, the notify install snapshot would not inform when the whole progress is done
From the Ozone side, the statemachine's notifyInstallSnapshotFromLeader is a single request and process. It is fine before we find out that the installation of the snapshot could get stuck due to the whole RocksDB replacement each time (the leader could have purged the raft log during transferring the snapshot and thus triggers another snapshot installation when the previous install request is done). To solve this, we come up with the incremental snapshot idea, which could transfer the incremental part of RocksDB in the next install request, and needs to preserve the checkpoints.  The incremental snapshot needs to compare the checkpoints and hence the checkpoints cannot be deleted after the first …

RATIS-1582. Add notify install snapshot finished event to inform the

---

ratis-assembly/src/main/assembly/bin.xml
ratis-docs/content/cli.md

see https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1589?filter=allissues

RATIS-1589. Get ratis-shell resource from bin tarball

---

ratis-server-api/src/main/java/org/apache/ratis/server/storage/RaftStorage.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/StorageImplUtils.java
ratis-server/src/test/java/org/apache/ratis/server/storage/RaftStorageTestUtils.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

see https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1588

RATIS-1588. Add a builder of RaftStorageImpl

---

ratis-client/src/main/java/org/apache/ratis/client/AsyncRpcApi.java
ratis-client/src/main/java/org/apache/ratis/client/DataStreamClient.java
ratis-client/src/main/java/org/apache/ratis/client/RaftClient.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientImplUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

See https://issues.apache.org/jira/browse/RATIS-1569

RATIS-1569. Move the asyncRpcApi.sendForward(..) call to the client side

---

ratis-server/src/main/java/org/apache/ratis/server/storage/FileChunkReader.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java

Currently in InstallSnapshot, statemachine has to pre-compute each file's md5 digest and provide it in `FileInfo`. When snapshot file is large, this computing is time-consuming and may cause leader timeout. 
In this PR I propose to move the computing task along within the InstallSnapshot stream process. That is, for each SnapshotChunk,  we can read the chunk & compute its moving MD5 digest in the same time. This can enable us to read file & compute file MD5 in one sequential scan and thus save IO costs.
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1597
Current application code won't be affected by this PR. If a digest is given in `FileInfo`, we still use the given digest. However, when digest is not provided (null) in `FileInfo`, the digest will be calculated by the above …

RATIS-1597. Compute MD5 during snapshot streaming

---

ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

See https://issues.apache.org/jira/browse/RATIS-1602

RATIS-1602. Add a ProxiesPool inner class in NettyServerStreamRpc.

---

ratis-client/src/main/java/org/apache/ratis/client/api/AdminApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/AdminImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/SetConfigurationRequest.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java

see https://issues.apache.org/jira/browse/RATIS-1594

RATIS-1594. Support ADD mode to SetConfiguration

---

NOTICE
pom.xml
ratis-assembly/src/main/resources/NOTICE

Upgrade Ratis Thirdparty to 1.0.1, which has the following (non-test) changes:
RATIS-1585. Bump gson to 2.8.9 
RATIS-1591. Bump netty to 4.1.77
RATIS-1595. Shade dropwizard 4.x in ratis-thirdparty
RATIS-1601. Use the shaded dropwizard metrics and remove the dependency
https://issues.apache.org/jira/browse/RATIS-1614
https://issues.apache.org/jira/browse/RATIS-1601
https://github.com/codings-dan/incubator-ratis/actions/runs/2616031344

RATIS-1614. Upgrade Ratis Thirdparty to 1.0.1

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java

See https://issues.apache.org/jira/browse/RATIS-1610

RATIS-1610. NettyRpcService should not bind the port in the constructor.

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

Server should support listening on a specified network address
[RATIS-1615](https://issues.apache.org/jira/browse/RATIS-1615)

RATIS-1615. Server should support listening on a specified network address

---

ratis-server/src/test/java/org/apache/ratis/server/metrics/TestLeaderElectionMetrics.java

Changes an assertion in TestLeaderElectionMetrics.testOnLeaderElectionCompletion() to check that leaderElectionLatency >= 0 (was leaderElectionLatency > 0).
https://issues.apache.org/jira/browse/RATIS-1621
I ran TestLeaderElectionMetrics.testOnLeaderElectionCompletion() a couple of thousand times (no failures).

RATIS-1621. Fix intermittent failure in TestLeaderElectionMetrics

---

ratis-shell/pom.xml

See https://issues.apache.org/jira/browse/RATIS-1623

RATIS-1623. Remove guava.version from ratis-shell/pom.xml.

---

ratis-server/src/main/java/org/apache/ratis/server/leader/InstallSnapshotRequests.java

in method : org.apache.ratis.server.leader.InstallSnapshotRequests#newInstallSnapshotRequest; 
it is unnecessary to compute repeatedly the total size of snapshot .
RATIS-1627. InstallSnapshotRequests add properties : totalSize
https://issues.apache.org/jira/browse/RATIS-1627

RATIS-1627. InstallSnapshotRequests add properties : totalSize

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java

Avoid using 0 delay for slow or dead followers when new entries comes.
[RATIS-1622: High cpu usage of LogAppenderDaemon](https://issues.apache.org/jira/browse/RATIS-1622)
Tested manually by using the following steps:
* Start a cluster of 5 nodes
* shutdown node 5 and 5
* make some change to get new log entry
* monitor the CPU usage of the leader node.
The CPU load is significantly reduced from 90% to 10%(in Docker environment, and cpus is limited to 1 for each node).
However, some unit tests fails locally. I'll open this to see if any tests will fail in CI.

RATIS-1622. Fix high CPU load when some followers are down

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

Currently,  the leader does not know who finished the snapshot and called the 
notifySnapshotInstalled event. To make it clear, the leader statemachine should also get the peer info.
https://issues.apache.org/jira/browse/RATIS-1631
CI

RATIS-1631. Add Raftpeer Info for NotifySnapshotInstalled

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogInputStream.java

In SegmentedRaftLogInputStream#init, the SegmentedRaftLogReader instance is not correctly closed if the log is corrupted. The LogSegment#readSegmentFile function will try to delete empty segment, however it may fail on Windows because previously it's not closed. 
https://issues.apache.org/jira/browse/RATIS-1634
Already coverd in unit test ServerRestartTests#testRestartWithCorruptedLogHeader.

RATIS-1634. Close SegmentedRaftLogReader if init failed.

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java

When run the rpc server, always output redundant and wrong log, like admin.port、client.port.
```
2022-07-22 09:24:21 INFO  RaftServer:46 - raft.rpc.type = GRPC (default)
2022-07-22 09:24:21 INFO  GrpcFactory:48 - PERFORMANCE WARNING: useCacheForAllThreads is true that may cause Netty to create a lot garbage objects and, as a result, trigger GC.
It is recommended to disable useCacheForAllThreads by setting -Dorg.apache.ratis.thirdparty.io.netty.allocator.useCacheForAllThreads=false in command line.
2022-07-22 09:24:21 INFO  GrpcConfigKeys:46 - raft.grpc.admin.port = -1 (default)
2022-07-22 09:24:21 INFO  GrpcConfigKeys:46 - raft.grpc.server.port = 10024 (custom)
2022-07-22 09:24:21 INFO  GrpcConfigKeys:46 - raft.grpc.client.port = -1 (default)
2022-07-22 09:24:21 INFO  GrpcConfigKeys:46 - …
```

RATIS-1633. Improve the grpc config output log information.

---

ratis-examples/src/test/java/org/apache/ratis/examples/ParameterizedBaseTest.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-netty/src/test/java/org/apache/ratis/netty/MiniRaftClusterWithNetty.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/MiniRaftClusterWithSimulatedRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/MiniRaftClusterWithRpcTypeGrpcAndDataStreamTypeNetty.java
ratis-test/src/test/java/org/apache/ratis/datastream/MiniRaftClusterWithRpcTypeNettyAndDataStreamTypeNetty.java

see https://issues.apache.org/jira/browse/RATIS-1635

RATIS-1635. Support listener in MiniRaftCluster

---

ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SnapshotManagementTest.java

see https://issues.apache.org/jira/browse/RATIS-1640

RATIS-1640. Add unit-test of listener related to setConfiguration and takeSnapshot

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java

Fix OrderedStreamAsync#scheduleWithTimeout method to report a correct timeout value via TimeoutIOException
https://issues.apache.org/jira/browse/RATIS-1655
manual tests

RATIS-1655. Fix OrderedStreamAsync#scheduleWithTimeout to report a correct timeout value

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/util/TimeoutExecutor.java
ratis-common/src/main/java/org/apache/ratis/util/TimeoutScheduler.java
ratis-common/src/main/java/org/apache/ratis/util/TimeoutTimer.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingStepDown.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotManagementRequestHandler.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java
ratis-server/src/main/java/org/apache/ratis/server/impl/WatchRequests.java
ratis-test/src/test/java/org/apache/ratis/util/TestTimeoutScheduler.java

See https://issues.apache.org/jira/browse/RATIS-1603

RATIS-1603. TimeoutScheduler can have a huge amount of threads and cause OOM.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java

`RaftServerImpl#appendEntriesAsync` is still using the common pool here:
https://github.com/apache/ratis/blob/3db8f9eac82efedd51322a0d213300c9a0940bb6/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java#L1416-L1417
Preceding steps in `appendEntriesAsync` are already running on `serverExecutor`, so I think there is no need to further defer this step.
https://issues.apache.org/jira/browse/RATIS-1656
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/2789205160

RATIS-1656. Leftover usage of ForkJoinPool.commonPool() in RaftServerImpl

---

ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLogSequentialOps.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLogTest.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestCacheEviction.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

https://github.com/apache/ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java#L1280
here a TODO comment, i do not know is it worth to implement it ? 
i have finished it  no matter how.
https://issues.apache.org/jira/browse/RATIS-1665
ci  build

RATIS-1665. RaftLog avoid converting list

---

.gitignore
pom.xml
ratis-assembly/src/main/assembly/bin.xml
ratis-assembly/src/main/assembly/examples-bin.xml
ratis-assembly/src/main/assembly/shell-bin.xml
ratis-examples/pom.xml
ratis-shell/pom.xml
ratis-shell/src/main/libexec/ratis-shell-config.sh

The shell jar in the lib folder, while other jars in jars folder, we can put them together.
```
[dcadmin@dcadmin-work ratis]$ ll -a ratis-assembly/target/apache-ratis-3.0.0-SNAPSHOT
total 36
drwxr-xr-x 11 dcadmin dcadmin   178 Jan 22  2020 .
drwxrwxr-x  7 dcadmin dcadmin   264 Aug  8 11:31 ..
drwxr-xr-x  2 dcadmin dcadmin    19 Jan 22  2020 bin
drwxr-xr-x  2 dcadmin dcadmin    30 Jan 22  2020 conf
drwxr-xr-x  2 dcadmin dcadmin  4096 Jan 22  2020 jars
drwxr-xr-x  3 dcadmin dcadmin    19 Jan 22  2020 lib
drwxr-xr-x  2 dcadmin dcadmin    35 Jan 22  2020 libexec
-rw-r--r--  1 dcadmin dcadmin 13394 Jan 22  2020 LICENSE
-rw-r--r--  1 dcadmin dcadmin  5246 Jan 22  2020 NOTICE
-rw-r--r--  1 dcadmin dcadmin  1201 Jan 22  2020 README.md
drwxr-xr-x 21 dcadmin dcadmin  4096 Jan 22  2020 src 
``` …

RATIS-1669. Combine shell lib folder and root jars folder

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftGroup.java
ratis-test/src/test/java/org/apache/ratis/protocol/TestRaftGroup.java

When run ratis example, the script still runs normally while the peerids are same.
```
BIN=ratis-examples/src/main/bin
PEERS=n0:127.0.0.1:6000,n0:127.0.0.1:6001,n0:127.0.0.1:6002
```
After patch
```
[dcadmin@dcadmin-work ratis]$     PEERS=n0:127.0.0.1:6000,n0:127.0.0.1:6001,n0:127.0.0.1:6002
[dcadmin@dcadmin-work ratis]$ ID=n0; ${BIN}/server.sh arithmetic server --id ${ID} --storage /tmp/ratis/test/${ID} --peers ${PEERS}
Found /work/projects/opensource/raft/ratis/ratis-examples/target/ratis-examples-3.0.0-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalStateException: PeerId n0 has already appeared in this group.
at org.apache.ratis.util.Preconditions.assertTrue(Preconditions.java:72)
at org.apache.ratis.protocol.RaftGroup.lambda$new$2(RaftGroup.java:66)
at …
```

RATIS-1673. Verify duplicate peerid when init raft group

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java

See https://issues.apache.org/jira/browse/RATIS-1642
(Will also try removing the SuppressFBWarnings tags.)

RATIS-1642. Specify the thread-safety requirement in StateMachine.

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java

`TestLeaderInstallSnapshot` leaves untracked files in `ratis-test/snapshot` directory.
```
$ mvn clean test -DfailIfNoTests=false -Dtest=TestLeaderInstallSnapshot
...
$ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
ratis-test/snapshot/
nothing added to commit but untracked files present (use "git add" to track)
$ find ratis-test/snapshot | sort
ratis-test/snapshot
ratis-test/snapshot/1.bin
ratis-test/snapshot/sub
ratis-test/snapshot/sub/2.bin
```
The root cause is that `getSMdir()` returns `null` until storage is initialized.
https://issues.apache.org/jira/browse/RATIS-1680
```
$ mvn clean test -DfailIfNoTests=false -Dtest=TestLeaderInstallSnapshot
...
$ git status
On branch …
```

RATIS-1680. TestLeaderInstallSnapshot creates untracked files

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java

ElectionTimeout cannot be set too small, which will lead to frequent leader change when full GC occurs. However, longer ElectionTimeout will cause longer unavailable times during start up, which is annoying.
In this PR I propose to separate first election timeout and normal election timeout. This can enable Raft Group elect a leader quickly during start up while avoid frequent leader change during normal operations.
https://issues.apache.org/jira/browse/RATIS-1638
unit tests

RATIS-1638. Separate first election timeout

---

dev-support/make_rc.sh

see https://issues.apache.org/jira/browse/RATIS-1682

RATIS-1682. Fix ratis make_rc.sh prepare-bin phase

---

ratis-common/src/main/java/org/apache/ratis/util/FileUtils.java

Use StandardCopyOption.ATOMIC_MOVE to enhance robustness.
https://issues.apache.org/jira/browse/RATIS-1681
unit tests

RATIS-1681. Use atomic_move to enhance robustness

---

pom.xml

Upgrade Ratis Thirdparty to 1.0.2, which has the following (non-test) changes:
RATIS-1600. Add protobuf-java-util
RATIS-1632. Upgrade gRPC to 1.48.1
RATIS-1664. Exclude org.slf4j.* in ratis-thirdparty-misc
RATIS-1679. Shade io.perfmark:perfmark-api in ratis-thirdparty
https://issues.apache.org/jira/browse/RATIS-1684
https://github.com/codings-dan/incubator-ratis/actions/runs/2910213305

RATIS-1684. Upgrade Ratis Thirdparty to 1.0.2

---

ratis-client/src/main/java/org/apache/ratis/client/api/GroupManagementApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/GroupManagementImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/GroupManagementRequest.java
ratis-common/src/main/java/org/apache/ratis/util/MemoizedCheckedSupplier.java
ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-common/src/main/java/org/apache/ratis/util/SizeInBytes.java
ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServer.java
ratis-server-api/src/main/java/org/apache/ratis/server/storage/RaftStorage.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/main/java/org/apache/ratis/server/storage/StorageImplUtils.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestStorageImplUtils.java

See https://issues.apache.org/jira/browse/RATIS-1677

RATIS-1677. Do not auto format RaftStorage in RECOVER.

---

.github/workflows/post-commit.yml

RATIS-1313 added matrix build with fail-fast behavior, which RATIS-1341 restricted to PRs only.  Due to a Github improvement committers can now choose to re-run only failed tasks.  Thus cancelling parallel runs no longer provides the most cost-effective way to get a clean run.
https://issues.apache.org/jira/browse/RATIS-1690
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/2933403333

RATIS-1690. Disable fail-fast for unit check

---

ratis-common/src/main/java/org/apache/ratis/protocol/SetConfigurationRequest.java

Changes made to SetConfigurationRequest for RATIS-1593 and RATIS-1594 are not backwards compatible.  Downstream component (e.g. Ozone) needs code change to be able to construct a SetConfigurationRequest after upgrade.  I think we should support the old interface for 2.4.0.
https://issues.apache.org/jira/browse/RATIS-1687
Built Ratis, compiled Ozone with it.
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/2929301261

RATIS-1687. Make SetConfigurationRequest backwards compatible

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java

Add a interface in `LogAppender` to enable trigger snapshot manually and immediately. 
https://issues.apache.org/jira/browse/RATIS-1671
unit tests

RATIS-1671. Add manual trigger snapshot

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

Move shutdown of `RaftServerProxy#executor` inside the block which is executed after lifecycle check.  This prevents subsequent callers (notably `StateMachineUpdater`) from blocking until the executor is shutdown.
https://issues.apache.org/jira/browse/RATIS-1691
Ran all Ratis unit tests locally.
Ran Ozone integration tests with 2.4.0-rc0 + RATIS-1687 + this change.  Most tests passed (most importantly HA tests that timed out previously).
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/2935727046

RATIS-1691. Potential deadlock in server shutdown

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ReadRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java

Add the heartbeat broadcast mechanism in LeaderState. 
When a leader is requested for current readIndex, it should first confirm its authority by broadcasting heartbeats and receiving majority acknowledgements. If the leadership is confirmed, the readIndex can be safely returned.
In this PR I propose to add the broadcast mechanism and use it to implement readIndex request.
https://issues.apache.org/jira/browse/RATIS-1643
this patch should be tested when Read request using ReadIndex Option is implemented.

RATIS-1643. Add heartbeat broadcast mechanism for leader readIndex

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/GrpcServerMetrics.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/server/TestGrpcServerMetrics.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/MetricRegistryInfo.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/MetricsReporting.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/RatisMetricRegistry.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/RatisMetricRegistryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetricsBase.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestLogAppenderMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRetryCacheMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/metrics/ServerMetricsTestUtils.java
ratis-server/src/test/java/org/apache/ratis/server/metrics/TestLeaderElectionMetrics.java
ratis-test/src/test/java/org/apache/ratis/TestRaftServerSlownessDetection.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

See https://issues.apache.org/jira/browse/RATIS-1689
This is a retry of #724 .

RATIS-1689. Remove the use of the thirdparty Gauge.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/GrpcServerMetrics.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/server/TestGrpcServerMetrics.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/LongCounter.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/RatisMetricRegistry.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/RatisMetricRegistryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/TestRatisServerMetricsBase.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftSnapshotWithGrpc.java

See https://issues.apache.org/jira/browse/RATIS-1692

RATIS-1692. Remove the use of the thirdparty Counter.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java

See https://issues.apache.org/jira/browse/RATIS-1697

RATIS-1697. StateMachineUpdater.getStateMachineLastAppliedIndex should handle null.

---

ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/ReadException.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LeaderState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ReadRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestReadOnlyRequestsWithGrpc.java

Implement linearizable read-only requests in leader, according to Raft Thesis section 6.4.
1. Obtain `readIndex` by broadcasting heartbeats and receiving majority acks.
2. Wait statemachine to advance at least as far as `readIndex`
3. Query statemachine now and we can get a linearizable result.
https://issues.apache.org/jira/browse/RATIS-1696
New unit tests in ReadOnlyTests, including basic / parallel client / timeout scenarios.

RATIS-1696. Support linearizable read-only requests in leader

---

ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

see https://issues.apache.org/jira/browse/RATIS-1698

RATIS-1698. Add unit-test of listener related to leaderElection

---

ratis-client/src/main/java/org/apache/ratis/client/api/BlockingApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/BlockingImpl.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/ReadException.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-proto/src/main/proto/Grpc.proto
ratis-proto/src/main/proto/Raft.proto
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerRpc.java
ratis-server-api/src/main/java/org/apache/ratis/server/protocol/RaftServerAsynchronousProtocol.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java

Add a new server RPC type: readIndex. This RPC is sent from follower to leader for asking current readIndex. 
When a follower receives a linearizable read request, it should first obtain readIndex through this RPC, and then wait forstatemachine to advance and read.
https://issues.apache.org/jira/browse/RATIS-1701

RATIS-1701. Add new Server RPC: readIndex

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/BufferedWriteChannel.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogOutputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestBufferedWriteChannel.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestRaftLogReadWrite.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

When the RaftLog's FileChannel is closed, some async futures may still in pending state. Unexpected error would occur when these futures start executing on a closed file channel, see[ issue-1708](https://issues.apache.org/jira/browse/RATIS-1708). We should wait for these futures.
https://issues.apache.org/jira/browse/RATIS-1708
unit tests.

RATIS-1708. RaftLog file channel closed before async flush ends

---

ratis-common/src/main/java/org/apache/ratis/util/Daemon.java
ratis-common/src/main/java/org/apache/ratis/util/JvmPauseMonitor.java
ratis-common/src/main/java/org/apache/ratis/util/TimeoutScheduler.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDaemon.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/RequestHandler.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedServerRpc.java
ratis-server/src/test/java/org/apache/ratis/statemachine/SimpleStateMachine4Testing.java

Use builder pattern to get rid of multiple overloaded constructors for `Daemon`.
This refactor is a prerequisite for #733 so we can flexibly add another argument to the Daemon builder.
https://issues.apache.org/jira/browse/RATIS-1695
This is just a refactor so the existing unit tests will be sufficient.

RATIS-1695 Use a Builder for Daemon

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/GrpcServerMetrics.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/MessageMetrics.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/RatisMetrics.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/MetricRegistriesImpl.java
ratis-metrics/src/main/java/org/apache/ratis/metrics/impl/MetricRegistryFactoryImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/metrics/NettyServerStreamRpcMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/LeaderElectionMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/LogAppenderMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftLogMetricsBase.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/SegmentedRaftLogMetrics.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/TestRaftLogMetrics.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

See https://issues.apache.org/jira/browse/RATIS-1704

RATIS-1704. Fix SuppressWarnings("VisibilityModifier") in RatisMetrics.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java

In the cluster, we found that there are many exceptions on Failed appendEntries.
Unexpected Index: previous is null but entries[0].getIndex()=3402406. So the follower cannot append an entry due to some limit.
The scenario:
Follower B restarted, leader A sent the entry and B can not find the previous log entry. A sent the notifyInstallSnapshot request to B, and B found its next index is larger than the leader's firstAvailableLogIndex(the index to install snapshot). A updated B's index according to the reply and sent the entries to B.  A will find the previous entry TermIndex through ``getPrevious(long nextIndex)``, if nextIndex of raft log of B is exactly the same as startIndex of leader A (B needs the entries since A's firstAvailableLogIndex), A has purged its raft log and will check the …

RATIS-1707. Fix corner case when getPrevious in LogAppenderBase

---

pom.xml
ratis-assembly/src/main/assembly/bin.xml
ratis-assembly/src/main/assembly/src.xml
ratis-metrics-default/src/test/java/org/apache/ratis/metrics/TestMetricRegistriesLoader.java
ratis-metrics-dropwizard3/pom.xml
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3JvmMetrics.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3MetricRegistriesImpl.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3MetricRegistryFactoryImpl.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3MetricsReporting.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3RatisMetricRegistryImpl.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3RatisObjectNameFactory.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3TimekeeperImpl.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/RefCountingMap.java
ratis-metrics-dropwizard3/src/main/resources/META-INF/services/org.apache.ratis.metrics.MetricRegistries
ratis-metrics-dropwizard3/src/test/java/org/apache/ratis/metrics/dropwizard3/TestLoadDm3MetricRegistries.java
ratis-metrics-dropwizard3/src/test/java/org/apache/ratis/metrics/dropwizard3/TestRefCountingMap.java

See https://issues.apache.org/jira/browse/RATIS-1712

RATIS-1712. Add a dropwizard 3 implementation of ratis-metrics-api.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

1. Add minWait for GrpcLogAppender. When cluster contains a slow follower, 0 waiting time ends up high cpu load and lots of Inconsistent AppendEntries. 
2. Disable retry for Server RPC channel. There's leak in gRPC retry mechanism that could lead to OutOfDirectMemoryError when appendEntries timeout and retried on a slow follower. see https://github.com/grpc/grpc-java/issues/9563.
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-1674
unit tests
manual tests

RATIS-1674. In GrpcLogAppender, disable retry and add minWait.

---

NOTICE
ratis-assembly/src/main/resources/NOTICE

See https://issues.apache.org/jira/browse/RATIS-1719

RATIS-1719. Bump the copyright year to 2022 in NOTICE file.

---

ratis-assembly/pom.xml
ratis-assembly/src/main/assembly/bin.xml
ratis-assembly/src/main/assembly/examples-bin.xml
ratis-assembly/src/main/assembly/shell-bin.xml
ratis-assembly/src/main/assembly/src.xml

See https://issues.apache.org/jira/browse/RATIS-1721

RATIS-1721. example-bin.xml and shell-bin.xml use incorrect LICENSE.

---

dev-support/checks/_mvn_unit_report.sh
dev-support/checks/unit.sh

Allow running multiple iterations of tests in `unit.sh` simply by setting `ITERATIONS` environment variable.
Results (summary, output of failed tests) for all iterations are saved in separate subdirectories.
https://issues.apache.org/jira/browse/RATIS-1658
Locally:
```
$ ITERATIONS=3 ./dev-support/checks/unit.sh -Dtest=TestLogAppenderWithGrpc
...
$ find target/unit -type f | sort
target/unit/iteration1/failures
target/unit/iteration1/output.log
target/unit/iteration1/summary.txt
target/unit/iteration2/failures
target/unit/iteration2/output.log
target/unit/iteration2/summary.txt
target/unit/iteration3/failures
target/unit/iteration3/output.log
target/unit/iteration3/summary.txt
target/unit/summary.txt
$ cat target/unit/summary.txt
Iteration 1 exit code: 0
Iteration 2 exit code: 0
Iteration …
```

RATIS-1658. Prepare unit check for running some tests repeatedly

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientReply.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/ReadIndexException.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestWithLongTimeoutTests.java

In Linearizable Read Only requests, there are two category of exceptions:
1. LeaderNotReady / NotLeader, client should retry on these exceptions.
2. TimeoutIOException, client should accept that this read request fails.
In This PR, I propose to separate ReadException to ReadException(fail) and ReadIndexException(retry-able).
https://issues.apache.org/jira/browse/RATIS-1716
1. Passed original unit tests.
2. Add new unit test suite for client retry on ReadIndexException.

RATIS-1716. Separate ReadException and ReadIndexException for client retry

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java

I removed SuppressedWarning annotation. No additional changes are needed.
https://issues.apache.org/jira/browse/RATIS-1651
unit tests, local findbugs run

RATIS-1651. Fix NP_NULL_PARAM_DEREF in GrpcServerProtocolService

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/BufferedWriteChannel.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogOutputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

Serializing a log entry to RaftLog currently requires two data copies, one from entry to temp heap array, one from heap array to direct byteBuffer. The original motivation is to reduce the former copy and directly serialize log entry to direct byteBuffer. This beneficial in the following two aspects:
1. Avoid temp heap array and reduce young GC pressure.
2. Save CPU cycles on copying data and reduce latency.
However, the checksum operation on Log Entry prevents us from eliminating the extra copy. Performing checksum on direct memory involves copying data back to heap (Oops🥵), one byte at a time. To make matters worse, Unsafe operations involves lots of safety overheads like boundary checking, make the performance even slower (3x times) than original two-copy method. Therefore, we better …

RATIS-1717. Perf: Use global serialize buf to avoid temp buf

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

removed SuppressedWarning annotation. No additional changed are needed.
https://issues.apache.org/jira/browse/RATIS-1652
unit tests, local findbugs run

RATIS-1652. Fix NP_NULL_PARAM_DEREF in DataStreamManagement

---

.github/workflows/post-commit.yml

Upgrade Github Actions action versions to ones that use node16, as node12 is being deprecated: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://issues.apache.org/jira/browse/RATIS-1725
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/3252239569

RATIS-1725. Update github actions for node16

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java

After upgrading to Ratis 2.4.0, I found the param name for heartbeatChannel is confusing. 
It should be `useSeparate` instead of `useCached`
Jira issue: https://issues.apache.org/jira/browse/RATIS-1727

RATIS-1727. Typo: change GrpcConfigKey 'useCached' to useSeparate

---

ratis-examples/src/main/bin/client.sh
ratis-examples/src/main/bin/common.sh
ratis-examples/src/main/bin/server.sh
ratis-examples/src/main/bin/start-all.sh
ratis-experiments/scripts/flatbuf-compile.sh

…ble with CDPATH.
Several Bash scripts in Ratis use this common idiom to discover the current source path and then build relative paths from it:
```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```
This mostly works well, but it isn't compatible with interactive shells using the `CDPATH` environment variable to provide a custom search path for resolving the directory referenced by `cd`.  (See [bash man page](https://linux.die.net/man/1/bash) discussion of `CDPATH` and how the resolved directory is "written to the standard output.")
The standard solution is to redirect stdout of `cd` to `/dev/null`:
```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
```
Some Ratis scripts already do this, but not all.
https://issues.apache.org/jira/browse/RATIS-1340
Manual …

RATIS-1340: Ratis scripts' discovery of Bash source path is incompatible with CDPATH.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/LeaderNotReadyException.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java

See https://issues.apache.org/jira/browse/RATIS-1733

RATIS-1733. Typo: fix misleading params names in `RaftServerConfigKeys`

---

ratis-shell/pom.xml

see https://issues.apache.org/jira/browse/RATIS-1736

RATIS-1736. Fix ratis-shell can't work in branch-2

---

ratis-common/src/main/java/org/apache/ratis/protocol/AdminProtocol.java

See https://issues.apache.org/jira/browse/RATIS-1737

RATIS-1737. Add default leaderElectionManagement implementation in AdminProtocol

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachineStorage.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/leader/InstallSnapshotRequests.java
ratis-server/src/main/java/org/apache/ratis/server/storage/FileChunkReader.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/main/java/org/apache/ratis/server/storage/StorageImplUtils.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java

The same changes as proposed in https://github.com/apache/ratis/pull/774. This PR is for master branch. 
Jira issue see https://issues.apache.org/jira/browse/RATIS-1734

RATIS-1734. Separate state machine snapshot install path

---

ratis-metrics-default/src/main/java/org/apache/ratis/metrics/impl/RatisMetricRegistryImpl.java
ratis-metrics-dropwizard3/src/main/java/org/apache/ratis/metrics/dropwizard3/Dm3RatisMetricRegistryImpl.java

- reduce unnecessary object allocations to reduce memory and garbage collection pressure
- https://issues.apache.org/jira/browse/RATIS-1748
Existing tests cover this

RATIS-1748. Cache getMetricName to reduce garbage

---

ratis-common/src/main/java/org/apache/ratis/util/FileUtils.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/SimpleStateMachineStorage.java
ratis-test/src/test/java/org/apache/ratis/server/storage/TestRaftStorage.java

Clean md5 file created by old ratis version
[RATIS-1752](https://issues.apache.org/jira/browse/RATIS-1752)
Check if old MD5 file can be deleted correctly.

RATIS-1752. Clean md5 file created by old ratis version.

---

ratis-docs/src/site/markdown/devguide.md
ratis-docs/src/site/markdown/snapshot.md

See https://issues.apache.org/jira/browse/RATIS-1750.
This PR proposes to add the snapshot section in developer's guide.
I choose to add snapshot section first since snapshot mechanism is rather complicated, and some requires early decisions, like the decision between `installSnapshot` or `installSnapshotNotification`.

RATIS-1750. Add snapshot section in dev guide

---

pom.xml
ratis-assembly/pom.xml
ratis-client/pom.xml
ratis-common/pom.xml
ratis-docs/pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-grpc/pom.xml
ratis-metrics/pom.xml
ratis-netty/pom.xml
ratis-proto/pom.xml
ratis-replicated-map/pom.xml
ratis-resource-bundle/pom.xml
ratis-server-api/pom.xml
ratis-server/pom.xml
ratis-shell/pom.xml
ratis-test/pom.xml
ratis-tools/pom.xml

Bump version number in POMs on `branch-2` after release.
https://issues.apache.org/jira/browse/RATIS-1755
```
$ mvn -DskipTests clean package
...
[INFO] Reactor Summary for Apache Ratis 2.4.2-SNAPSHOT:
[INFO] 
[INFO] Apache Ratis ....................................... SUCCESS [  0.776 s]
[INFO] Apache Ratis Documentation ......................... SUCCESS [  0.204 s]
[INFO] Apache Ratis Protocols ............................. SUCCESS [  2.565 s]
[INFO] Apache Ratis Common ................................ SUCCESS [  1.289 s]
[INFO] Apache Ratis Client ................................ SUCCESS [  0.666 s]
[INFO] Apache Ratis Server API ............................ SUCCESS [  0.538 s]
[INFO] Apache Ratis Metrics ............................... SUCCESS [  0.652 s]
[INFO] Apache Ratis Server …
```

RATIS-1755. Update version number after 2.4.1 release

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

```java
//RaftServerImpl
private CompletableFuture<ReadIndexReplyProto> sendReadIndexAsync() {
if (getInfo().getLeaderId() == null) {
JavaUtils.completeExceptionally(generateNotLeaderException());
}
final ReadIndexRequestProto request = ServerProtoUtils.toReadIndexRequestProto(
getMemberId(),  getInfo().getLeaderId());
try {
return getServerRpc().async().readIndexAsync(request);
} catch (IOException e) {
return JavaUtils.completeExceptionally(e);
}
}
```
- The first `JavaUtils.completeExceptionally` was not returned
- When the first `getInfo().getLeaderId()` returns non-null, the second `getInfo().getLeaderId()` may return null.
Due to the bugs above, `ReadOnlyRequestTests.testLinearizableReadTimeout()` may fail with NPE; see https://github.com/apache/ratis/actions/runs/3581261971/jobs/602 …

RATIS-1744. NullPointerException causes RaftClient retry failure.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java

ServerState.getLeaderId() still returns itself when a leader just steps down. This PR proposes to update leader to null when stepping down.
https://issues.apache.org/jira/browse/RATIS-1754

RATIS-1754. Set leader to null when stepping down

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java

There is `no next_index`, `match_index` and `rpc_response_time` metric for listener.
[RATIS-1757](https://issues.apache.org/jira/browse/RATIS-1757)

RATIS-1757: Missing some metrics for listener.

---

ratis-examples/README.md
ratis-examples/src/main/java/org/apache/ratis/examples/common/Constants.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/client/CounterClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterServer.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/debug/server/Server.java
ratis-examples/src/main/resources/conf.properties

Add linearizable read usage in Counter example.
Also fixed some problems in ratis-examples/README
https://issues.apache.org/jira/browse/RATIS-1758
manual test.

RATIS-1758. Add linearizable read in Counter example

---

ratis-common/src/main/java/org/apache/ratis/util/OpenCloseState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDaemon.java

See https://issues.apache.org/jira/browse/RATIS-1761

RATIS-1761. If LeaderStateImpl is not running, it should not restart a LogAppender.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java

We encountered `IllegalStateException` indicating a LogSegment missing as follows:
```java
java.lang.IllegalStateException Found a gap between logs: the last log segment log-88826_88927 ended at 88927 but the next log segment log-89130_89071 started at 89130.
at org.apache.ratis.util.Preconditions.assertTrue(Preconditions.java:72)
at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogCache.validateAdding(SegmentedRaftLogCache.java:421)
at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogCache.addSegment(SegmentedRaftLogCache.java:428)
at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogCache.loadSegment(SegmentedRaftLogCache.java:381)
at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLog.loadLogSegments(SegmentedRaftLog.java:241)
at …
```

RATIS-1763. Purging logs in an ordered manner

---

ratis-common/src/main/java/org/apache/ratis/util/FileUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java

In grpcLogAppender, when installing snapshot from leader and fails (corrupted MD5 or other reason), the log-appender can't automatically recover from this failure in the subsequent retry attempts. 
The retry attempt will fail because the `createDirectories` [here](https://github.com/apache/ratis/blob/1b3c61d5dbcdb2b1ac5fd49a624a6cb88ab04744/ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java#L105) will throw a file already exist exception. This PR add a if-clause to create directory only when the directory does not exists.
https://issues.apache.org/jira/browse/RATIS-1764
1. unit tests
2. manual test by simulating a failure scene and to see if the retry result is successful.
exception stack
```java
2022-12-19 20:26:15,071 [grpc-default-executor-4936] ERROR …
```

RATIS-1764. [GrpcLogAppender] Automatic recover from install snapshot failure

---

ratis-server/src/main/java/org/apache/ratis/server/storage/FileChunkReader.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java

Stream MD5 is introduced  by https://github.com/apache/ratis/commit/db3623a22e39a7957d9985fc9fe6784fe977f070 to reduce duplicate IO costs. However, current implementation calculates MD5 chunk-wise instead of file-wise.
We should calculate MD5 once per file, instead of many times per chunk.
https://issues.apache.org/jira/browse/RATIS-1765
1. unit tests.
2. new unit tests.

RATIS-1765. [GrpcLogAppender] Calculate streaming md5 file-wise when installSnapshot

---

ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java

I noticed that matchIndex in leaderStateImpl in initialized with value and I think it is incorrect. 
https://github.com/apache/ratis/blob/d45dccc09c34d9dc51c52c6b14b468b2641692c2/ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java#L40
As the Raft Paper[2] states, matchIndex is 'for each server, index of highest log entry known to be replicated on server’.
[2] https://raft.github.io/raft.pdf 
0 is considered to be a valid Raft Log index in Ratis, and if we initialize matchIndex to 0, the very first log entry will become committed as soon as it is flushed into leader’s LogSegment, instead of after receiving majority ack responses.
This incorrectly initialized matchIndex is **causing permanent Inconsistency problem in our CI environment**, see …

RATIS-1767. Initialize MatchIndex to RaftLog.INVALID_LOG_INDEX

---

pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-resource-bundle/src/main/resources/supplemental-models.xml
ratis-test/pom.xml

Switch to `slf4j-reload4j` provider to avoid bundling `log4j` in Ratis distribution.
> The reload4j project is a fork of Apache log4j version 1.2.17 with the goal of fixing pressing security issues. It is intended as a drop-in replacement for log4j version 1.2.17. By drop-in, we mean the replacement of log4j.jar with reload4j.jar in your build with no source code changes in .java files being necessary.
https://issues.apache.org/jira/browse/RATIS-1776
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/3968298137/jobs/6801284615

RATIS-1776. Switch to slf4j-reload4j

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java

See https://issues.apache.org/jira/browse/RATIS-1774

RATIS-1774. Change SenderList in LeaderStateImpl to implement Iterable.

---

.gitignore

Ignore .vscode/ which is created by VSCode, a popular editor.
https://issues.apache.org/jira/browse/RATIS-1784
Manually verified the directory no longer shows up in git status.

RATIS-1784. Ignore .vscode in source repo.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogInputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogReader.java
ratis-server/src/test/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogTestUtils.java
ratis-server/src/test/java/org/apache/ratis/statemachine/impl/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestCacheEviction.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestRaftLogReadWrite.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java
ratis-tools/src/main/java/org/apache/ratis/tools/ParseRatisLog.java

See https://issues.apache.org/jira/browse/RATIS-1783

RATIS-1783. MAX_OP_SIZE is not configurable on raft log read.

---

ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java

see [jira1786](https://issues.apache.org/jira/browse/RATIS-1786)

RATIS-1786. Reset the digester of the follower at the beginning of each file transfer during a InstallSnapshot to avoid snapshot transfer failure

---

ratis-common/src/main/java/org/apache/ratis/util/ConcurrentUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

see [jira1785](https://issues.apache.org/jira/browse/RATIS-1785)

RATIS-1785. Use SingleThreadExecutor to manage the lifetime of single thread

---

ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java

Fix flaky test ServerRestartTests#testRestartFollower.
https://issues.apache.org/jira/browse/RATIS-1791
Repeat ServerRestartTests#testRestartFollower 100x in CI.
Before this patch, it fails very often:
https://github.com/kaijchen/ratis/actions/runs/4261054005
With ea73079ea24a39c7dc848152fc5dee8416744bcc only, 3/100 test failed:
https://github.com/kaijchen/ratis/actions/runs/4261055481
With both ea73079ea24a39c7dc848152fc5dee8416744bcc and 11c1c78d4a760f0aa344df33aec2ef34200abc8b, all tests passed:
https://github.com/kaijchen/ratis/actions/runs/4261057419

RATIS-1791. Intermittent failure in ServerRestartTests#testRestartFollower

---

ratis-common/src/main/java/org/apache/ratis/util/PeerProxyMap.java

Replace usage of `parallelStream` in `PeerProxyMap#close` with a per-task parallel forEach.
https://issues.apache.org/jira/browse/RATIS-1792
Regular CI:
https://github.com/adoroszlai/incubator-ratis/actions/runs/4264373621

RATIS-1792. Replace parallelStream usage in PeerProxyMap

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/FollowerInfo.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLogIndex.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java

- Enforce raft.server.log.appender.wait-time.min.
- Move GrpcLogAppender.waitTimeMinMs to LogAppenderBase.
- Remove GrpcLogAppender.lastAppendEntries which duplicates lastRpcSendTime.
- Do not print log if no update in RaftLogIndex.
See https://issues.apache.org/jira/browse/RATIS-1793

RATIS-1793. Enforce raft.server.log.appender.wait-time.min.

---

ratis-assembly/src/main/assembly/bin-pkg.xml

https://issues.apache.org/jira/browse/RATIS-1799

RATIS-1799. Make shell scripts in binary package executable

---

ratis-common/src/test/java/org/apache/ratis/BaseTest.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java

Fix flasky test of TestLogAppenderWithGrpc.testPendingLimits
https://issues.apache.org/jira/browse/RATIS-1801
Existed UT

RATIS-1801. Fix flaky test of TestLogAppenderWithGrpc.testPendingLimits

---

ratis-shell/src/main/libexec/ratis-shell-config.sh

Remove unused properties ratis.shell.user.logs.dir
https://issues.apache.org/jira/browse/RATIS-1800
Not need

RATIS-1800. Remove unused ratis-shell properties

---

ratis-test/src/test/java/org/apache/ratis/grpc/TestLogAppenderWithGrpc.java

Fix flaky test, make sure followers are up-to-date before blocking the appends in the follower
https://issues.apache.org/jira/browse/RATIS-1801
Repeat the test 100x in CI
Before: https://github.com/kaijchen/ratis/actions/runs/4322045714
After: https://github.com/kaijchen/ratis/actions/runs/4323233058

RATIS-1806. Further fix for TestLogAppenderWithGrpc#testPendingLimits

---

ratis-docs/src/site/markdown/cli.md

Add doc about GENERIC_COMMAND_OPTIONS of ratis-shell, it's necesary.
https://issues.apache.org/jira/browse/RATIS-1805

[RATIS-1805] Add doc about GENERIC_COMMAND_OPTIONS of ratis-shell

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-proto/src/main/proto/Grpc.proto

See https://issues.apache.org/jira/browse/RATIS-1802

RATIS-1802. GrpcServerProtocolService encounters IllegalStateException: call already closed.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java

see https://issues.apache.org/jira/browse/RATIS-1811

RATIS-1811. Improve StreamObserver's log messages

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java

Address flaky test TestRaftServerWithGrpc#testRaftClientMetrics.
The metrics are updated asynchronously, sometimes it hasn't been updated before assertions.
https://issues.apache.org/jira/browse/RATIS-1810
100x TestRaftServerWithGrpc#testRaftClientMetrics in CI.
Before: https://github.com/kaijchen/ratis/actions/runs/4345085390
After: https://github.com/kaijchen/ratis/actions/runs/4353918913

RATIS-1810. Intermittent failure in TestRaftServerWithGrpc#testRaftClientMetrics

---

.asf.yaml

Enable autolink to Jira on GitHub.
https://issues.apache.org/jira/browse/RATIS-1815
For example:
https://github.com/apache/flink-connector-kafka/commits/main
https://github.com/apache/incubator-celeborn/commits/main

RATIS-1815. GitHub: Enable autolink to Jira

---

ratis-shell/src/main/libexec/ratis-shell-config.sh

This is mainly for supporting Java 17, but any other Java 8+ version should be allowed.
https://issues.apache.org/jira/browse/RATIS-1813
Before
```console
$ bin/ratis sh
Error: ratis-shell requires Java 8 or Java 11, currently Java 17.0.6 found. 
```
After (tested in Java 8 and Java 17)
```console
$ bin/ratis sh
[main] INFO org.reflections.Reflections - Reflections took 32 ms to scan 1 urls, producing 5 keys and 18 values
Usage: ratis sh [generic options]
[election [transfer] [stepDown] [pause] [resume]]         
[group [info] [list]]                                     
[peer [add] [remove] [setPriority]]                       
[snapshot [create]]                                       
```

RATIS-1813. Allow ratis-shell to run in any JDK 8+ version

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

Fix "TransferLeadership can be stopped by appendEntries from old leader", see Jira for details.
> 1. Transferee received startLeaderElection (RaftServerImpl#startLeaderElection:1700 -> RaftServerImpl#changeToCandidate:649 -> RoleInfo#startLeaderElection:121 -> start new thread LeaderElection)
> 2. Transferee received appendEntries (stack trace in the log above), and become follower.
> 3. LeaderElection thread in step 1 is running, found the CandidateState is already CLOSED by step 2.
> 
> The term of transferee is expected to be increased in step 3 (LeaderElection#run:238 -> LeaderElection#askForVotes:304 -> ServerState#initElection:221 -> currentTerm.incrementAndGet).
> But in this case, step 2 is executed before step 3 when the term hasn't been increased.
Increase term immediately when …

RATIS-1796. Fix TransferLeadership stopped by heartbeat from old leader

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Fix group info command not show the listener.
[RATIS-1814](https://issues.apache.org/jira/browse/RATIS-1814)

RATIS-1814: The group info command of the Ratis shell does not show the listener

---

ratis-common/src/main/java/org/apache/ratis/util/ResourceSemaphore.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/util/StreamObserverWithTimeout.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java
ratis-server/src/main/java/org/apache/ratis/server/leader/InstallSnapshotRequests.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcTestClient.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/TestStreamObserverWithTimeout.java
ratis-test/src/test/java/org/apache/ratis/util/TestResourceSemaphore.java

See https://issues.apache.org/jira/browse/RATIS-1812

RATIS-1812. Enforce a outstanding request limit in StreamObserverWithTimeout

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

Separate the timeout between
1. one-time unary gRPC call
2. streaming gRPC call (installSnapshot)
See https://issues.apache.org/jira/browse/RATIS-1809
existing unit tests.

RATIS-1809. Use separated timeout for GrpcLogAppender's streaming RPC

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/election/TransferCommand.java

Yield leader to higher priority peer by TransferLeadership.
To avoid blocking client requests for a long time,
it will only start TransferLeadership when the higher priority peer is up-to-date.
https://issues.apache.org/jira/browse/RATIS-1770
Covered by `LeaderElectionTests#testYieldLeaderToHigherPriority()`.

RATIS-1770. Yield leader to higher priority peer by TransferLeadership

---

ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java

We should not send StartLeaderElection to the transferee when `leaderLastEntry` is null.
Because `leaderLastEntry` is expected to be non-null in `RaftServerImpl#startLeaderElection`:
```java
if (leaderLastEntry == null) {
LOG.warn("{}: receive null leaderLastEntry which is unexpected", getMemberId());
return ServerProtoUtils.toStartLeaderElectionReplyProto(leaderId, getMemberId(), false);
}
```
https://issues.apache.org/jira/browse/RATIS-1817
Existing tests in CI.

RATIS-1817. Do not send StartLeaderElection when leaderLastEntry is null

---

dev-support/checks/_mvn_unit_report.sh
dev-support/checks/build.sh
dev-support/checks/checkstyle.sh
dev-support/checks/findbugs.sh
dev-support/checks/rat.sh
dev-support/checks/sonar.sh
dev-support/checks/unit.sh
dev-support/find_maven.sh
dev-support/make_rc.sh
dev-support/run-test-repeatedly.sh

Split from https://github.com/apache/ratis/pull/854. This is a follow-up for [RATIS-1795](https://issues.apache.org/jira/browse/RATIS-1795). By using Maven Wrapper in CI workflows, we build reproducibly as users/devs in local env.
RATIS-1819
Should pass existing CI checks.
cc @szetszwo

RATIS-1819. Use Maven Wrapper in CI workflows

---

ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/MiniRaftClusterWithSimulatedRpc.java

Increase sleep time in `blockQueueAndSetDelay()` to fix intermittent failure in `testEnforceLeader()`
https://issues.apache.org/jira/browse/RATIS-1662
Repeat 400x in CI
Before: https://github.com/kaijchen/ratis/actions/runs/4477152298
After: https://github.com/kaijchen/ratis/actions/runs/4477155987

RATIS-1662. Intermittent failure in testEnforceLeader

---

pom.xml

see https://issues.apache.org/jira/browse/RATIS-1821

RATIS-1821. Upgrade ratis-thirdparty version to 1.0.4

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Currently, first election is disabled on `setLeader`. However, it does not cover all scenarios. For example, when a candidate receives `DISCOVERED_A_NEW_TERM` as the response to `PreVote`, it should also disable first election.
Therefore, I propose to disable first election on `changeToFollower`
https://issues.apache.org/jira/browse/RATIS-1822
Existing unit tests.

RATIS-1822. Disable first election on changeToFollower

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

Installed snapshot index was updated when installSnapshot is not done,
causing TestLeaderInstallSnapshot to be flaky.
This PR combines `updateInstalledSnapshotIndex` with `reloadStateMachine`,
which will only be called when installSnapshot is done.
https://issues.apache.org/jira/browse/RATIS-1827
* 100x testSeparateSnapshotInstallPath
* before: https://github.com/kaijchen/ratis/actions/runs/4561132033
* after: https://github.com/kaijchen/ratis/actions/runs/4561544643
* 100x testMultiFileInstallSnapshot
* before: https://github.com/kaijchen/ratis/actions/runs/4561143974
* after: https://github.com/kaijchen/ratis/actions/runs/4561548069

RATIS-1827. Update installed snapshot index only when InstallSnapshot is done

---

.idea/vcs.xml

Improve dev experience when using IDEA. When I'm browsing among commits, I can jump to the associated PRs and JIRA tickets with a click.
This config file (trick) is also used by Flink - https://github.com/apache/flink/blob/master/.idea/vcs.xml
~~Not yet. If it's good to go, I can create one.~~
RATIS-1829
Manually.
cc @szetszwo @SzyWilliam

RATIS-1829. Support magic links to PR and JIRA in IDEA

---

ratis-test/src/test/java/org/apache/ratis/retry/TestRetryPolicy.java

Fix intermittent failure in TestRetryPolicy#testRequestTypeDependentRetryWithTimeout()
https://issues.apache.org/jira/browse/RATIS-1830
Repeated 400x in CI:
Before: https://github.com/kaijchen/ratis/actions/runs/4666014513
After: https://github.com/kaijchen/ratis/actions/runs/4666100149

RATIS-1830. Intermittent failure in TestRetryPolicy

---

ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcTestServer.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/TestStreamObserverWithTimeout.java

Fix flaky test TestStreamObserverWithTimeout
https://issues.apache.org/jira/browse/RATIS-1832
Repeat 400x TestStreamObserverWithTimeout in CI:
Before: https://github.com/kaijchen/ratis/actions/runs/4697491698
After: https://github.com/kaijchen/ratis/actions/runs/4697492709

RATIS-1832. Intermittent failure in TestStreamObserverWithTimeout

---

ratis-server/src/main/java/org/apache/ratis/server/storage/FileChunkReader.java

See https://issues.apache.org/jira/browse/RATIS-1837
The observations refer to issue comments in https://github.com/apache/ratis/pull/876.
The cause is that `ByteString::readFrom` will drain out the inputStream and reads all data of a stream into memory, as stated in the doc https://javadoc.io/doc/com.google.protobuf/protobuf-java/2.5.0/com/google/protobuf/ByteString.html 
> Completely reads the given stream's bytes into a ByteString, blocking if necessary until all bytes are read through to the end of the stream.
When a snapshot file is of Gigabytes size, this `ByteString::readFrom` takes 6s to complete and by the time it returns, the follower already starves and starts a new election.

RATIS-1837. Restrict reading maxChunkSize bytes each installSnapshot RPC

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

see [RATIS-1841](https://issues.apache.org/jira/browse/RATIS-1841)

RATIS-1841. Fixed bug where cluster restart failed to transfer snapshot.

---

ratis-docs/src/site/markdown/configurations.md
ratis-docs/src/site/site.xml

As a noob, I've been hoping for more documentation. I noticed some md files were merged but not added to site.xml.
According to [RATIS-1630](https://issues.apache.org/jira/browse/RATIS-1630)
Maybe we can add this markdown to site.xml so we can view the documentation locally.   
When i view the document locally. I found some formatting issues like below:    
I fixed this at the issue:   
[RATIS-1843](https://issues.apache.org/jira/browse/RATIS-1843)
(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

RATIS-1843. Add existing markdown documents to site.xml in the ratis-docs project

---

ratis-common/src/main/java/org/apache/ratis/util/PeerProxyMap.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyRpcProxy.java

`createProxyImpl` is implemented for Netty variant only while the gRPC variant pass the handle to constructor directly. Perhaps it's better to use the same flavor so that improving readability and avoid unexpected `UnsupportedOperationException`.
Chore work. If it's good to have and a JIRA ticket is required, I'll file one.
https://issues.apache.org/jira/browse/RATIS-1848
Compiled.

RATIS-1848. Simplify PeerMap inheritance

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

When the stream server side receives a disconnection, memory is cleared
https://issues.apache.org/jira/browse/RATIS-1850

RATIS-1850. When the stream server channelInactive, cleanup the request.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java

When the stream server channelInactive, all requests in the channel.
At the same time, there will be multiple stream sessions, using the same channel, for transmission, and when the connection is broken, we should clean up more stream sessions
https://issues.apache.org/jira/browse/RATIS-1853

RATIS-1853. When the stream server channelInactive, all requests in the channel.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java

see [jira1854](https://issues.apache.org/jira/browse/RATIS-1854?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)

RATIS-1854 Remove useless error logs when closing the ratisclient writing thread

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/BufferedWriteChannel.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/main/java/org/apache/ratis/server/storage/StorageImplUtils.java

see [jira1855](https://issues.apache.org/jira/browse/RATIS-1855)

RATIS-1855 Fix some sonar code smell and bugs in ratis-server

---

ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestWithLongTimeoutTests.java

`ReadIndex` depends on `StateMachineUpdater` to notify apply index changes. Current implementation only notifies when a `StateMachineLogEntry` is applied. 
In this PR, I propose to notify the `ReadIndex` listener when any types of RaftLog is applied.
https://issues.apache.org/jira/browse/RATIS-1856
1.  unit tests.
2. manual test (perform `read-index read` successfully after configuration changes of a raft group).

RATIS-1856. Notify apply index change of all RaftLog entries

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java

See https://issues.apache.org/jira/browse/RATIS-1858

RATIS-1858. Follower keeps logging first election timeout.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RoleInfo.java

see [jira1861](https://issues.apache.org/jira/browse/RATIS-1861).

RATIS-1861. NullPointerException in readAsync when Ratis leader is changing

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java

see [jira1862](https://issues.apache.org/jira/browse/RATIS-1862)

RATIS-1862 Add the parameter whether to take Snapshot when stopping to adapt to different services

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedStreamAsync.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientReplies.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java

This PR does two things
1. I found that a timeout occurred on the client side, In fact, the server is fine and there are no errors or timeouts, I opened the debug log and found that the client Reply queue had mismatched responses.
2. Delete the replyQueueGracePeriod logic, the Reply queue is cleared, triggered when a close stream is received.
https://issues.apache.org/jira/browse/RATIS-1550

RATIS-1550. Refactor stream client reply queue

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/DivisionProperties.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DivisionPropertiesImpl.java

See https://issues.apache.org/jira/browse/RATIS-1865.
Previous discussions in this thread at https://github.com/apache/ratis/pull/383#issuecomment-756887260 have concluded that the leader lease timeout ratio is unnecessary since the min-rpc-timeout provides sufficient safety. However, it's worth noting that CPU drifts among group peers can vary. Introducing this option enables users to adapt to diverse environments, such as CI or production settings.

RATIS-1865. Add leader lease bound ratio configuration

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java

Delay putting more messages to `appendLog` stream until the stream is ready.
https://issues.apache.org/jira/browse/RATIS-1868
Unit tested.

RATIS-1868. Handling Netty back pressure when streaming ratis log

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PeerConfiguration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java

See https://issues.apache.org/jira/browse/RATIS-1870.
The patch includes two changes:
1. Add considerations on OldConf when deciding whether leader is working as `singleton`.
2. Move `hasMajority` related code to RaftConfigurationImpl.

RATIS-1870. Refactor hasMajority code during configuration changes

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

See https://issues.apache.org/jira/browse/RATIS-1873.
An IllegalStateException is thrown on retry cache entry:
```
2023-08-14 21:59:51,099 [7@group-000200000003-StateMachineUpdater] ERR0R o.a.r.s.i.StateMachineUpdater:196 - 7@group-000200000003-StateMachineUpdater caught a Throwable. 
org.apache.ratis.server.raftlog.RaftLogIOException: java.lang.IllegalStateException: retry cache entry should be pending: l9@client-D8ECBF42B70A:done
at org.apache.ratis.server.impl.RaftServerImpl.applyLogToStateMachine(RaftServerImpl.java:1780)
at org.apache.ratis.server.impl.StateMachineUpdater.applyLog(StateMachineUpdater.java:242)
at org.apache.ratis.server.impl.stateMachineUpdater.run(StateMachineUpdater.java:184)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: …
```

RATIS-1873. Remove RetryCache assertion that doesn't hold

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ReadIndexHeartbeats.java

See https://issues.apache.org/jira/browse/RATIS-1872

RATIS-1872. HeartbeatAck use in-correct callId as minCallId.

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

see [jira](https://issues.apache.org/jira/browse/RATIS-1874)

RATIS-1874 Add notifyLeaderReady function in IStateMachine

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

See https://issues.apache.org/jira/browse/RATIS-1876

RATIS-1876. NPE in GrpcLogAppender.resetClient.

---

ratis-common/src/main/java/org/apache/ratis/util/JvmPauseMonitor.java
ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

See https://issues.apache.org/jira/browse/RATIS-1877

RATIS-1877. In JvmPauseMonitor, sleepTime should not be larger than sleepDeviationThreshold

---

pom.xml

See https://issues.apache.org/jira/browse/RATIS-1878
Let's upgrade maven-checkstyle-plugin version to 3.3.0 which uses checkstyle version 9.3 (the latest version supporting JDK 8) by default.  See https://maven.apache.org/plugins/maven-checkstyle-plugin/history.html

RATIS-1878. checkstyle fails with UnsupportedClassVersionError.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

See https://issues.apache.org/jira/browse/RATIS-1881

RATIS-1881. In LeaderStateImpl, set placeHolderIndex from the log.

---

ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Made a mistake in previous PR https://github.com/apache/ratis/pull/904. The conditions here are a bit of tricky.
The cache entry is expected to be **not completed normally** when `replyPendingRequest`, since we'll complete this cache entry at the very end of `replyPendingRequest`.
The explanation why this assertion fails in previous PR is incorrect. The real path leading to the error is:
If the request r arrived, committed, but became timeout due to blocking apply (may be stuck in a synchronous snapshotting), a client may choose to retry r. However, if the retry gap exceeds retryCache expiration duration (in our case, yes), the very same request r would be committed, **again**. After the snapshotting finished, these two identical requests being applied would cause the assertion to fail. …

RATIS-1873. Fix retry cache warning condition

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Start clientWriteRequest timer as soon as the leader receives the client request.
https://issues.apache.org/jira/browse/RATIS-1885
Patched on a 2.x Ozone cluster and confirmed the metrics look sane.

RATIS-1885. Incorrect clientWriteRequest timer usage

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java

@szetszwo I noticed that we once made a `GrpcUtil.asyncCall` (298c1a2de173c0e2284fc08ef2f953a5fee86e2d) so I reuse the code with a few modification to adapt the readIndex type signature.
I check all rpcs defined in Grpc.proto and the readIndex rpc is the only one remaining having this issue.
https://issues.apache.org/jira/browse/RATIS-1888
IMO, it's trivial and too detailed to test. But if we have some test infra I'm glad to work one.

RATIS-1888. Handle exception of readIndexAsync in gRPC readIndex impl

---

ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java

see [jira](https://issues.apache.org/jira/browse/RATIS-1889)
It looks like the master branch doesn't have this issue, but we can cp this commit to a future 2.x release branch to circumvent some potential issues

RATIS-1889 NoSuchMethodError: RaftServerMetricsImpl.addNumPendingRequestsGauge

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

see [jira](https://issues.apache.org/jira/browse/RATIS-1892)

RATIS-1892 Unify the lifetime of the RaftServerProxy thread pool

---

ratis-common/src/main/java/org/apache/ratis/util/Timestamp.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/FollowerInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DivisionPropertiesImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderLease.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java

In Raft, the leader is responsible for processing and coordinating client requests, replicating data among other followers, and maintaining the distributed state machine. 
Vanilla Raft requires the leader to obtain majority acknowledgements before serving every read requests. During normal operations, this prerequisite leads to unnecessary rpcs exchanged among the cluster, diminished read throughput and increased latency. 
The leader lease is a concept that allows the leader to maintain its leadership without obtaining majority acknowledgements for a certain period of time (lease duration), during which it can directly serve client read requests. 
- Suppose the CPU clocks are perfectly synchronized among cluster machines.
- Let each AppendEntries request AE(i) contain a send time T(i) …

RATIS-1866. Maintain leader lease after AppendEntries

---

ratis-common/src/main/java/org/apache/ratis/util/AwaitForSignal.java
ratis-common/src/main/java/org/apache/ratis/util/AwaitToRun.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java

RATIS-1893. In SegmentedRaftLogCache, start a daemon thread to checkAndEvictCache.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

When testing for 3.0.0 release, we found unexpected error messages introduced by a recent PR https://github.com/apache/ratis/pull/914. 
```java
27951 [grpc-default-executor-6] ERROR o.a.r.grpc.server.GrpcLogAppender - Failed onNext request=AppendEntriesRequest:cid=13,entriesCount=3,lastEntry=(t:2, i:340), reply=1<-2#13:OK-t2,SUCCESS,nextIndex=341,followerCommit=339,matchIndex=340 
java.lang.IllegalStateException: Failed to updateIncreasingly for nextIndex: 343 -> 341
at org.apache.ratis.util.Preconditions.assertTrue(Preconditions.java:73)
at org.apache.ratis.server.raftlog.RaftLogIndex.updateIncreasingly(RaftLogIndex.java:68)
at org.apache.ratis.server.impl.FollowerInfoImpl.increaseNextIndex(FollowerInfoImpl.java:96)
at org.apache.ratis.grpc.server.GrpcLogAppender$AppendLogResponseHandler. …
```

RATIS-1895. Replace increaseNextIndex with  updateNextIndex in GrpcLogAppender

---

ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderLease.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java

see https://issues.apache.org/jira/browse/RATIS-1894

RATIS-1894. Implement ReadOnly based on leader lease

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-common/src/main/java/org/apache/ratis/util/Timestamp.java
ratis-docs/src/site/markdown/configurations.md
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/FollowerInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/DivisionPropertiesImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderLease.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransferLeadership.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java

see https://issues.apache.org/jira/browse/RATIS-1864
In Raft, the leader is responsible for processing and coordinating client requests, replicating data among other followers, and maintaining the distributed state machine. 
Vanilla Raft requires the leader to obtain majority acknowledgements before serving every read requests. During normal operations, this prerequisite leads to unnecessary rpcs exchanged among the cluster, diminished read throughput and increased latency. 
The leader lease is a concept that allows the leader to maintain its leadership without obtaining majority acknowledgements for a certain period of time (lease duration), during which it can directly serve client read requests. 
The requirement of Lease is first brought up by the Alluxio Community @codings-dan.
- …

RATIS-1864. Support lease based read-only requests

---

ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-test/src/test/java/org/apache/ratis/util/TestTimeDuration.java

RATIS-1886. AppendLog sleep fixed time cause significant drop in write throughput.

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyUtils.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyServerStreamRpc.java
ratis-test/src/test/java/org/apache/ratis/netty/TestTlsConfWithNetty.java

From Netty documentation (https://netty.io/wiki/native-transports.html), `EpollEventLoopGroup` generally should have better performance than `NioEventLoopGroup` and therefore should be used by default. The only reason to use `NioEventLoopGroup` is if the underlying OS does not support it (`EpollEventLoopGroup` is only supported in Linux).
From the one of the core developer of Netty (Norman Maurer): https://stackoverflow.com/questions/35568365/netty-epolleventloopgroup-vs-nioeventloopgroup-which-should-i-choose-on-centos
https://issues.apache.org/jira/browse/RATIS-1898
Existing tests (`NioEventLoopGroup` to `EpollEventLoopGroup` should not introduce regressions).

RATIS-1898. Netty should use EpollEventLoopGroup by default

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyClient.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyRpcProxy.java

Similar to RATIS-1898, to use EpollEventLoopGroup for Netty proxies.
https://issues.apache.org/jira/browse/RATIS-1899

RATIS-1899. Use EpollEventLoopGroup for Netty Proxies

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStore.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreCommon.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLogSequentialOps.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransactionManager.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RetryCacheTestUtil.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

RATIS-1897. Make TransactionContext available in DataApi.write(..).

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java

RATIS-1902. The snapshot index is set incorrectly in InstallSnapshotReplyProto.

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

RATIS-1904. Refactor RaftServerImpl.submitClientRequestAsync(..).

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/FollowerInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerInfoImpl.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java

Decrease next index obeying that new one is larger than match index in `GrpcLogAppender::resetClient()`.
[RATIS-1909](https://issues.apache.org/jira/browse/RATIS-1909)
Pass existed tests

RATIS-1909. Fix Decreasing Next Index When GrpcLogAppender Reset Client.

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyUtils.java

RATIS-1917. Print Epoll.unavailabilityCause() only once.

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

see [jira](https://issues.apache.org/jira/browse/RATIS-1918)

RATIS-1918 Introduces parameters that separately control the shutdown of RaftServerProxy by JVMPauseMonitor

---

ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/membership/server/CServer.java
ratis-examples/src/main/java/org/apache/ratis/examples/membership/server/Console.java
ratis-examples/src/main/java/org/apache/ratis/examples/membership/server/RaftCluster.java

The 《CONSENSUS: BRIDGING THEORY AND PRACTICE》 has explain the JOINT consensus, which is implemented by ratis. But it didn't say how to configure the initial conf for new peers. I didn't find demonstration in ratis either.
Initial conf for new peers is easy to make mistakes and cause split brain or cluster unavailable. I think we can add an example to illustrate how to initiate new peers when performing membership change.
https://issues.apache.org/jira/browse/RATIS-1911
Manual tests. This example is an interactive console.

RATIS-1911. Add MembershipManager example.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RoutingTable.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestDataStreamSslWithRpcTypeGrpcAndDataStreamTypeNetty.java

While implementing [HDDS-9392](https://issues.apache.org/jira/browse/HDDS-9392), I incorrectly updated the first node in `RoutingTable` so that it does not point to the same node in `DataStreamClientImpl#dataStreamServer`. This causes some issues that took a while to debug due to the lack of assertion.
To prevent this in the future, let's setup an assertion in `DataStreamClientImpl#stream` to throw exception if the first node in `RoutingTable` is not equal to `DataStreamClientImpl#dataStreamServer`.
https://issues.apache.org/jira/browse/RATIS-1913
Unit test.

RATIS-1913. Assert that the primary peers in DataStreamClient and RoutingTable are equal

---

ratis-common/src/main/java/org/apache/ratis/util/AtomicFileOutputStream.java
ratis-common/src/main/java/org/apache/ratis/util/FileUtils.java
ratis-common/src/main/java/org/apache/ratis/util/LogUtils.java
ratis-common/src/main/java/org/apache/ratis/util/MD5FileUtil.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java

RATIS-1915. Do not use FileInputStream/FileOutputStream in ratis-common.

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/RaftClientImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientRequest.java
ratis-common/src/main/java/org/apache/ratis/rpc/CallId.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RetryCacheImpl.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/client/impl/RaftClientTestUtil.java
ratis-server/src/test/java/org/apache/ratis/statemachine/impl/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftServerWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestRetryCacheWithGrpc.java

RATIS-872. Invalidate replied calls in retry cache.

---

ratis-common/src/main/java/org/apache/ratis/util/ConcurrentUtils.java
ratis-common/src/main/java/org/apache/ratis/util/JavaUtils.java
ratis-examples/src/main/java/org/apache/ratis/examples/common/Constants.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/CounterCommand.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/client/CounterClient.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterServer.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/membership/server/CServer.java
ratis-examples/src/test/java/org/apache/ratis/examples/counter/TestCounter.java

RATIS-1901. Update Counter example to benchmark performance.

---

ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

RATIS-1924. Increase the default of raft.server.log.segment.size.max.

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

RATIS-1923. Netty: atomic operations require side-effect-free functions.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/GroupManagementBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftServerTestUtil.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/server/impl/TestRaftConfiguration.java

This patch resolves a membership change bug. See detail in https://github.com/apache/ratis/pull/943.
https://issues.apache.org/jira/browse/RATIS-1912
unit tests

RATIS-1912. Fix infinity election when perform membership change.

---

ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedObject.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyConfigKeys.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamChainTopologyWithGrpcCluster.java
ratis-test/src/test/java/org/apache/ratis/datastream/TestNettyDataStreamStarTopologyWithGrpcCluster.java
ratis-test/src/test/java/org/apache/ratis/util/TestReferenceCountedObject.java

When benchmarking Ozone streaming pipeline using `ozone freon ockg`, the benchmark would not end although all the keys have been written.  `hdds.ratis.raft.netty.dataStream.client.worker-group.share` is set to true to use the shared worker group optimization.
Using Arthas, it's found that non-daemon threads like "NettyClientStreamRpc-workerGroup–thread1" are still running even after the benchmark has finished. The root cause is that the shared worker group will never be closed, causing the JVM shutdown hook to never be triggered. The benchmark was able to shutdown normally if the share configuration is disabled.
It seems that shared worker group is a lazily instantiated singleton. The shared worker group will be instantiated when the first `WorkerGroupGetter` is instantiated and passed to …

RATIS-1921. Shared worker group in WorkerGroupGetter should be closed

---

pom.xml

see https://issues.apache.org/jira/browse/RATIS-1929

RATIS-1929. Bump ratis-thirdparty version to 1.0.5

---

ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java

RATIS-1930. Add a conf for enable/disable majority-add.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/util/ZeroCopyMessageMarshaller.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/util/ZeroCopyReadinessChecker.java

First step of bringing zero-copy support to Ratis GRPC is create a message marshaller in ratis-grpc (https://github.com/GoogleCloudPlatform/grpc-gcp-java/pull/77).
Sample usage can be found from [here](https://github.com/duongkame/ratis/blob/RATIS-1925/ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java#L308).
https://issues.apache.org/jira/browse/RATIS-1932
This code path is unused now, test will be added when the feature is implemented as per RATIS-1925 and RATIS-1926.

RATIS-1932. Create zero-copy Marshaller

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ReadRequests.java

see https://issues.apache.org/jira/browse/RATIS-1927.
The `LastAppliedTermIndex` may be updated in between of the `check` and `enqueue`. 
Normally this data race is not a big deal since the next increment in AppliedIndex will complete the waiting entry. 
However, when IOTDB restarts, there will be no subsequent read/write requests unless the first probing read request successfully returns. Under situations like that, this data race may haunt the system several seconds until reaching timeout.
I added a post-double-check as a quick fix instead of implementing synchronization.

RATIS-1927. Use double check to eliminate data race in ReadRequests 

---

ratis-common/src/main/java/org/apache/ratis/util/IOUtils.java
ratis-common/src/main/java/org/apache/ratis/util/PureJavaCrc32C.java
ratis-common/src/test/java/org/apache/ratis/util/TestPureJavaCrc32C.java
ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/BufferedWriteChannel.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogFormat.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogOutputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogReader.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-test/src/test/java/org/apache/ratis/server/ServerRestartTests.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestBufferedWriteChannel.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

RATIS-589. Eliminate buffer copying in SegmentedRaftLogOutputStream.

---

.github/workflows/post-commit.yml

Fix SonarCloud issues:
> The version of Java (11.0.21) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
> Shallow clone detected during the analysis. Some files will miss SCM information. This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.
https://issues.apache.org/jira/browse/RATIS-1951
Since `sonar` check only runs for commits in the main repo, it will be tested after merge.  But similar change was [already done](https://github.com/apache/ozone/commit/08131b9addc719551a8e4d8c1846f8c8f11bd62c) for Ozone.

RATIS-1951. Upgrade sonar check to Java 17

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java

Some of the logs in `NettyClientStreamRpc` mention the source of the message using `toString` inherited from `Object`.  Replace them with more readable names.
https://issues.apache.org/jira/browse/RATIS-1956
Before:
```
(NettyClientStreamRpc.java:operationComplete(194)) - org.apache.ratis.netty.client.NettyClientStreamRpc$Connection$1@36383c10 succeed.
(NettyClientStreamRpc.java:channelRead(330)) - org.apache.ratis.netty.client.NettyClientStreamRpc$1@31294ad5: read DataStreamReplyByteBuffer:clientId=client-F61E6E1DAE37,type=STREAM_HEADER,id=1,offset=0,length=0,SUCCESS,bytesWritten=0
```
After:
```
(NettyClientStreamRpc.java:operationComplete(194)) - Connection-localhost/127.0.0.1:33119 succeed.
(NettyClientStreamRpc.java:channelRead(330)) - NettyClientStreamRpc->s0: read …
```

RATIS-1956. Avoid built-in toString in NettyClientStreamRpc log

---

dev-support/checks/build.sh
dev-support/checks/checkstyle.sh
dev-support/checks/findbugs.sh
dev-support/checks/rat.sh
dev-support/checks/sonar.sh
dev-support/checks/unit.sh

If dependencies are not available in local repo, Maven logs download progress for each:
```
[INFO] Downloading from apache.snapshots: https://repository.apache.org/snapshots/com/github/spotbugs/spotbugs-maven-plugin/4.2.0/spotbugs-maven-plugin-4.2.0.pom
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-maven-plugin/4.2.0/spotbugs-maven-plugin-4.2.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-maven-plugin/4.2.0/spotbugs-maven-plugin-4.2.0.pom (33 kB at 1.3 MB/s)
[INFO] Downloading from apache.snapshots: https://repository.apache.org/snapshots/com/github/hazendaz/base-parent/27/base-parent-27.pom
[INFO] Downloading from central: …
```

RATIS-1959. Omit download progress in CI builds

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

1. Fix race condition that may cause follower to be incorrectly marked as having caught up with leader.
2. Fix calculation of `initializing` flag for `appendEntries` request sent to follower.
Please see RATIS-1960 for details on both.
CI:
https://github.com/adoroszlai/ratis/actions/runs/7151958459
Passed 10x50 `TestInstallSnapshotNotificationWithGrpc#testInstallSnapshotDuringBootstrap` (this was failing in 6% of runs after fixing only the race condition):
https://github.com/adoroszlai/ratis/actions/runs/7152037092

RATIS-1960. Follower may be incorrectly marked as having caught up

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/util/ZeroCopyMessageMarshaller.java

RATIS-1939 refactored `ZeroCopyMessageMarshaller`, replacing `popStream(T)` with `release(T)`.  For compatibility with 3.0.0, I would like to add back `popStream`.
(Note: there is a typo in the commit message, please use PR title when merging, if the change  is accepted.)
https://issues.apache.org/jira/browse/RATIS-1963
CI:
https://github.com/adoroszlai/ratis/actions/runs/7169889152

RATIS-1963. Restore ZeroCopyMessageMarshaller#popStream

---

ratis-common/src/main/java/org/apache/ratis/util/PureJavaCrc32C.java

Fixed SF_SWITCH_NO_DEFAULT findbugs issue in `PureJavaCrc32C`
RATIS-1649
Manually ran findbugs to make sure that the warning is gone after removing the `SuppressFBWarnings`

RATIS-1649. Fix SF_SWITCH_NO_DEFAULT in PureJavaCrc32C.

---

ratis-common/src/main/java/org/apache/ratis/io/MD5Hash.java

Fixed `EI_EXPOSE_REP` findbugs warning in MD5Hash.
RATIS-1648
Ran findbugs manually and verified the change.

RATIS-1648. Fix EI_EXPOSE_REP in MD5Hash.

---

ratis-common/src/main/java/org/apache/ratis/util/LifeCycle.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-test/src/test/java/org/apache/ratis/util/TestLifeCycle.java

Assign local address to new peers being added to the cluster.
https://issues.apache.org/jira/browse/RATIS-1942
Compared 10x10 runs of `TestRetryCacheWithGrpc` with and without the patch.
without patch: 13/100 failures, 10/13 failure logs had `STARTING -> STARTING`:
https://github.com/adoroszlai/ratis/actions/runs/7199041920
```
$ grep -cr 'STARTING -> STARTING' | sort -g
1/iteration2/ratis-test/org.apache.ratis.grpc.TestRetryCacheWithGrpc-output.txt:1223
2/iteration1/ratis-test/org.apache.ratis.grpc.TestRetryCacheWithGrpc-output.txt:1457
2/iteration3/ratis-test/org.apache.ratis.grpc.TestRetryCacheWithGrpc-output.txt:1284
2/iteration9/ratis-test/org.apache.ratis.grpc.TestRetryCacheWithGrpc-output.txt:1374
3/iteration7/ratis-test/org.apache.ratis.grpc.TestRetryCacheWithGrpc-output.txt:1190 …
```

RATIS-1942. GrpcLogAppender has `ILLEGAL TRANSITION: STARTING -> STARTING`

---

ratis-common/src/main/java/org/apache/ratis/util/BatchLogger.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

See https://issues.apache.org/jira/browse/RATIS-1966. 
See the effects:
BEFORE：
AFTER

RATIS-1966. Batch frequent warn logs during gRPC exceptional periods

---

.github/workflows/post-commit.yml

* Use explicit `cache/restore` in all checks except `build`.  This avoids the need for separate cache keys in concurrent checks, since only `build` will save cache.
* Specify `path` exception to avoid the need to explicitly delete Ratis artifacts before cache upload.
* Add step name where missing.
https://issues.apache.org/jira/browse/RATIS-1984
CI:
https://github.com/adoroszlai/ratis/actions/runs/7357421711

RATIS-1984. Simplify Maven cache for dependencies in CI

---

.github/workflows/post-commit.yml
dev-support/checks/build.sh
dev-support/checks/coverage.sh
dev-support/checks/findbugs.sh
dev-support/checks/unit.sh
pom.xml
ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java

* Setup Java 8 in `unit` check to match the version used in `build` check.
* Collect code coverage data from `unit` check.
* Rename `sonar` check to `coverage`.
* Combine coverage data from `unit` check splits.
* Generate HTML and XML report from combined coverage data.
Sonar Cloud, which currently shows 0% coverage, will hopefully pick up the same data.  (We may need an additional hack [like this](https://github.com/apache/ozone/blob/58572aaa736bb4c9ef859020c2a4726c7f1de97a/hadoop-ozone/dev-support/checks/sonar.sh#L26-L31).  But first let's try without that one.)
https://issues.apache.org/jira/browse/RATIS-1985
Temporarily enabled `coverage` check in forks.  Downloaded `coverage` artifact, checked HTML report.
https://github.com/adoroszlai/ratis/actions/runs/7364058733

RATIS-1985. Calculate code coverage

---

dev-support/checks/sonar.sh

RATIS-1985 added code coverage calculation. SonarCloud expects the report in a different location, so it still shows 0%.
```
[INFO] 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
[INFO] No report imported, no coverage information will be imported by JaCoCo XML Report Importer
```
This change sets the property to the location of the aggregate XML report generated by `coverage.sh`.
https://issues.apache.org/jira/browse/RATIS-1988
Tested in (non-fork) [CI run](https://github.com/apache/ratis/actions/runs/7377131200/job/20070984036#step:8:1298):
```
[INFO] Sensor JaCoCo XML Report Importer [jacoco]
[INFO] Importing 1 report(s). Turn your logs in debug …
```

RATIS-1988. Provide Jacoco report to Sonar

---

ratis-common/src/main/java/org/apache/ratis/conf/ReconfigurationBase.java

Change the judgment logic: 
It is necessary to determine whether the `effective` is null, rather than `newValue`.
Because the parameter of the `properties.set` method is `effective`.
```java
final String effective = reconfigureProperty(property, newValue);
LOG.info("{}: changed property {} to {} (effective {})", name, property, newValue, effective);
if (newValue != null) {
properties.set(property, effective);
} else {
properties.unset(property);
}
```
https://issues.apache.org/jira/browse/RATIS-1991
No testing required.

RATIS-1991. Optimize the reconfig judgment logic in the ReconfigurationBase class.

---

ratis-docs/src/site/markdown/metrics.md
ratis-metrics-api/src/main/java/org/apache/ratis/metrics/RatisMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/WatchRequests.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/RaftServerMetricsImpl.java
ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java

Add some watch request metrics for better visibility. 
The metrics are:
- number of watch request in queue
- number of watch request queue limit hit
- number of watch request timeout
https://issues.apache.org/jira/browse/RATIS-1998
UT.

RATIS-1998. Add watch request metrics

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/util/StreamObserverWithTimeout.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcTestClient.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcTestServer.java
ratis-test/src/test/java/org/apache/ratis/grpc/util/TestStreamObserverWithTimeout.java

Fix intermittent timeout in `TestStreamObserverWithTimeout#testWithTimeout`.
1. The first request may take long to reach the server, probably due to some initialization overhead.  The patch adds a "warmup" request, for which timeout is not applied.
2. Client and server seem to share `grpc-default-executor` thread pool.  This may result in delay at client due to server sleeping.  The patch uses a thread per request in `GrpcTestServer`.
3. With these, we can restore test settings prior to 29d032dde65cfb441e7c912b1621cfff6c266674.
https://issues.apache.org/jira/browse/RATIS-1989
Passed 500x in [repeated run](https://github.com/adoroszlai/ratis/actions/runs/7528357858) (although it [also passed](https://github.com/adoroszlai/ratis/actions/runs/7529250422) 500x on `master`).
Since it's passing …

RATIS-1989. Intermittent timeout in TestStreamObserverWithTimeout

---

ratis-test/src/test/java/org/apache/ratis/grpc/util/GrpcZeroCopyTestClient.java

See RATIS-1987.
The test client should enqueue before calling `onNext(..)`.
After this change, passed 100 times: https://github.com/szetszwo/ratis/actions/runs/7532901374

RATIS-1987. Intermittent NPE in TestGrpcZeroCopy.

---

ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequest.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequests.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/TransactionManager.java

See RATIS-2001
We should use `TermIndex` instead of `index` as the key of the maps.

RATIS-2001. TransactionContext can be wrongly reused.

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegmentPath.java

Avoid the need for `@SuppressFBWarnings` in `LogSegmentPath`.
https://issues.apache.org/jira/browse/RATIS-2002
CI:
https://github.com/adoroszlai/ratis/actions/runs/7562377046

RATIS-2002. Fix findbugs warnings in LogSegmentPath

---

ratis-server/src/main/java/org/apache/ratis/server/leader/InstallSnapshotRequests.java

Remove `@SuppressFBWarnings("IT_NO_SUCH_ELEMENT")` in `InstallSnapshotRequests`, and ensure spotbugs does not complain.
https://issues.apache.org/jira/browse/RATIS-2003
CI:
https://github.com/adoroszlai/ratis/actions/runs/7562098256

RATIS-2003. Fix IT_NO_SUCH_ELEMENT in InstallSnapshotRequests

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java

Replace `compareTo` with `Comparator` in `LogSegment` to get rid of `EQ_COMPARETO_USE_OBJECT_EQUALS` warning (previously suppressed).
https://issues.apache.org/jira/browse/RATIS-2004
CI:
https://github.com/adoroszlai/ratis/actions/runs/7574274326

RATIS-2004. Fix EQ_COMPARETO_USE_OBJECT_EQUALS in LogSegment

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcClientProtocolService.java
ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLogSequentialOps.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java

See [RATIS-2009](https://issues.apache.org/jira/browse/RATIS-2009)
Found this issue when running tests for #1014, TestServerRestartWithGrpc failed because RaftConfiguration entry zero-copy buffer are released too early (while the log entry are still in the EntryCache.)
https://issues.apache.org/jira/browse/RATIS-2009

RATIS-2009. ReferenceCount should work for all LogEntry types.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java

Support Zero-Copy in GrpcServerProtocolService.appendEntries
https://issues.apache.org/jira/browse/RATIS-1934

RATIS-1934. Support Zero-Copy in GrpcServerProtocolService

---

pom.xml
ratis-assembly/src/main/resources/NOTICE
ratis-common/pom.xml
ratis-common/src/main/java/org/apache/ratis/protocol/RaftPeerId.java
ratis-netty/pom.xml
ratis-server-api/pom.xml
ratis-server/pom.xml
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/BufferedWriteChannel.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java

* Remove some unnecessary `@SuppressFBWarnings`
* Remove dependency on `spotbugs-annotations`
* Remove single usage of `javax.annotation` coming from `jsr305`, which is a transitive dependency via `spotbugs-annotations`
https://issues.apache.org/jira/browse/RATIS-2010
```
$ mvn -DskipTests clean package
$ ./dev-support/checks/findbugs.sh
```
CI:
https://github.com/adoroszlai/ratis/actions/runs/7575711637

RATIS-2010. Remove dependency on spotbugs-annotations

---

ratis-server/src/main/java/org/apache/ratis/server/impl/VoteContext.java

During pre-vote, some follower reject the PRE_VOTE request from a candidate although the candidate has the same peer ID as the current leader. 
`2024-01-18 13:44:50,123 [grpc-default-executor-100] INFO org.apache.ratis.server.impl.VoteContext: e46cc30b-13ca-4778-b856-e84b0677493d@group-059247EC8137-FOLLOWER: reject PRE_VOTE from c7e3fa47-df62-4883-8d6e-50c3b6a9b94c: this server is a follower and still has a valid leader c7e3fa47-df62-4883-8d6e-50c3b6a9b94c`
It might be a good idea to add another check so that if the candidate has the same peer ID as the follower's current recognized leader, we approve the PRE_VOTE request.
Note: The optimization might be marginal since leader is only valid after min.rpc.timeout (150ms). Afterwards, the follower should recognize the candidate. …

RATIS-2008. Follower should recognize candidate if the candidate is the same peer as the current valid leader

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientAsynchronousProtocol.java
ratis-common/src/main/java/org/apache/ratis/util/SlidingWindow.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcClientProtocolService.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

When running tests as per #1023, some buffer leaks are discovered.
1. The `ReferenceCountedObject` `release` in `whenComplete` (e.g. `RaftServerImpl`'s `submitClientRequestAsync ` and `appendEntriesAsync`) does not always guarantee an execution. As the retuned future may be discarded when the client connection is terminated.
2. The `processClientRequest` called from SlidingWindow doesn't always guarantee 100% execution either. `PendingOrderedRequest ` entries may not be processed at all because of client cancellation, or request duplications (`IllegalStateException` due to retries.  
3. LogEntryProto loaded from files is not released after being retained. This is harmless for now but is noisy in leak detection mode.
https://issues.apache.org/jira/browse/RATIS-2007
Tests.

RATIS-2007. Zero-copy buffers are not released

---

.github/workflows/post-commit.yml
.github/workflows/repeat-test.yml

Upgrade GitHub actions to `v4` to get Node.js 20.
https://issues.apache.org/jira/browse/RATIS-2015
https://github.com/adoroszlai/ratis/actions/runs/7644603377

RATIS-2015. Node.js 16 actions are deprecated

---

ratis-metrics-default/pom.xml
ratis-metrics-default/src/test/java/org/apache/ratis/metrics/TestMetricRegistriesLoader.java
ratis-metrics-default/src/test/java/org/apache/ratis/metrics/impl/TestRefCountingMap.java

Migrate ratis-metrics-default tests to Junit 5.
RATIS-1974
Ran unit test locally

RATIS-1974. Migrate ratis-metrics-default tests to Junit 5.

---

ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedObject.java
ratis-common/src/main/java/org/apache/ratis/util/SlidingWindow.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcClientProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-server-api/src/main/java/org/apache/ratis/server/protocol/RaftServerAsynchronousProtocol.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/test/java/org/apache/ratis/statemachine/impl/SimpleStateMachine4Testing.java

Zero-copy buffers are not released - 2nd chunk, including fixes in:
1. Sliding window: requests being replied as `will NEVER be processed`, requests coming with seqNum < nextToProcess.
2. appendEntries: avoid releasing at `whenComplete`.
3. Streaming request: pending requests retained must be released after completing.
4. Log entries being purged (after snapshot) must be released.
https://issues.apache.org/jira/browse/RATIS-2018
CI

RATIS-2018. Zero-copy buffers are not released - 2nd chunk

---

ratis-examples/pom.xml
ratis-examples/src/test/java/org/apache/ratis/TestMultiRaftGroup.java
ratis-examples/src/test/java/org/apache/ratis/examples/ParameterizedBaseTest.java
ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/TestArithmetic.java
ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/TestArithmeticLogDump.java
ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/cli/TestAssignCli.java
ratis-examples/src/test/java/org/apache/ratis/examples/arithmetic/expression/TestExpression.java
ratis-examples/src/test/java/org/apache/ratis/examples/common/TestSubCommand.java
ratis-examples/src/test/java/org/apache/ratis/examples/counter/TestCounter.java

This PR migrates ratis-examples tests to Junit 5
RATIS-1973
Using existing unit tests

RATIS-1973. Migrate ratis-examples tests to Junit 5.

---

ratis-common/src/main/java/org/apache/ratis/util/LeakDetector.java
ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedLeakDetector.java
ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedObject.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/metrics/ZeroCopyMetrics.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcService.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-server/src/test/java/org/apache/ratis/LogAppenderTests.java
ratis-server/src/test/java/org/apache/ratis/RaftExceptionBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java

Add metrics assertions to verify all zero-copy messages are released properly. 
This PR also introduces a simple leak-tracing mechanism to help debug the leaks' source. This leak detection is only enabled for tests. It has 2 modes:
- Simple: enabled by default for test. The leak report looks like below.
```
2024-01-22 12:55:50,391 [LeakDetector-ReferenceCountedObject0] WARN  util.ReferenceCountedLeakDetector (ReferenceCountedLeakDetector.java:lambda$new$0(87)) - LEAK: A org.apache.ratis.protocol.RaftClientRequest is not released properly
``` 
- Advanced: the leak report includes all the stacktraces for object creation, retains and releases. The capturing of stacktraces has a severe impact on performance and makes few tests timed out. So, this is only enabled manually to debug specific …

RATIS-1978. Add tests assertions to verify all zero-copy messages are released properly

---

ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/statemachine/impl/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

StateMachine should be supplied log entries by ReferenceCountedObject<LogEntryProto> instead of LogEntryProto. 
https://issues.apache.org/jira/browse/RATIS-1997
CI

RATIS-1997. Refactor StateMachine interface to use ReferenceCountedObject

---

ratis-examples/src/main/java/org/apache/ratis/examples/arithmetic/ArithmeticStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/counter/server/CounterStateMachine.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/TransactionContext.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequest.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/TransactionContextImpl.java
ratis-server/src/test/java/org/apache/ratis/ReadOnlyRequestTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/StateMachineShutdownTests.java
ratis-server/src/test/java/org/apache/ratis/statemachine/impl/SimpleStateMachine4Testing.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java
ratis-test/src/test/java/org/apache/ratis/statemachine/TestStateMachine.java

Client `StateMachine` code may cache log entries supplied from `TransactionContext` in `applyTransaction`. Hence, `TransactionContext` needs to supply log entries via a ReferenceCountedObject.
Next: RATIS-2026
https://issues.apache.org/jira/browse/RATIS-2020
CI. https://github.com/duongkame/ratis/actions/runs/7821145122

RATIS-2020. Refactor TransactionContext to supply LogEntryProto via a ReferenceCountedObject

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/ChannelMap.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/StreamMap.java
ratis-server-api/src/main/java/org/apache/ratis/server/DataStreamServerRpc.java
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerRpc.java
ratis-server-api/src/main/java/org/apache/ratis/server/ServerRpc.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamBaseTest.java

RATIS-2035. Refactor streaming code for Read.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

When testing the tranferLeadership feature, I get the following exeption:
```
org.apache.ratis.protocol.exceptions.TransferLeadershipException: s0@group-5B01F2A9DF29 refused to transfer leadership to peer s1 as it does not has highest priority 5: peers:[s0|rpc:localhost:62939|admin:localhost:62940|client:localhost:62941|dataStream:localhost:62942|priority:2|startupRole:FOLLOWER, s1|rpc:localhost:62943|admin:localhost:62944|client:localhost:62945|dataStream:localhost:62946|priority:0|startupRole:FOLLOWER, s2|rpc:localhost:62947|admin:localhost:62948|client:localhost:62949|dataStream:localhost:62950|priority:0|startupRole:FOLLOWER]|listeners:[], old=null
```
The expression of "it does not has highest priority 5" doesn't seem good.
After the change, log becomes as follows:
``` …
```

RATIS-2043. Change toString() of RaftConfigurationImpl

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ReadIndexHeartbeats.java

One linearizable read (read-index based) thread is stuck and never returned. jstack shows
```
"pool-75-IoTDB-ClientRPC-Processor-35$20240317_005430_35720_4.1.0" #14477 prio=5 os_prio=0 tid=0x00007ffafc049800 nid=0x3eb65e waiting on condition [0x00007ff8f5bc6000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x000000031efd8348> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
at …
```

RATIS-2044. Fix ReadIndex loss caused by data race in AppendEntriesListeners

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2036)

RATIS-2036 Avoid trigger snapshot when removing raftGroup

---

ratis-client/src/main/java/org/apache/ratis/client/api/SnapshotManagementApi.java
ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-client/src/main/java/org/apache/ratis/client/impl/SnapshotManagementImpl.java
ratis-common/src/main/java/org/apache/ratis/protocol/SnapshotManagementRequest.java
ratis-proto/src/main/proto/Raft.proto
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Allow client to set `creationGap` in snapshot management requests. The parameter will override the server's `snapshot.creation.gap` property. In that way, client can force a snapshot (with `creationGap = 0`) without having to change global server's property.
https://issues.apache.org/jira/browse/RATIS-2050

RATIS-2050. Add creationGap param to snapshot management API

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java
ratis-server-api/src/main/java/org/apache/ratis/server/raftlog/RaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDefault.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java

LogAppender must consume log entries as reference counted objects because it keeps the entries for asynchronous processing.
This must include `StateMachine.read` to provide a reference as well. This will be done in RATIS-1979 (see the last comment in the JIRA). 
https://issues.apache.org/jira/browse/RATIS-2026
CI.

RATIS-2026. LogAppender to consume log entries with reference count

---

ratis-common/src/main/java/org/apache/ratis/util/LeakDetector.java
ratis-common/src/main/java/org/apache/ratis/util/PeerProxyMap.java
ratis-common/src/main/java/org/apache/ratis/util/Preconditions.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ConfigurationManager.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderLease.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/metrics/LeaderElectionMetrics.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/main/java/org/apache/ratis/server/storage/RaftStorageDirectoryImpl.java
ratis-server/src/main/java/org/apache/ratis/server/storage/SnapshotManager.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/TransactionContextImpl.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2051)

RATIS-2051 Fix Sonar bugs for Ratis

---

ratis-docs/src/site/markdown/cli.md
ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/local/RaftMetaConfCommand.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/LocalCommandIntegrationTest.java

Originally, the PeerId generated in file new-raft-meta.conf by command 
`$ ratis sh local raftMetaConf -peers <P0_HOST:P0_PORT,P1_HOST:P1_PORT,P2_HOST:P2_PORT> -path <PARENT_PATH_OF_RAFT_META_CONF> `
it uses the address of server as PeerId, which would cause the ratis group to fail to start if there are some duplicated addresses stored in raft-meta.conf.
Thus, need to fix that by using actual PeerId in raft-meta.conf and store back to generated new-raft-meta.conf.
https://issues.apache.org/jira/browse/RATIS-2040
tested in dev cluster, integration test

Ratis-2040. Fix RaftPeerId generated by command of "raftMetaConf" to use real PeerId

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientReplies.java
ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientStreamRpc.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

RATIS-1504. Add timeout handling to DataStreamManagement#checkSuccessRemoteWrite.

---

ratis-common/src/main/java/org/apache/ratis/util/JavaUtils.java

RATIS-2057. Add back JavaUtils.attemptUntilTrue(..).

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java

See [RATIS-2059](https://issues.apache.org/jira/browse/RATIS-2059).
https://issues.apache.org/jira/browse/RATIS-2059
CI.

RATIS-2059. Missing reference count when putting log entries to cache on follower

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Move notifyTermIndexUpdated after leader.checkReady
https://issues.apache.org/jira/browse/RATIS-2055

RATIS-2055. Move notifyTermIndexUpdated after leader.checkReady

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2060)

RATIS-2060 Avoid unexpected shutdown of RaftServerProxy during membership change

---

ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java

1. parameter `int thresholdMs` in `RaftServerConfigKeys#setCloseThreshold` is misrepresented as milliseconds while the correct unit is seconds. So fix the unit to TimeDuration.
2. Also fix `setSleepDeviationThreshold` parameter unit to TimeDuration.
https://issues.apache.org/jira/browse/RATIS-2061
manual tests : It passes the parameter verification in ozone project.

RATIS-2061. Fix setCloseThreshold parameter in RaftServerConfigKeys

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/local/RaftMetaConfCommand.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/LocalCommandIntegrationTest.java

[RATIS-2040](https://issues.apache.org/jira/browse/RATIS-2040) made some changes in the command to add an option to provide peerID. While doing so , it updated the address string to be of pattern "hostname/ip:port" which was previously hostname:port. This PR sets it back to "host:port" pattern.
This causes connectionRefused messages in the application as the wrong address string is used.
https://issues.apache.org/jira/browse/RATIS-2069
Unit test added

RATIS-2069. RaftMetaConf command sets incorrect peerAddress pattern.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/LogProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/memory/MemoryRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/util/ServerStringUtils.java

See [RATIS-2068](https://issues.apache.org/jira/browse/RATIS-2068).
https://issues.apache.org/jira/browse/RATIS-2068
CI

RATIS-2068. Avoid logging raw StateMachine data body.

---

.github/workflows/post-commit.yml

dependabot pushes dependency version bumps to the main repo instead of its own fork. It then creates a pull request without waiting for the push workflow to succeed. Thus both workflows test the same state of code, which is unnecessary.
Example: [PR](https://github.com/apache/ratis/pull/1076), [push workflow](https://github.com/apache/ratis/actions/runs/8944621294/job/24571916137?pr=1076), [PR workflow](https://github.com/apache/ratis/actions/runs/8944621510/job/24571916496?pr=1076).
With this change, checks will not be triggered by `push` to branches prefixed with `dependabot/`, which matches dependabot naming convention.  PR checks will still be run.
https://issues.apache.org/jira/browse/RATIS-2070
Pushed the same commit in my fork to:
- branch …

RATIS-2070. Skip push build for dependabot

---

.github/workflows/post-commit.yml

The maximum time to let a job run before GitHub automatically cancels it is 6 hours by default. The goal of this task is to define shorter timeouts for jobs in Ratis CI workflow, which is expected to complete in less time.
https://issues.apache.org/jira/browse/RATIS-2072
CI:
https://github.com/adoroszlai/ratis/actions/runs/8956839210

RATIS-2072. Limit timeout of CI workflow jobs

---

pom.xml

Ratis build sets Surefire fork timeout to 10 minutes:
https://github.com/apache/ratis/blob/58671923e78a10d5c6a7d49a06e2d95690d5e9bb/pom.xml#L637
Yet, sometimes Surefire fork is not killed, check runs until Github workflow is cancelled:
```
Tue, 12 Mar 2024 19:43:11 GMT [INFO] Running org.apache.ratis.netty.TestRaftWithNetty
Wed, 13 Mar 2024 01:40:25 GMT Error: The operation was canceled.
```
The problem is that:
> Since 3.0.0-M4 the process checkers are disabled. ([doc](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#enableProcessChecker))
Changes in this PR (and links to similar change in Ozone):
1. Enable process checkers to apply the fork timeout ([HDDS-10174](https://issues.apache.org/jira/browse/HDDS-10174))
2. Downgrade to Surefire 3.0.0-M4 due to: …

RATIS-2073. Enable Surefire process checkers

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyClient.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyRpcProxy.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyUtils.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java

RATIS-2074. Intermittent fork timeout in TestRaftWithNetty#testBasicAppendEntriesKillLeader.

---

.github/workflows/post-commit.yml

Remove the temporary workaround added in RATIS-1361.
https://issues.apache.org/jira/browse/RATIS-2087
CI:
https://github.com/adoroszlai/ratis/actions/runs/9033512372

RATIS-2087. Remove workaround for GitHub reverse DNS issue

---

.asf.yaml

Ratis PR descriptions sometimes reference Ozone Jira issues. It would be nice to automatically link these, similar to how it is already done for RATIS.
https://issues.apache.org/jira/browse/RATIS-2086
Ozone has similar config:
https://github.com/apache/ozone/blob/6487de7defc87f6456e986100de07620f88b1015/.asf.yaml#L25-L29

RATIS-2086. Autolink Ozone issues in PRs

---

ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java

When getEntry gets timed out, the StateMachine reference count is released twice.
We should not release the reference inside getEntry.
See RATIS-2077.
https://issues.apache.org/jira/browse/RATIS-2077
CI

RATIS-2077. Timedout StateMachine retainRead is released twice

---

.github/workflows/post-commit.yml

Add Java 17 and 21 to the _compile_ check's matrix as a basic smoketest of compatibility.
Match `javac.version` with JDK (see HDDS-7633 for a possible issue).
https://issues.apache.org/jira/browse/RATIS-2085
CI:
https://github.com/adoroszlai/ratis/actions/runs/9032668282

RATIS-2085. Compile Ratis with JDK 17/21 in CI

---

pom.xml

Bump `ratis-thirdparty` to 1.0.6.
https://issues.apache.org/jira/browse/RATIS-2090
CI:
https://github.com/adoroszlai/ratis/actions/runs/9077754904

RATIS-2090. Bump ratis-thirdparty to 1.0.6

---

ratis-server-api/src/main/java/org/apache/ratis/statemachine/StateMachine.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

Currently there is no way for application to get notified once the RaftServerProxy is close.
This task is to add a close callback support to RaftServerProxy. 
Motivated by HDDS-10749. 
https://issues.apache.org/jira/browse/RATIS-2066
integration test with Ozone.

RATIS-2066. RaftServerProxy supports close callback

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java

See RATIS-2093.
https://issues.apache.org/jira/browse/RATIS-2093

RATIS-2093. Decouple metadata and configuration entries from appendEntries buffer for stateMachineCache'

---

ratis-server-api/src/main/java/org/apache/ratis/server/protocol/TermIndex.java

See [RATIS-2101](https://issues.apache.org/jira/browse/RATIS-2101).
https://issues.apache.org/jira/browse/RATIS-2101
No additional tests needed.

RATIS-2101. Move TermIndex.PRIVATE_CACHE to Util.CACHE

---

ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderDaemon.java

Currently, the closeFuture only completes after the LogAppenderDaemon has started. However, when closing from the NEW state, the transition is NEW -> CLOSED, and the LogAppenderDaemon was not started.
https://issues.apache.org/jira/browse/RATIS-2100

RATIS-2100. The `closeFuture` never completed while closing from the `NEW` state

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/NotReplicatedException.java
ratis-server/src/test/java/org/apache/ratis/WatchRequestTests.java

In Ozone's XceiverClientRatis#watchForCommit, there are two watch commits request with different ReplicationLevel
1. Watch for ALL_COMMITTED 
2. Watch for MAJORITY_COMMITTED (If the previous watch threw an exception)
Based on the second watch request, the client will remove some failed datanode UUID from the commitInfoMap.
The second watch might not be necessary since the entries in AbstractCommitWatcher.commitIndexMap implies that the PutBlock request has been committed to the majority of the servers. Therefore, another MAJORITY_COMMITTED watch might not be necessary. From my understanding, the second MAJORITY_COMMITTED only serves to gain information to remove entries from commitInfoMap.
If the first watch failed with NotReplicatedException, we might be able to remove the need to a …

RATIS-2089. Add CommitInfoProto in NotReplicatedException

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ConfigurationManager.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLeaderInstallSnapshot.java

1. Follower reply ALREADY_INSTALLED when install old snapshots from leader.
2. Configuration Manager now will replace the original conf with new conf if they share the same (uncommitted) index.
https://issues.apache.org/jira/projects/RATIS/issues/RATIS-2084?filter=allopenissues
New unit tests. Before the patch the IllegalStateException can be 100% reproduced in the unit test.

RATIS-2084. Follower reply ALREADY_INSTALLED when install old snapshots from leader

---

ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedObject.java
ratis-examples/src/main/java/org/apache/ratis/examples/filestore/FileStoreStateMachine.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/TransactionContext.java
ratis-test/src/test/java/org/apache/ratis/statemachine/TestStateMachine.java

As discuss in RATIS-2094, the usage of TransactionContext's `getStateMachineLogEntry` and `getStateMachineContext` may cause corruptions when zero-copy is enabled.
1. For stateMachineContext, when TransactionContext is created from `startTransaction(LogEntryProto)`, the `stateMachineContext` should  not be created/parsed directly from the LogEntryProto's content (as it would directly refer to the zero-copy buffer without reference count). We should copy `logData` to create this context object. The change in `FileStoreStateMachine` demonstrate this.
2. For `stateMachineLogEntry`, it should be used internally in TransactionContextImpl to form the LogEntryProto. Any subsequent access to `stateMachineLogEntry` should happen via the logEntry, aka via `TransactionContext.getLogEntryRef`. Hence, …

RATIS-2094. Avoid corruptions from TransactionContext's stateMachineLogEntry and stateMachineContext.

---

ratis-client/src/main/java/org/apache/ratis/client/RaftClientConfigKeys.java
ratis-docs/src/site/markdown/configurations.md

Add config doc for `RaftClient`. Like what RATIS-1732 did for `RaftServer`.
https://issues.apache.org/jira/browse/RATIS-2106
- n/a

RATIS-2106. Add configuration reference for RaftClient

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java

RaftLogBase#updateCommitIndex returns true regardless whether commit index is actually increased (RaftLogIndex#updateIncreasingly returns true). This can cause unnecessary StateMachineUpdater notification
We can change it so that RaftLogBase#updateCommitIndex only returns true if commit index is actually increased. 
Note: For leader ServerState#updateCommitIndex is called only if there are entries to commit (i.e. majority > oldLasCommitted), so RaftLogBase#updateCommitIndex should increase the commit index of leader.
https://issues.apache.org/jira/browse/RATIS-2109

RATIS-2109. RaftLogBase#updateCommitIndex should return true only if commitIndex is increased

---

.github/workflows/repeat-test.yml
dev-support/checks/unit.sh

Improve `repeat-test` workflow:
* Skip artifact upload if all iterations passed
* Rename artifact using run number/ID
* Fail fast if no tests were run (e.g. due to workflow triggered for non-existent test class)
https://issues.apache.org/jira/browse/RATIS-2112
`repeat-test` run without failures:
https://github.com/adoroszlai/ratis/actions/runs/9486024280
`repeat-test` run with non-existent test class:
https://github.com/adoroszlai/ratis/actions/runs/9486291646

RATIS-2112. Improve repeat-test workflow

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

`SegmentedRaftLogWorker` can queue LogEntries without retaining a reference counter. This is caught during testing zero-copy with Apache Ozone. Datanode crashes to corruption caused by SegmentedRaftLogWorker threads.
https://issues.apache.org/jira/browse/RATIS-2114
CI.

RATIS-2114. Corruption due to SegmentedRaftLogWorker queues LogEntry without reference counter

---

pom.xml
ratis-assembly/src/main/assembly/bin.xml

Create and publish Software Bill of Materials (SBOM) for Ratis.
https://cwiki.apache.org/confluence/display/SECURITY/Software+Bill+of+Materials+SBOM
https://issues.apache.org/jira/browse/RATIS-2110
```
$ mvn -DskipTests -Prelease clean package
...
[INFO] --- cyclonedx-maven-plugin:2.8.0:makeAggregateBom (default) @ ratis ---
[INFO] CycloneDX: Resolving Aggregated Dependencies
[INFO] CycloneDX: Creating BOM version 1.5 with 30 component(s)
[INFO] CycloneDX: Writing and validating BOM (XML): target/bom.xml
[INFO]            attaching as ratis-3.1.0-SNAPSHOT-cyclonedx.xml
[INFO] CycloneDX: Writing and validating BOM (JSON): target/bom.json
[INFO]            attaching as ratis-3.1.0-SNAPSHOT-cyclonedx.json
...
$ tar tzvf ratis-assembly/target/apache-ratis-3.1.0-SNAPSHOT-bin.tar.gz | grep bom …
```

RATIS-2110. Publish SBOM artifacts

---

.github/workflows/post-commit.yml
dev-support/make_rc.sh
ratis-assembly/pom.xml

RATIS-1660 added explicit executions of `maven-assembly-plugin` to build binary and source tarballs.  Since they are bound to the `package` phase, we no longer need to manually include `assembly:single` in the command to build Ratis.
https://issues.apache.org/jira/browse/RATIS-2117
Verified that both source and binary tarballs are still created:
https://github.com/adoroszlai/ratis/actions/runs/9660881857/job/26647380234#step:5:1950
https://github.com/adoroszlai/ratis/actions/runs/9660881857/job/26647380234#step:5:1964
Additional validation by `compile` check, which builds Ratis using contents from the source tarball.

RATIS-2117. No need for manual assembly:single execution

---

pom.xml
ratis-assembly/pom.xml
ratis-client/pom.xml
ratis-common/pom.xml
ratis-docs/pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml
ratis-grpc/pom.xml
ratis-metrics-api/pom.xml
ratis-metrics-default/pom.xml
ratis-metrics-dropwizard3/pom.xml
ratis-netty/pom.xml
ratis-proto/pom.xml
ratis-replicated-map/pom.xml
ratis-resource-bundle/pom.xml
ratis-server-api/pom.xml
ratis-server/pom.xml
ratis-shell/pom.xml
ratis-test/pom.xml
ratis-tools/pom.xml

Ratis 3.1.0 was released, we should bump version on `master` to `3.2.0-SNAPSHOT`.
https://issues.apache.org/jira/browse/RATIS-2120
```
$ mvn -DskipTests clean package
...
[INFO] Reactor Summary for Apache Ratis 3.2.0-SNAPSHOT:
[INFO] 
[INFO] Apache Ratis ....................................... SUCCESS [  0.748 s]
[INFO] Apache Ratis Documentation ......................... SUCCESS [  0.223 s]
[INFO] Apache Ratis Protocols ............................. SUCCESS [  2.723 s]
[INFO] Apache Ratis Common ................................ SUCCESS [  1.623 s]
[INFO] Apache Ratis Client ................................ SUCCESS [  0.667 s]
[INFO] Apache Ratis Server API ............................ SUCCESS [  0.643 s]
[INFO] Apache Ratis Metrics API ........................... SUCCESS [  0.345 s] …
```

RATIS-2120. Bump version after 3.1.0 release

---

pom.xml

Java 9 introduced new [`javac` option `--release`](https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html#option-release), which helps ensure compatibility with the given Java version ([blog with great explanation](https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/)).  The goal of this change is to set this option when compiling with JDK 9+, instead of `--source` and `--target`.
`--release` expects version without the old-style `1.` prefix (i.e. `8` instead of `1.8`).  `maven-enforcer-plugin` [added support for the same](https://issues.apache.org/jira/browse/MENFORCER-440) in version 3.2.1, so we also need to bump the plugin.
https://issues.apache.org/jira/browse/RATIS-2121
Compiled Ratis with JDK versions 8, 11, 17, targeting versions up to that of …

RATIS-2121. Set javac --release when compiling with JDK 9+

---

ratis-common/src/main/java/org/apache/ratis/util/DataBlockingQueue.java
ratis-common/src/main/java/org/apache/ratis/util/DataQueue.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

This pull request fixes the issue where RaftServerImpl.appendEntries may be blocked indefinitely.
https://issues.apache.org/jira/browse/RATIS-2116
unit tests

RATIS-2116. Fix the issue where RaftServerImpl.appendEntries may be blocked indefinitely

---

.github/workflows/post-commit.yml
dev-support/checks/repro.sh
pom.xml
src/main/resources/ratis-version.properties

`buildnumber-maven-plugin`'s `create-metadata` goal generates a properties file similar to:
```
#Created by build system. Do not modify
#Fri Dec 29 09:18:39 CET 2023
version=3.0.1
revision=Unknown
name=Apache Ratis Common
timestamp=1703837919371
```
Time of build should be omitted, because it makes builds non-reproducible.  The same set of sources and build instructions result in different output each time.
However, `buildnumber-maven-plugin` doesn't seem to have any way to configure the properties to be included/omitted.  We can replace it with a custom properties file.  `hadoop-maven-plugins` is used to get the SCM revision.
https://issues.apache.org/jira/browse/RATIS-1840
Added a step in `compile` check to verify build is reproducible.
CI: …

RATIS-1840. Avoid including build timestamp in artifacts

---

content/post/3.1.0.md

Update Ratis website with announcement for 3.0.1 bugfix release.
https://issues.apache.org/jira/browse/RATIS-1992

RATIS-2122. Update website with Ratis 3.1.0 release

---

content/post/2.0.0.md
content/post/2.1.0.md
content/post/2.2.0.md
content/post/2.3.0.md
content/post/2.4.0.md
content/post/2.4.1.md
content/post/2.5.0.md
content/post/2.5.1.md
content/post/3.0.0.md
content/post/3.1.0.md

List only 3.0.1 and 3.1.0 in [Downloads](https://ratis.apache.org/downloads.html) page.
https://issues.apache.org/jira/browse/RATIS-2123
```
hugo serve
open http://localhost:1313
```

RATIS-2123. Remove old releases from website

---

ratis-common/src/main/java/org/apache/ratis/util/NetUtils.java

Currently, if the address is IPv6, NetUtils.address2String always surrounds it with '[]'.
This should be done only when the input is an IP string, and not for hostnames (which have an IPv6 address)
RATIS-2131
Manual testing

RATIS-2131: Surround with [] only if hostName is a IPv6 string

---

ratis-common/src/main/java/org/apache/ratis/protocol/exceptions/NotLeaderException.java

Optimize NotLeaderException message
https://issues.apache.org/jira/browse/RATIS-2126
Original unit tests suite

RATIS-2126. Optimize NotLeaderException message

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/client/GrpcClientProtocolClient.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolClient.java

Referring to this [comment ](https://github.com/apache/ratis-thirdparty/pull/53#issuecomment-2262233350) , Ratis should not use http proxy while setting up grpc/netty clients if configured.
Reference : https://github.com/grpc/grpc-java/issues/5600#issuecomment-486680942
https://issues.apache.org/jira/browse/RATIS-2133
Verified by building & replacing the ratis-grpc jar and trying out an Ozone  write  with jvm args set for http proxy. 
Also verified via unit test using  
```
mvn -Dtest=TestLeaderElectionWithGrpc \
-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8080 -Djava.net.useSystemProxies=true \
clean test
```
Before the fix: 
```bash
incubator-ratis % cat ratis-test/target/surefire-reports/org.apache.ratis.grpc.TestLeaderElectionWithGrpc- …
```

RATIS-2133. Ignore http proxy for grpc client & server

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java

`TestLeaderInstallSnapshot.testInstallSnapshotLeaderSwitch` calls `cluster.shutdown` twice (one in the test method and another in `runWithNewCluster`).  The second shutdown seems to create weird problems with leak detection. 
https://issues.apache.org/jira/browse/RATIS-2104
Run the test 30 times and all green.

RATIS-2104. Double shutdown in TestLeaderInstallSnapshot.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java

Now, RaftLog appends a metadata entry with the lastCommitIndex and checks whether the entry at the lastCommitIndex is neither a metadata entry nor an entry with a smaller commit index.
However, RaftLog doesn't always log metadata entries in order. Sometimes, it misses some commit indexes. For example:
STATEMACHINELOGENTRY(1, 1)
STATEMACHINELOGENTRY(1, 2)
METADATAENTRY(commitIndex: 1)
A METADATAENTRY is lost.
The lastCommitIndex in the METADATAENTRY and  is a metadata entry, RaftLog won't append it.
https://issues.apache.org/jira/browse/RATIS-2134
CI:
https://github.com/chungen0126/ratis/actions/runs/10233933768

RATIS-2134.  `logMetadata` could miss appending the `metadataEntry` with the lastCommitIndex

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java
ratis-server/src/test/java/org/apache/ratis/RetryCacheTests.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestLeaderInstallSnapshotWithGrpc.java

RATIS-2115. Fix flaky RetryCacheTests and InstallSnapshotFromLeaderTests.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2138)

RATIS-2138 Remove uncessary error log in JVMPauseMonitor When GC is serious

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2144)

RATIS-2144 SegmentedRaftLogWorker should close the stream before releasing the buffer.

---

ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

see: https://issues.apache.org/jira/browse/RATIS-2145

RATIS-2145. Follower hangs until the next trigger to take a snapshot.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

see [jira](https://issues.apache.org/jira/browse/RATIS-2146?orderby=created+DESC%2C+priority+DESC%2C+updated+DESC)

RATIS-2146 Fixed possible issues caused by concurrent deletion and election when member changes

---

ratis-assembly/src/main/assembly/src.xml

`ratis-version.properties` added in RATIS-1840 needs to be included in the `src` assembly.
https://issues.apache.org/jira/browse/RATIS-2153
```
$ mvn -DskipTests clean verify
...
$ tar tzvf ratis-assembly/target/ratis-assembly-*-src.tar.gz | grep 'src/src'
drwxr-xr-x root/root         0 2023-11-19 15:23 apache-ratis-3.2.0-SNAPSHOT-src/src/
drwxr-xr-x root/root         0 2023-11-19 15:23 apache-ratis-3.2.0-SNAPSHOT-src/src/main/
drwxr-xr-x root/root         0 2023-11-19 15:23 apache-ratis-3.2.0-SNAPSHOT-src/src/main/resources/
-rw-r--r-- root/root       873 2023-11-19 15:23 apache-ratis-3.2.0-SNAPSHOT-src/src/main/resources/ratis-version.properties
```
CI:
https://github.com/adoroszlai/ratis/actions/runs/10778262480

RATIS-2153. ratis-version.properties missing from src bundle

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

Previous PR see https://github.com/apache/ratis/pull/1133 
issue see https://issues.apache.org/jira/browse/RATIS-2138
This PR is the follow-up to 2138
This PR related issue: https://issues.apache.org/jira/browse/RATIS-2154

RATIS-2154.  The old leader may send appendEntries after term changed,

---

ratis-common/src/main/java/org/apache/ratis/util/AwaitForSignal.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java

In `GrpcLogAppender`, it waits for signal at the end of `notifyInstallSnapshot` as following.
https://github.com/apache/ratis/blob/3e38e6da1053c1b522d51123b8ac88ea15e60f94/ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java#L825-L831
However, checking whether the `InstallSnapshotResponseHandler` is done and the call `AwaitForSignal.await()` are not atomic. This creates a potential race condition where InstallSnapshotResponseHandler.close() could finish after the check but before the wait, causing that `GrpcLogAppender` is still waiting even though `InstallSnapshotResponseHandler` has already completed, leading to timeout. 
Things change in the patch:
Move the done check inside the lock in AwaitForSignal to ensure atomicity. …

RATIS-2152. GrpcLogAppender stucks while sending an installSnapshot notification request

---

dev-support/make_rc.sh

see [jira](https://issues.apache.org/jira/browse/RATIS-2150)

RATIS-2150. No need for manual assembly:single execution when mvn deploy

---

ratis-server-api/src/main/java/org/apache/ratis/server/protocol/TermIndex.java
ratis-server/src/main/java/org/apache/ratis/statemachine/impl/BaseStateMachine.java

In the Ratis project and other projects, the default value of TermIndex is used. Here we create a default value for TermIndex.
https://issues.apache.org/jira/browse/RATIS-2167
Make sure UT passes.

RATIS-2167. Add default value in TermIndex

---

pom.xml

RATIS-2169. mvnw test: Corrupted STDOUT by directly writing to native stream in forked JVM 1

---

ratis-client/src/main/java/org/apache/ratis/client/impl/ClientProtoUtils.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerProtoUtils.java

For the readIndexRequestProto, we don't need to set message member 
In readIndex, we did not use clientRequest.message, so we do not need to serialize the message
https://issues.apache.org/jira/browse/RATIS-2165

RATIS-2165. Do not include RaftClientRequest Message in ReadIndexRequest

---

ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java

Fix legacy problems with #1145 
https://issues.apache.org/jira/browse/RATIS-2166

RATIS-2166. Update nextChunkIndex when snapshot is ALREADY_INSTALLED

---

ratis-common/src/main/java/org/apache/ratis/util/DataBlockingQueue.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcClientProtocolService.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java
ratis-server/src/test/java/org/apache/ratis/statemachine/impl/SimpleStateMachine4Testing.java

RATIS-2151
This is to fix the following problems described in https://github.com/apache/ratis/pull/1156
3. `GrpcClientProtocolService.UnorderedRequestStreamObserver.processClientRequest(..)` should use try-finally.
4. `GrpcLogAppender.appendLog(..)` calls `release()` incorrectly for exception.
6. `LogSegment` cache can release an entry multiple times.
7. `LogSegment.loadCache(..)` should call `retain()` for cache hit.
8. `SegmentedRaftLog.retainLog(..)`: between getting the entry and calling `retain()`, the entry can be released.  The "fail to retain" exception, if there is any, can be ignored since It is the same as a cache miss.  See #1153
9. `SegmentedRaftLog.retainEntryWithData(..)` should release for exception.
10. Test bug: the log entries stored in `SimpleStateMachine4Testing` can …

RATIS-2151. TestRaftWithGrpc keeps failing with zero-copy.

---

ratis-common/src/main/java/org/apache/ratis/util/CodeInjectionForTesting.java
ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java

Move server.isRunning () check from LeaderElection to FollowerState to ensure that the server is ready when it becomes a candidate
https://issues.apache.org/jira/browse/RATIS-2172

RATIS-2172. RaftServer may lose FollowerState

---

ratis-common/src/main/java/org/apache/ratis/util/LeakDetector.java
ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedLeakDetector.java
ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedObject.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java

RATIS-2164
This is mainly fixing the first two problem mentioned in https://github.com/apache/ratis/pull/1156
1. `LeakDetector`: asserted allLeaks is non-empty but printed "allLeaks.size = 0"
- Another bug: Trackers can be considered as a leak without calling `retain()`. Without calling `retain()` at all, it is not a leak.
2. `SimpleTracing` and `AdvancedTracing`: the methods should be synchronized.
- Minor presentation problem: `AdvancedTracing` should have a single track list instead of two lists: `retainsTraces` and `releaseTraces`.

RATIS-2164. LeakDetector has a race condition.

---

ratis-grpc/pom.xml
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcConfigKeys.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcFactory.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServices.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServicesImpl.java
ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
ratis-test/src/test/java/org/apache/ratis/grpc/TestCustomGrpcServices.java
ratis-test/src/test/java/org/apache/ratis/grpc/server/TestGrpcMessageMetrics.java

RATIS-2168. Support custom gRPC services.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

`RaftServerImpl` builds `LogInfoProto` to create `GroupInfoReply` for `RaftServer#getGroupInfo` in [RATIS-2031](https://issues.apache.org/jira/browse/RATIS-2031), which causes `NullPointerException` for null latest snapshot as follows:
```
[info] Test org.apache.celeborn.service.deploy.master.clustermeta.ha.MasterRatisServerSuiteJ.testIsLeader started
24/10/24 08:16:30,295 ERROR [pool-1-thread-1] HARaftServer: Failed to retrieve RaftPeerRole. Setting cached role to UNRECOGNIZED and resetting leader info.
java.io.IOException: java.lang.NullPointerException
at org.apache.ratis.util.IOUtils.asIOException(IOUtils.java:56)
at org.apache.ratis.server.impl.RaftServerImpl.waitForReply(RaftServerImpl.java:1148)
at org.apache.ratis.server.impl.RaftServerProxy.getGroupInfo(RaftServerProxy.java:607) …
```

RATIS-2179. Fix NPE in RaftServerImpl.getLogInfo

---

ratis-common/src/main/java/org/apache/ratis/util/SizeInBytes.java
ratis-common/src/main/java/org/apache/ratis/util/TimeDuration.java
ratis-server-api/src/main/java/org/apache/ratis/statemachine/TransactionContext.java
ratis-server/src/main/java/org/apache/ratis/server/impl/PendingRequest.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftConfigurationImpl.java

In Ratis, some of the messaging for Objects.requireNonNull() is not clear enough. The purpose of this PR is to try to fix that.
https://issues.apache.org/jira/browse/RATIS-2182
ci: 
https://github.com/jianghuazhu/ratis/actions/runs/11590363184

RATIS-2182. Fix some Objects.requireNonNull messages

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java

see #RATIS-2177
In addition, I made some improvements to TruncateSegment.maxEndIndex (), because segments are sorted by index from largest to smallest, so returning the endIndex of the first segment is enough.

RATIS-2177. Delete segmentLog from small to large according to logIndex

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLog.java

Please refer to https://issues.apache.org/jira/browse/RATIS-2186
https://issues.apache.org/jira/browse/RATIS-2186
Unit test.

RATIS-2186. Raft log should not purge index lower than the log start index

---

ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java

See https://issues.apache.org/jira/browse/RATIS-2189
Checked using `jmap -histo:live` that `DirectByteBuffer` are not created when using the following arguments:
```
-Dorg.apache.ratis.thirdparty.io.netty.noPreferDirect=true -Dorg.apache.ratis.thirdparty.io.netty.noUnsafe=true -Dorg.apache.ratis.thirdparty.io.netty.allocator.numDirectArenas=0
```

RATIS-2189. Use ByteBufAllocator#ioBuffer in NettyDataStreamUtils

---

ratis-examples/src/test/java/org/apache/ratis/examples/filestore/FileStoreStreamingBaseTest.java
ratis-netty/src/main/java/org/apache/ratis/netty/NettyDataStreamUtils.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamClusterTests.java
ratis-test/src/test/java/org/apache/ratis/datastream/DataStreamTestUtils.java

Similar to LeakDetector#assertNoLeaks in MiniRaftCluster, we can also add the Netty leak detector in tests as specified in https://netty.io/wiki/reference-counted-objects.html#wiki-h2-9 to ensure that all ByteBuf are released.
https://issues.apache.org/jira/browse/RATIS-2191
Intentionally add leak add check that `IllegalStateException` is thrown: https://github.com/ivandika3/ratis/actions/runs/11871018319/job/33121223662

RATIS-2191. Add ResourceLeakDetector to Netty tests

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerProxy.java

Found OverlappingFileLockExceptio when restarting RaftServer. 
When closing `RaftServerProxy`, all `RaftServerImpl` in `implMap` should be closed. However, if there was a new `RaftServerImpl` started by `RaftServerProxy#groupManagementAsync`, it would not be closed properly. The log will say that the new `RaftServerImpl` has been closed, but its raft store is still being initialised by `implExecutor`.
Things change:
- Closing implExecutor before closing implMap prevents RaftServerImpl from starting after it is closed by implMap.
https://issues.apache.org/jira/browse/RATIS-2194
https://github.com/chungen0126/ratis/actions/runs/12008556158

RATIS-2194. FileLock didn't unlock properly

---

ratis-common/src/main/java/org/apache/ratis/util/LogUtils.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/GrpcUtil.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcAdminProtocolService.java

RATIS-2185: Improve gRPC log messages debugability.  In particular, we fix the followings:
- Some exceptions in `GrpcAdminProtocolService` are not printed.
- The cause exceptions are not printed in `GrpcUtil.warn(..)`.

RATIS-2185. Improve gRPC log messages debugability.

---

dev-support/make_rc.sh

During release process, Ratis is currently re-built from scratch in several steps.  Outputs of various steps are published to two different locations.
1. `prepare-src`: builds everything, installs artifacts (jars, tarballs, etc.) in local repo
2. `prepare-bin`: verifies that Ratis can be built from the contents of the source tarball created by `prepare-src`
3. `assembly`: adds src tarball from step (1) and binary tarball from step (2) to Subversion
4. `publish-mvn`: publish artifacts to the Maven repo
Problem: Both `prepare-bin` and `publish-mvn` re-build Ratis and install build artifacts to the local repo.
Result:
- Binary tarball in Subversion and Maven repo are different, created by `prepare-bin` and `publish-mvn`, respectively.
- Jars in binary tarball and Maven repo are different.
- …

RATIS-2206. Jars in Maven repo and binary tarball are not the same

---

dev-support/make_rc.sh

RATIS-2206 introduced a problem in the release process: plain `deploy:deploy` fails for modules with `packaging=jar`.  Previous test has not revealed this, because the first module is a `pom`, deployment was attempted, and it was expected to fail due to lack of authentication.
It turns out we cannot skip re-build of the project.  However, we can reorder steps to ensure items published to Maven and Subversions are consistent.
(Alternatively we could publish files one-by-one using `deploy:deploy-file`, but it's error-prone.)
I think it is safe to publish to the Maven staging repo before adding files to Subversion locally, since it can be discarded if needed.  So the order is now:
1. `prepare-src`
2. `verify-bin` (renamed from `prepare-bin` to better reflect its purpose)
3. `publish-mvn`
4. …

RATIS-2211. publish-mvn fails with: ... did not assign a file to the build artifact

---

pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml

1. Bump `maven-shade-plugin` from 3.2.4 to 3.6.0 (current latest), since versions before 3.5.3 may have non-reproducible output:
```bash
$ mvn artifact:check-buildplan
...
[INFO] --- artifact:3.5.3:check-buildplan (default-cli) @ ratis-examples ---
[ERROR] plugin with non-reproducible output: org.apache.maven.plugins:maven-shade-plugin:3.2.4, require minimum 3.5.3
```
2. Disable creation of `dependency-reduced-pom.xml` (affects the `ratis-examples` and `ratis-experiments` modules).  These files are written to `dependencyReducedPomLocation`.  The problem is that
> setting a value for this parameter with a directory other than `${basedir}` will change the value of `${basedir}` for all executions that come after the shade execution. This is often not what you want. This is considered an open …

RATIS-2216. Bump maven-shade-plugin to 3.6.0

---

pom.xml
ratis-examples/pom.xml
ratis-experiments/pom.xml

Build uses `copy-rename-maven-plugin` to overwrite original jar with shaded one in `ratis-examples` (and experiments).  `maven-shade-plugin` can do that, so we can remove usage of `copy-rename-maven-plugin`.
> `<shadedArtifactAttached>`
> Defines whether the shaded artifact should be attached as classifier to the original artifact. If false, the shaded jar will be the main artifact of the project
> ([source](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#shadedArtifactAttached))
https://issues.apache.org/jira/browse/RATIS-2222
Built locally:
```
$ ./mvnw -Prelease -DskipTests -Dmaven.javadoc.skip clean verify
...
[INFO] --- shade:3.6.0:shade (default) @ ratis-examples ---
...
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing …
```

RATIS-2222. Remove copy-rename-maven-plugin usage

---

ratis-common/src/main/java/org/apache/ratis/util/LeakDetector.java
ratis-common/src/test/java/org/apache/ratis/BaseTest.java

> After the first test case has failed, the leak detector will fail the following test cases (even if there are no new leaks) since it won't reset the leak trackers. ([comment](https://issues.apache.org/jira/browse/RATIS-2184?focusedCommentId=17894661&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17894661))
We should skip further tests to avoid wasting time.
(I'm guessing JUnit4 tests may not benefit from this, since it's added in a JUnit5 hook method.)
https://issues.apache.org/jira/browse/RATIS-2220
10x10 [run](https://github.com/adoroszlai/ratis/actions/runs/12443701223) of `TestRaftWithGrpc`, as expected has many failures.
In each case at most 1 test failed with error, various number of other tests were skipped:
```
[ERROR] Tests run: 11, Failures: 0, …
```

RATIS-2220. Skip further tests after leak detected

---

ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java

`TestRaftWithGrpc#testWithLoad` is run 3 times, twice with the same value for `raft.grpc.server.heartbeat.channel`.  This happens because `testWithLoad(boolean)` no longer overrides `testWithLoad` from parent class after RATIS-1976.
```
$ mvn -am -pl :ratis-test clean test -Dtest='TestRaftWithGrpc' -Dsurefire.reportFormat=plain
...
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 174.463 s - in org.apache.ratis.grpc.TestRaftWithGrpc
org.apache.ratis.grpc.TestRaftWithGrpc.testStateMachineMetrics  Time elapsed: 3.415 s
org.apache.ratis.grpc.TestRaftWithGrpc.testBasicAppendEntries  Time elapsed: 12.339 s
org.apache.ratis.grpc.TestRaftWithGrpc.testBasicAppendEntriesKillLeader  Time elapsed: 11.075 s
org.apache.ratis.grpc.TestRaftWithGrpc.testOldLeaderCommit  Time elapsed: …
```

RATIS-2219. Remove duplicate test case from TestRaftWithGrpc

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

See RATIS-2225
```java
//RaftServerImpl.submitClientRequestAsync
try {
assertLifeCycleState(LifeCycle.States.RUNNING);
} catch (ServerNotReadyException e) {
final RaftClientReply reply = newExceptionReply(request, e);
requestRef.release();
return CompletableFuture.completedFuture(reply);
}
```
In the code above,
- it may catch `ServerNotReadyException` when the server is shutting down.
- It calls `newExceptionReply` which may throw another exception.
Then, requestRef.release() is not called.
Also, when a unchecked exception is thrown, it won't be logged.

RATIS-2225. RaftClientRequest leak in RaftServerImpl.

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/post-commit.yml
dev-support/checks/compile.sh

Reduce duplication in CI workflow.
- Create a reusable workflow (`check.yml`) for a single, generic check.
- Refactor existing checks in `post-commit.yml` (except `coverage`, which needs extra tokens) to call the reusable one.  Minor changes as implementation detail:
- Separate `repro` check from `compile`.
- Create separate `compile.sh` for `compile` check.
- Group simple checks (`author`, `checkstyle`, etc.) with matrix strategy as `basic`.
- Split existing `post-commit.yml` into:
- `ci.yml`, has most of the logic, is triggered by workflow call
- `post-commit.yml`, triggered by `push`/`pull_request`, simply calls `ci.yml`
This split is not strictly required, but I think the way GitHub UI displays workflow runs is better this way (runs: …

RATIS-2210. Reduce duplication in CI workflow

---

.gitignore
.mvn/develocity.xml
.mvn/extensions.xml

> The [Develocity] Build Cache speeds up your builds by reusing outputs from any previous build
> [The] local Build Cache [...] allows other subsequent builds on the same machine to reuse the outputs whenever they execute a goal with the same inputs.
> ([source](https://docs.gradle.com/develocity/maven-extension/current/#using_the_build_cache))
This PR enables cache for local builds, but not for CI builds.
Develocity can also publish build scans (information about build/test runs), which could be enabled in a follow-up task.
https://issues.apache.org/jira/browse/RATIS-2226
First build with cache (can be reproduced later by adding `-Ddevelocity.cache.local.enabled=false`):
```
$ ./mvnw -Prelease -DskipTests clean verify
...
[INFO] BUILD SUCCESS
[INFO] …
```

RATIS-2226. Enable Develocity local build cache

---

ratis-client/src/main/java/org/apache/ratis/client/impl/DataStreamClientImpl.java
ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

During perssure test using ratis streaming, we found direct memory leak.
After days of debugging, we found it's caused by uncleaned remote stream.
https://issues.apache.org/jira/browse/RATIS-2197
Local performance test.

RATIS-2197. Clean remote stream to resolve direct memory leak

---

ratis-examples/src/main/resources/log4j.properties

made `ratis-example` logs as info level
https://issues.apache.org/jira/browse/RATIS-2200
(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

RATIS-2200. Make Ratis example log at INFO level

---

ratis-common/src/main/java/org/apache/ratis/util/AutoCloseableLock.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java

See https://issues.apache.org/jira/browse/RATIS-2234.
See discussion at https://issues.apache.org/jira/browse/RATIS-2208
Thanks @szetszwo for the patch provided!

RATIS-2234. Remove lock race between heartbeat and append log channels

---

ratis-server/src/main/java/org/apache/ratis/server/leader/LogAppenderBase.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLog.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestLogSegment.java

RATIS-2228
- Add a new `EntryBuffer` class for the buffer queue and the ref map.
- Remove the `buffer` field from `LogAppenderBase`.
- Add a method for readLogEntries and a method for pollList.
- Change `LogEntryLoader` to not extending guava `CacheLoader`.
- Fix a bug in `LogEntryLoader.load` -- it should re-throw an exception.
- Pass `TermIndex` instead of `LogRecord` in `LogEntryLoader`

RATIS-2228. Refactor the offered map in LogAppenderBase.nextAppendEntriesRequest

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-server/src/test/java/org/apache/ratis/server/simulation/SimulatedRpc.java
ratis-test/src/test/java/org/apache/ratis/conf/TestConfUtils.java

RATIS-2229. Do not print the same conf values multiple times.

---

ratis-docs/src/site/markdown/configurations.md
ratis-server-api/src/main/java/org/apache/ratis/server/RaftServerConfigKeys.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

See https://issues.apache.org/jira/browse/RATIS-2233

RATIS-2233. make NOPROGRESS timeout configurable

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

See https://issues.apache.org/jira/browse/RATIS-2235
See the discussion at https://issues.apache.org/jira/browse/RATIS-2208

RATIS-2235. Allow only one thread to perform appendLog 

---

pom.xml
ratis-resource-bundle/src/main/resources/META-INF/LICENSE.vm
ratis-resource-bundle/src/main/resources/META-INF/NOTICE.vm

- Bump `maven-remote-resources-plugin` to 3.3.0, which fixes an intermittent reproducibility problem (MRRESOURCES-150).
- Replace `-` with `_` in variable names in the templates, because `-` is causes error with newer versions of the plugin.  (BTW, are these templates inherited from Hadoop?  Most of the dependencies mentioned seem to be unused in Ratis.)
https://issues.apache.org/jira/browse/RATIS-2215
CI:
https://github.com/adoroszlai/ratis/actions/runs/12657963122

RATIS-2215. Bump maven-remote-resources-plugin to 3.3.0

---

ratis-server-api/src/main/java/org/apache/ratis/server/DivisionInfo.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java

see https://issues.apache.org/jira/browse/RATIS-2237

RATIS-2237 Add getFollowerMatchIndices interface for DivisionInfo

---

.github/workflows/check.yml
.mvn/develocity.xml
.mvn/extensions.xml

Publish data about CI builds to `develocity.apache.org`.
Downgrade `develocity-maven-extension`, because the server at `develocity.apache.org` [does not yet support 1.23](https://github.com/apache/ozone/pull/7701#discussion_r1916538894).
https://issues.apache.org/jira/browse/RATIS-2239
Similar config file is already used for Ozone.
CI:
https://github.com/adoroszlai/ratis/actions/runs/12805619564

RATIS-2239. Publish build scans to develocity.apache.org

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/RaftLogBase.java

See https://issues.apache.org/jira/browse/RATIS-2240

RATIS-2240. updatePurgeIndex doesn't need to hold RaftLogBase.writeLock

---

ratis-client/src/main/java/org/apache/ratis/client/impl/OrderedAsync.java
ratis-common/src/main/java/org/apache/ratis/util/BatchLogger.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcServerProtocolService.java
ratis-server/src/main/java/org/apache/ratis/server/impl/SnapshotInstallationHandler.java

When one of the Ozone OM falls back and bootstraps, the logs are printed very frequently and it rolls off 30 log files (of 200MB each) in 15 mins. Since logs are rolled off too quick, troubleshooting cause of bootstrap is becoming difficult.
Updated the logging to BatchLogger using the review patch from @szetszwo https://github.com/apache/ratis/pull/1216 - I closed that pull request by mistake.
https://issues.apache.org/jira/browse/RATIS-2244
Logging change. Didnt create unit test for this change.

RATIS-2244. Reduce the number of log messages during bootstrap

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/repeat-test.yml

Ubuntu 20.04 is being deprecated: https://github.com/actions/runner-images/issues/11101
Upgrade to 24.04.
https://issues.apache.org/jira/browse/RATIS-2247
CI:
https://github.com/adoroszlai/ratis/actions/runs/13249818209

RATIS-2247. Bump GitHub Actions runner to ubuntu-24.04

---

rat-excludes.txt

Addendum for #1222.  Exclude bootstrap and jquery minimized scripts for RAT check.
```
./build.sh ../ratis-site
```

RATIS-2250. Add RAT exclusions for bootstrap and jquery

---

.github/workflows/ci.yaml
dev-support/checks/unit.sh
pom.xml
ratis-assembly/pom.xml
ratis-client/pom.xml
ratis-common/src/test/java/org/apache/ratis/test/tag/Flaky.java
ratis-common/src/test/java/org/apache/ratis/test/tag/FlakyTest.java
ratis-docs/pom.xml
ratis-examples/src/test/java/org/apache/ratis/TestMultiRaftGroup.java
ratis-experiments/pom.xml
ratis-metrics-api/pom.xml
ratis-netty/pom.xml
ratis-proto/pom.xml
ratis-replicated-map/pom.xml
ratis-server-api/pom.xml
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-shell/pom.xml
ratis-test/src/test/java/org/apache/ratis/grpc/TestRaftWithGrpc.java
ratis-tools/pom.xml

There are some flaky tests that frequently fail in CI.  Re-running the entire _unit (...)_ check is wasteful.  It may not be successful for a few attempts, as various tests may fail in each re-try.
Changes in this PR:
- introduce `@Flaky` annotation
- identify some tests failing recently and tag them as flaky
- configure Surefire to automatically re-run flaky tests few times until successful
https://issues.apache.org/jira/browse/RATIS-2217
```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.471 s - in org.apache.ratis.server.simulation.TestLeaderElectionWithSimulatedRpc
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.667 s - in org.apache.ratis.grpc.TestLeaderElectionWithGrpc
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 155.428 s <<< …
```

RATIS-2217. Automatically re-try flaky tests in CI

---

ratis-common/src/main/java/org/apache/ratis/conf/ConfUtils.java
ratis-common/src/test/java/org/apache/ratis/util/TestRefCountingMap.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java

Replace few usages of Guava with equivalents from JDK or Ratis.
https://issues.apache.org/jira/browse/RATIS-2022
CI:
https://github.com/adoroszlai/ratis/actions/runs/13572312975

RATIS-2022. Replace some Guava usage with builtins

---

ratis-common/src/main/java/org/apache/ratis/util/AtomicFileOutputStream.java

`AtomicFileOutputStream` should reject overwriting existing temp file.
https://issues.apache.org/jira/browse/RATIS-2260
CI:
https://github.com/adoroszlai/ratis/actions/runs/13900762173

RATIS-2260. AtomicFileOutputStream should truncate temp file

---

dev-support/checks/sonar.sh
pom.xml

Bump Sonar Maven plugin to 5.0.0.4389 in attempt to fix [error](https://github.com/apache/ratis/actions/runs/13903203958/job/38900869515#step:8:2745) in coverage check:
```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project ratis: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to
```
This started happening without related code change.
https://issues.apache.org/jira/browse/RATIS-2263
Verified that version is being picked up and is valid:
```
$ SONAR_TOKEN=invalid ./dev-support/checks/sonar.sh
...
[INFO] --- sonar:5.0.0.4389:sonar (default-cli) @ …
```

RATIS-2263. Bump sonar-maven-plugin to 5.0.0.4389

---

ratis-common/src/main/java/org/apache/ratis/protocol/ClientId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftGroupId.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftId.java
ratis-common/src/main/java/org/apache/ratis/util/BiWeakValueCache.java
ratis-common/src/main/java/org/apache/ratis/util/WeakValueCache.java
ratis-test/src/test/java/org/apache/ratis/protocol/TestRaftId.java
ratis-test/src/test/java/org/apache/ratis/util/TestRaftIdCache.java

RATIS-2266. Use WeakValueCache instead of Guava cache in RaftId.

---

ratis-netty/src/main/java/org/apache/ratis/netty/server/DataStreamManagement.java

Fix documatention for method `DataStreamManagement.StreamInfo#getSuccessors`
https://issues.apache.org/jira/browse/RATIS-2268
Doc fix， no need tests.

RATIS-2268. A minor documatention fix for method getSuccessors.

---

.github/workflows/ci.yaml
dev-support/checks/release.sh
dev-support/make_rc.sh

Add a CI check for testing the first few, local steps of the release process.
https://issues.apache.org/jira/browse/RATIS-2209
https://github.com/adoroszlai/ratis/actions/runs/14155830155/job/39654951998

RATIS-2209. Exercise make_rc.sh in CI

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogInputStream.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogReader.java

After a leader loses leadership due to heartbeat timeout with a majority of followers, it forcibly interrupts the GrpcLogAppender thread.
This abrupt termination leads to two critical exceptions during log file reads:
1. ClosedByInterruptException when initializing SegmentedRaftLogInputStream.
2. A cascading NullPointerException in LogSegment.loadCache() due to incomplete log loading.
https://issues.apache.org/jira/browse/RATIS-2271?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
unit tests

RATIS-2271 Leadership Loss Causes ClosedByInterruptException and NullPointerException in LogAppender Thread

---

ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java

When the leader has no snapshot (forcing log-based catch-up), the new peer might lack timely configuration change logs due to stagingCatchupGap. This leaves the new peer with outdated configurations, violating Raft's membership change safety guarantees.
To solve this problem, the Leader is essentially required to ensure that the configuration of the Follower is the latest when the Follower completes the catch-up.
We add one more condition to the CAUGHTUP judgment logic. That is, CAUGHTUP is complete only after a follower receives the latest conf logs from the leader.
https://issues.apache.org/jira/browse/RATIS-2274
unit tests

RATIS-2274. Newly added peer may retain outdated configuration after membership change, causing election failure.

---

ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java

When a follower receives multiple appendEntries requests from the leader, it may throw an IllegalStateException during log index validation. Specifically, the NavigableIndices class fails to handle concurrent log appends properly, causing the follower to incorrectly reject valid entries with an "index mismatch" error.
The reason is that removeExisting can be called out of order. So we changing the Preconditions to check startIndex.
https://issues.apache.org/jira/browse/RATIS-2278
unit tests

RATIS-2278. Follower Fails to Append Entries Due to Index Validation in NavigableIndices

---

ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/LogSegment.java

Put entry to cache before adding the record.
modify the getLogRecord function with contains.
https://issues.apache.org/jira/browse/RATIS-2282
unit tests

RATIS-2282. LogAppender Restart Due to Premature Log Entry Access During Concurrent Write Processing

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java

Remove Redundant Validation in append()
https://issues.apache.org/jira/browse/RATIS-2278
unit tests

RATIS-2278. Follower Fails to Append Entries Due to Index Validation Race Condition in NavigableIndices

---

ratis-server/src/main/java/org/apache/ratis/server/impl/FollowerState.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderElection.java
ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/StateMachineUpdater.java
ratis-server/src/main/java/org/apache/ratis/server/util/ServerStringUtils.java

We built a unified method for generating the necessary name attributes in the RaftServerImpl submodule.
https://issues.apache.org/jira/browse/RATIS-2286
Ensure that the CI test passes smoothly.
ci: https://github.com/jianghuazhu/ratis/actions/runs/14794277631

RATIS-2286. Generate the necessary unified names for the submodules under RaftServerImpl

---

ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerState.java

The purpose of this PR is to improve RaftServerImpl#toString() to make it more readable.
Old:
`
LEADER s0@group-19104963FACE:t1, leader=s0, voted=s0, raftlog=Memoized:s0@group-19104963FACE-SegmentedRaftLog:OPENED:c0:last(t:1, i:0), conf=conf: {index: 0, cur=peers:[s0|localhost:15000]|listeners:[], old=null} RUNNING
`
New:
`
LEADER-> serverState(s0@group-7219D3B559C9:t1, leader=s0, voted=s0, raftlog=Memoized:s0@group-7219D3B559C9-SegmentedRaftLog:OPENED:c0:last(t:1, i:0), conf=conf: {index: 0, cur=peers:[s0|localhost:15000]|listeners:[], old=null})->RUNNING
`
https://issues.apache.org/jira/browse/RATIS-2287
ci: 
https://github.com/jianghuazhu/ratis/actions/runs/14853381971

RATIS-2287. Improve RaftServerImpl#toString() to make it more readable

---

.github/workflows/check.yaml
.github/workflows/ci.yaml

Calculated coverage is 0% because input files are missing.
```
[WARN] No execution data files provided.
[INFO] Writing execution data to /home/runner/work/ratis/ratis/dev-support/checks/../../target/coverage/jacoco-all.exec.
[INFO] Loading execution data file /home/runner/work/ratis/ratis/dev-support/checks/../../target/coverage/jacoco-all.exec.
[INFO] Analyzing 694 classes.
```
https://github.com/apache/ratis/actions/runs/14887012940/job/41810202866#step:7:1977
The problem is re-definition of `WITH_COVERAGE` variable in `unit` job.  Originally `with-coverage` was supposed to be a workflow input, but it was removed.
This change:
- removes the leftover definition
- defines global `WITH_COVERAGE` depending on whether the workflow is triggered by `push` or `pull_reqest`
- enables `coverage` …

RATIS-2289. Coverage is 0% due to no execution data files provided

---

ratis-common/src/main/java/org/apache/ratis/protocol/RaftClientMessage.java
ratis-common/src/main/java/org/apache/ratis/protocol/RaftId.java
ratis-common/src/main/java/org/apache/ratis/retry/ExponentialBackoffRetry.java
ratis-common/src/main/java/org/apache/ratis/util/JavaUtils.java
ratis-common/src/main/java/org/apache/ratis/util/ReferenceCountedLeakDetector.java
ratis-grpc/src/main/java/org/apache/ratis/grpc/server/GrpcLogAppender.java
ratis-server/src/main/java/org/apache/ratis/server/impl/RaftServerImpl.java
ratis-server/src/main/java/org/apache/ratis/server/impl/ServerImplUtils.java
ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogCache.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-test/src/test/java/org/apache/ratis/server/ServerBuilderTest.java
ratis-test/src/test/java/org/apache/ratis/server/raftlog/segmented/TestSegmentedRaftLogCache.java

We use Objects.requireNonNull() to uniformly replace Preconditions.assertNotNull().
https://issues.apache.org/jira/browse/RATIS-2180
ci: 
https://github.com/jianghuazhu/ratis/actions/runs/14921172685

RATIS-2180. Use Objects.requireNonNull instead of Preconditions.assertNotNull

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java

During the investigation of [RATIS-2251](https://issues.apache.org/jira/browse/RATIS-2251), we encountered a persistent unit test failure in TestInstallSnapshotNotificationWithGrpc#testAddNewFollowersNoSnapshot. Initially, we suspected this was caused by the JUnit version upgrade, but further analysis confirms that the test also fails under JUnit 4. Detailed discussions and debugging steps can be found in the comments of PR #1227.
When addressing the issue with the unit test : TestInstallSnapshotNotificationWithGrpc#testAddNewFollowersNoSnapshot
I found that the error persists even after applying the fix from [RATIS-2045](https://issues.apache.org/jira/browse/RATIS-2045).
[RATIS-2045](https://issues.apache.org/jira/browse/RATIS-2045) fixed the issue where SnapshotInstallationHandler …

RATIS-2291. Fix failing TestInstallSnapshotNotificationWithGrpc#testAddNewFollowersNoSnapshot.

---

ratis-netty/src/main/java/org/apache/ratis/netty/client/NettyClientRpc.java
ratis-server/src/test/java/org/apache/ratis/RaftAsyncTests.java
ratis-server/src/test/java/org/apache/ratis/RaftBasicTests.java

I'm currently follow up on [RATIS-2251](https://issues.apache.org/jira/browse/RATIS-2251), and test results indicate that we have some flaky tests. I'm working on identifying and resolving the root causes.
Specifically, I found that testStaleReadAsync and testStateMachineMetrics are failing because the client doesn't know the correct leaderId, which leads to request failures.
In async mode, if the leaderId is not explicitly specified, the default used in tests is s0. However, during actual test execution with three peers (s0, s1, and s2), any of them can become the leader. Therefore, we need to explicitly set the correct leaderId for the client to ensure reliable communication.
The output of the unit test is as follows:
```
java.util.concurrent.ExecutionException: …
```

RATIS-2294. Fix NettyClientRpc exception and timeout handling

---

.asf.yaml

Set the default commit message to the PR title during merge.  The title can still be edited if needed, but we can avoid picking up single commit's possibly bad message.  (See [.asf.yaml documentation](https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#merge-buttons).)
https://issues.apache.org/jira/browse/RATIS-2297

RATIS-2297. Set default commit message to PR title

---

pom.xml
ratis-common/pom.xml
ratis-common/src/test/java/org/apache/ratis/BaseTest.java
ratis-docs/src/site/markdown/snapshot.md
ratis-examples/pom.xml
ratis-proto/pom.xml
ratis-server/pom.xml
ratis-server/src/test/java/org/apache/ratis/RaftExceptionBaseTest.java
ratis-server/src/test/java/org/apache/ratis/RaftTestUtil.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/StateMachineShutdownTests.java
ratis-test/pom.xml

We will try to remove the junit4 dependency.
JIRA: RATIS-1977. Remove Junit 4 dependencies.
mvn clean test.

RATIS-1977. Remove Junit 4 dependencies.

---

ratis-shell/src/main/java/org/apache/ratis/shell/cli/sh/peer/AddCommand.java

Extend ratis-shell add command to support clientAddress and adminAddress parameters
https://issues.apache.org/jira/browse/RATIS-2323
manual tests within 3 ratis based celeborn masters
```
➜  apache-ratis-3.1.3-bin bin/ratis sh group info -Draft.rpc.type=NETTY -peers zw06-data-k8s-sparktest-cm0003.sankuai.com:9872
group id: c5196f6d-2c34-3ed3-8b8a-47bede733167
leader info: 2(zw06-data-k8s-sparktest-cm0003.sankuai.com:9872)
[server {
id: "2"
address: "zw06-data-k8s-sparktest-cm0003.sankuai.com:9872"
clientAddress: "zw06-data-k8s-sparktest-cm0003.sankuai.com:9097"
adminAddress: "zw06-data-k8s-sparktest-cm0003.sankuai.com:9097"
startupRole: FOLLOWER
}
commitIndex: 1495821
, server {
id: "1"
address: "zw06-data-k8s-sparktest-cm0002.sankuai.com:9872"
clientAddress: …
```

RATIS-2323. Extend ratis-shell add command

---

ratis-server/src/test/java/org/apache/ratis/InstallSnapshotFromLeaderTests.java
ratis-server/src/test/java/org/apache/ratis/InstallSnapshotNotificationTests.java
ratis-server/src/test/java/org/apache/ratis/RaftExceptionBaseTest.java
ratis-server/src/test/java/org/apache/ratis/server/impl/LeaderElectionTests.java
ratis-server/src/test/java/org/apache/ratis/server/impl/MiniRaftCluster.java
ratis-server/src/test/java/org/apache/ratis/server/impl/RaftReconfigurationBaseTest.java
ratis-server/src/test/java/org/apache/ratis/statemachine/RaftSnapshotBaseTest.java
ratis-test/src/test/java/org/apache/ratis/shell/cli/sh/PeerCommandIntegrationTest.java

See RATIS-2332.
Note that this is a test only change.

RATIS-2332. Start new servers with empty peer list in tests.

---

dev-support/make_rc.sh

see https://issues.apache.org/jira/browse/RATIS-2339

RATIS-2339. Avoid "commit does not belong to any branch" during release
